### ISSUE TITLE
[feature required] pouch should support cpu-period and cpu-quota

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#1031]
### Ⅰ. Issue Description

pouch create/run should also support the following args:
```
--cpu-period=0                  Limit CPU CFS (Completely Fair Scheduler) period
  --cpu-quota=0                   Limit CPU CFS (Completely Fair Scheduler) quota
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Could you help to handle this issue? @YaoZengzeng 
In addition, I am wondering if we need to refactor the spec related go files in /pouch/daemon/mgr/spec_*.go?
Since they are some kind of casual. In the past, when we adding a field in spec, we simply add a spec_*.go file.

**Comment by Ace-Tang** [comment]
I think spec related implement is not so good, lots of files `/pouch/daemon/mgr/spec_*.go` make this 
complex.  
@Letty5411 , you can just add this two spec field.

**Comment by allencloud** [comment]
> I think spec related implement is not so good, lots of files /pouch/daemon/mgr/spec_*.go make this
complex.

Actually I cannot quite follow you. @Ace-Tang 
Could you explain more on the complexity?
