### ISSUE TITLE
[make lint] golint: not found has exit code 0, reasonable?

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#1042]
### Ⅰ. Issue Description

I ran my command target in Makefile with `make lint`, while the local PATH has no golint,but it returns a exit code of 0. Is it reasonable?

```
root@i-8brpbc9t:~/go/src/github.com/alibaba/pouch# make lint
lint
/bin/sh: 1: golint: not found
root@i-8brpbc9t:~/go/src/github.com/alibaba/pouch# echo $?
0
root@i-8brpbc9t:~/go/src/github.com/alibaba/pouch#
```

### Ⅱ. Describe what happened
golint: not found has exit code 0

### Ⅲ. Describe what you expected to happen
exit code is non-0.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. checkout the master code
2. remove golint file if it exists in your PATH
3. execute `make lint`

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sunyuan3** [comment]
https://github.com/alibaba/pouch/pull/1059
