### ISSUE TITLE
[bug] command `pouch inspect` does not output an array

### ISSUE THREAD

**Issue by yyb196** [alibaba/pouch#1071]
### Ⅰ. Issue Description

command `pouch inspect` does not output an array,  output a map struct instread. which make stale orchastration system(like swarm) cannot correctlty unmarshal the response of api /containers/xxxx/json.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Thanks for the feedback. Actually you are right. It is an incompatibility with docker cli. However it is a client side incompatibility rather than API side.

Will fix it soon. @yyb196

**Comment by yyb196** [comment]
@allencloud you are right, it's only on the client side.

**Comment by allencloud** [comment]
@faycheng Could you help finish this feature? inspect related feature is implemented by you. It could not be better if you help to make inspect output an array.
