### ISSUE TITLE
[bug] Starting a container with exit value 11 should not return 0.

### ISSUE THREAD

**Issue by sunyuan3** [alibaba/pouch#1075]
### Ⅰ. Issue Description
Starting a container with exit value 11 should not return 0.

### Ⅱ. Describe what happened
Starting a container with exit value 11 returns 0.
In docker, the operation returns 11.

### Ⅲ. Describe what you expected to happen
Starting a container with exit value 11 returns 11.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

```
#pouch create reg.docker.alibaba-inc.com/base/busybox:latest sh -c "exit 11"
container ID: d496b381e6937c26b7333029a02ad213f316b231749d03431d45e304b7e41ae8, name: d496b3

[root@e100069194102.zmf /root/pouchtest/testcases/api_cli]
#pouch start -a d496b3

[root@e100069194102.zmf /root/pouchtest/testcases/api_cli]
#echo $?
0

[root@e100069194102.zmf /root/pouchtest/testcases/api_cli]
#pouch ps
Name   ID   Status   Created   Image   Runtime
```

### Ⅴ. Anything else we need to know?
NA

### Ⅵ. Environment:

- pouch version (use `pouch version`):
#pouch version
Os:              linux
Version:         0.3.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       Fri, 30 Mar 2018 11:50:18 +0800
GitCommit:       69e66f0e6a2dfc6e8c3f56b6f97325523b746da7
GoVersion:       go1.9.1
KernelVersion:   3.10.0-327.ali2015.alios7.x86_64

- OS (e.g. from /etc/os-release):
#cat /etc/os-release
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

- Kernel (e.g. `uname -a`):
#uname -a
Linux e100069194102.zmf 3.10.0-327.ali2015.alios7.x86_64 #1 SMP Sun Feb 11 16:23:43 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by Ace-Tang** [comment]
pouch exec also has such problem, I will fix in another pr.
