### ISSUE TITLE
[bug] "pouch network NotExistOption" returns 0.

### ISSUE THREAD

**Issue by sunyuan3** [alibaba/pouch#1076]
### Ⅰ. Issue Description
"pouch network NotExistOption" returns 0.

### Ⅱ. Describe what happened
"pouch network NotExistOption" returns 0.

### Ⅲ. Describe what you expected to happen
```
"pouch network NotExistOption" returns non-zero.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

#pouch network NotExistOption
Manager the networks in pouchd. It contains the functions of create/remove/list/inspect network, 'driver' is used to list drivers that pouch support. Now bridge network is supported in pouchd defaulted, it will be initialized when pouchd starting.

Usage:
  pouch network [command]

Available Commands:
  create      Create a pouch network
  inspect     Inspect a pouch network
  list        List pouch networks
  remove      Remove a pouch network

Flags:
  -h, --help   help for network

Global Flags:
  -H, --host string        Specify connecting address of Pouch CLI (default "unix:///var/run/pouchd.sock")
      --tlscacert string   Specify CA file of TLS
      --tlscert string     Specify cert file of TLS
      --tlskey string      Specify key file of TLS
      --tlsverify          Use TLS and verify remote

Use "pouch network [command] --help" for more information about a command.

[root@e100069194102.zmf /root/pouchtest/testcases/api_cli]
#echo $?
0
```
### Ⅴ. Anything else we need to know?
NA

### Ⅵ. Environment:

- pouch version (use `pouch version`):
#pouch version
GitCommit:       69e66f0e6a2dfc6e8c3f56b6f97325523b746da7
GoVersion:       go1.9.1
KernelVersion:   3.10.0-327.ali2015.alios7.x86_64
Os:              linux
Version:         0.3.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       Fri, 30 Mar 2018 11:50:18 +0800

- OS (e.g. from /etc/os-release):
#cat /etc/os-release
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

- Kernel (e.g. `uname -a`):
Linux e100069194102.zmf 3.10.0-327.ali2015.alios7.x86_64 #1 SMP Sun Feb 11 16:23:43 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by allencloud** [comment]
I could reproduce this, and I tried `pouch volume nonexist`, it also reports a zero exit code.
