### ISSUE TITLE
questions about Docker compatibility

### ISSUE THREAD

**Issue by AkihiroSuda** [alibaba/pouch#1123]
* The REST API is very similar to Docker. Actually, I confirmed `docker` client can already talk to `pouchd` partially. (`sudo docker -H unix:///var/run/pouchd.sock run -it --network bridge busybox`)
 However, I could not find any documentation about the API compatibility between Pouch and Docker.
 Does Pouch try to guarantee Docker compatibility? Or do they just have semantic similarity?

* How about CLI compatibility?

* Does Pouch plan to implement `docker build` equivalent? 

ref: https://github.com/containerd/containerd/issues/2288

**Comment by allencloud** [comment]
Thanks for your feedback. @AkihiroSuda 

Actually Pouch has an API version of 1.24 which is the same to Moby API version 1.24 in docker 1.12.6. In pouch's API, we split swarm related API from pouch. In addition, we provide a CRI server to support kubernetes kubelet.

> Or do they just have semantic similarity

Yes, they have semantic similarity. And we planning to provide a document that tells others the different part of API compatibility. 

> How about CLI compatibility

First thing, pouch would tries hard to guarantee the API compatibility. However, CLI compatibility is the second thing.

> Does Pouch plan to implement docker build equivalent?

We definitely have a plan to implement this part. But this part is a little bit different from the functionality of `docker build`.

**Comment by AkihiroSuda** [comment]
Thanks for clarification :smiley: 

> But this part is a little bit different from the functionality of docker build.

Could you be more specific about this?

**Comment by allencloud** [comment]
Yes, you may also see an issue in containerd/repo  https://github.com/containerd/containerd/issues/2267.
We will combine this feature into build functionality. We will also add some features into build, for example how to support p2p distribution tool to accomplish image warm up, and so on.

**Comment by AkihiroSuda** [comment]
Thanks :+1:
