### ISSUE TITLE
bug: remove a container complains error EOF

### ISSUE THREAD

**Issue by yyb196** [alibaba/pouch#1150]
### Ⅰ. Issue Description
#pouch rm -f e4864d
Error: failed to remove container: Delete http://d/v1.24/containers/e4864d?force=true: EOF

2018/04/17 19:13:38 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 653 [running]:
net/http.(*conn).serve.func1(0xc420e103c0)
        /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x19815e0, 0x249d780)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).markStoppedAndRelease(0xc42039c510, 0xc420c6fa20, 0xc420d97500, 0xc42030d2c0, 0x40)
        /tmp/pouchbuild/src/github.com/alibaba/pouch/daemon/mgr/container.go:1308 +0x206
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).Remove(0xc42039c510, 0x24cd3c0, 0xc420811e80, 0xc420c7fc19, 0x6, 0xc420e64960, 0x0, 0x0)
        /tmp/pouchbuild/src/github.com/alibaba/pouch/daemon/mgr/container.go:217 +0x213
github.com/alibaba/pouch/apis/server.(*Server).removeContainers(0xc420306e40, 0x24cd3c0, 0xc420811e80, 0x24cc1c0, 0xc420218a80, 0xc420442c00, 0x3, 0x3)
        /tmp/pouchbuild/src/github.com/alibaba/pouch/apis/server/container_bridge.go:33 +0x16a
github.com/alibaba/pouch/apis/server.(*Server).(github.com/alibaba/pouch/apis/server.removeContainers)-fm(0x24cd3c0, 0xc420811e80, 0x24cc1c0, 0xc420218a80, 0xc420442c00, 0xc420442c00, 0xc420b66ad0)
        /tmp/pouchbuild/src/github.com/alibaba/pouch/apis/server/router.go:42 +0x5c
github.com/alibaba/pouch/apis/server.filter.func1(0x24cc1c0, 0xc420218a80, 0xc420442c00)
        /tmp/pouchbuild/src/github.com/alibaba/pouch/apis/server/router.go:146 +0x327
net/http.HandlerFunc.ServeHTTP(0xc420de1aa0, 0x24cc1c0, 0xc420218a80, 0xc420442c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
github.com/alibaba/pouch/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420d87920, 0x24cc1c0, 0xc420218a80, 0xc420442c00)
        /tmp/pouchbuild/src/github.com/alibaba/pouch/vendor/github.com/gorilla/mux/mux.go:133 +0xed
net/http.serverHandler.ServeHTTP(0xc420dab1e0, 0x24cc1c0, 0xc420218a80, 0xc420442800)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420e103c0, 0x24cd3c0, 0xc420811dc0)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HusterWan** [comment]
this problem has been solved, Please rebase your code.
