### ISSUE TITLE
[feature request] add domain name resolve for pouch container

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#1162]
### Ⅰ. Issue Description

currently, pouch container can have network access to broad internet. While when doing domain name resolving, it still lacks /etc/resolv.conf and some other essential things.

### Ⅱ. Describe what happened

No domain name resolving is supported in containers created by pouchd

### Ⅲ. Describe what you expected to happen

domain name resolve works.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by houstar** [comment]
We have a container app for cluster system. In this cluster system,  the container app will be sync the cluster DNS from one of them.  The question is that we can't change the DNS resolver since its defined by Container namespace.  How to solve this in pouch ?

**Comment by HusterWan** [comment]
@houstar thanks a lot for your feedback, we will support specify container'DNS information soon

**Comment by allencloud** [comment]
This is covered in PR https://github.com/alibaba/pouch/pull/1403.
