### ISSUE TITLE
[feature required] pouch support load  and tag 

### ISSUE THREAD

**Issue by 112101160** [alibaba/pouch#1163]
### Ⅰ. Issue Description
Pouch not support 
```
pouch load
pouch tag
```

### Ⅱ. Describe what happened

With out pouch load  and pouch tag ,if network is isolation，we can't get some images

pouch version
GitCommit:       unknown
GoVersion:       go1.9.1
KernelVersion:   3.10.0-327.ali2012.alios7.x86_64
Os:              linux
Version:         0.4.0-dev
APIVersion:      1.24
Arch:            amd64
BuildTime:       unknown

**Comment by fuweid** [comment]
Hi @112101160 , pouch has tag and load functionality right now. For your case, I think we can use `pouch load` to handle your case. Since the docker image format is quite different from oci image, we need the third-party to do the conversion. I have a script, please the following script. First argu is dockerImageTarfile and second argu is image name. Please have a try. Thanks

```
#!/usr/bin/env bash

set -euo pipefail

# check_docker2oci checks the docker2oci command has been installed.
check_docker2oci() {
  command -v docker2oci > /dev/null || {
    echo >&2 "required docker2oci command, please use 'go get -u github.com/coolljt0725/docker2oci'"
    exit 1
  }
}

# import_image imports images.
import_image() {
  local tarfile name tmpdir tmptar

  tarfile=$1
  name=$2

  # docker image format to oci format in tmpdir
  tmpdir=$(mktemp -d -t 'tmpimagedir.XXXXX')
  docker2oci -i "${tarfile}" "${tmpdir}"

  # make oci tar
  tmptar=$(mktemp -t 'tmpimagetar.XXXXX.tar')
  tar -C "${tmpdir}" -cf "${tmptar}" ./

  # load oci tar
  pouch load -i "${tmptar}" "${name}"
}

main() {
  check_docker2oci
  import_image "$@"
}

main "$@"
```

**Comment by allencloud** [comment]
Does this meet your demand? If the answer is yes, please help to close this issue. Thanks a lot. We will absolutely take your demand as the highest priority. 😄

**Comment by 112101160** [comment]
LGTM
