### ISSUE TITLE
[bug] golang version 1.8.3 needs updated in .travis.yml

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#118]
**Issue Description**
We have decided to use golang 1.9.1 instead of 1.8.3. We have updated this version in https://github.com/alibaba/pouch/pull/86 for Dockerfile.

And we need to update .travis.yml:
```

dist: trusty
sudo: required

language: go
go:
  - 1.8.3
    
go_import_path: github.com/alibaba/pouch

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq autoconf automake

script:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo hack/make.sh 
```

Please help to fix up to keep consistent. Thanks a lot.

/cc @sunyuan3

**Comment by gaocegege** [comment]
Could I work on this issue?

**Comment by allencloud** [comment]
Yes, of course. It could not be better. @gaocegege

**Comment by gaocegege** [comment]
#dibs 

I have filed a PR #121 for this issue. But this repository is not activated in Travis CI: https://travis-ci.org/alibaba/pouch.

Or it may be activated in Travis CI private service travis-ci.com, not the public service travis-ci.org, since pouch was a private repository before.

Could you activate the repository in https://travis-ci.org/alibaba/pouch?

@allencloud

**Comment by allencloud** [comment]
Actually, information you provided is really helpful. Now I realized that for private and public repos, they are in different websites. Thanks a lot. We will change this PART. 
/cc @sunyuan3 Could you help to confirm and change the service type from private to public.

**Comment by allencloud** [comment]
@sunyuan3 
Sorry for bothering. Could you improve this issue's priority. 
Actually I need this service type change very urgent.
Since I finished pouch_robot's integration with travis webhook and pouch_robot could automatically report CI failure to user.

**Comment by sunyuan3** [comment]
Nice catch. I have activated travis ci for this public repo.
