### ISSUE TITLE
[proposal] add vagrant envrionment 

### ISSUE THREAD

**Issue by u2takey** [alibaba/pouch#1243]
### Ⅰ. Issue Description
As many developer use macos/windows for development, i propose adding vagrant environment  to facilitate development for such users.

If this seems reasonable, i can help to init this environment (vagrantfile as related docs).

**Comment by HusterWan** [comment]
@u2takey thanks a lot for your feedback, maybe @fuweid can research setup the vagrant environment  😀

**Comment by fuweid** [comment]
Hi @u2takey ,  happy to hear!!!

I think it's reasonable. You can show your PR 😀 . If you want to help us to do that, please consider to make the setup script reusable, because the setup way of Vagrant is the same to Dockerfile. 

Please go ahead!

**Comment by fuweid** [comment]
Thanks @u2takey 's help.
