### ISSUE TITLE
[bug] pull image failed because layer Unavailable

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#1289]
### Ⅰ. Issue Description
Pull image may occur error like below:
```
time="2018-05-09T10:08:52.647646492+08:00" level=info msg="Calling POST /v1.21/images/create?fromImage=reg.docker.alibaba-inc.com%2Fcise%2Fcise_5u7%3Alatest, client 100.81.193.96:51440 ali api.sigma.alibaba-inc.com"
time="2018-05-09T10:08:52+08:00" level=error msg="(*service).Write failed" error="rpc error: code = Unavailable desc = ref default/20/layer-sha256:e1de758ecc1ddd05500991af89af53dda8317a01434399299ca0ee365cb76605 locked: unavailable" expected=sha256:e1de758ecc1ddd05500991af89af53dda8317a01434399299ca0ee365cb76605 ref="layer-sha256:e1de758ecc1ddd05500991af89af53dda8317a01434399299ca0ee365cb76605"
time="2018-05-09T10:08:52+08:00" level=error msg="(*service).Write failed" error="rpc error: code = Unavailable desc = ref default/18/layer-sha256:1e61a346f526b812f8c3fc0260864d8cf713685b2bb061b01f2a6a91f9db0f7e locked: unavailable" expected=sha256:1e61a346f526b812f8c3fc0260864d8cf713685b2bb061b01f2a6a91f9db0f7e ref="layer-sha256:1e61a346f526b812f8c3fc0260864d8cf713685b2bb061b01f2a6a91f9db0f7e"
time="2018-05-09T10:08:53+08:00" level=error msg="(*service).Write failed" error="rpc error: code = Unavailable desc = ref default/1/layer-sha256:5473b8d0b28cc5851e104d699a4304228bcee929d3edbccfb859e404984049b4 locked: unavailable" expected=sha256:5473b8d0b28cc5851e104d699a4304228bcee929d3edbccfb859e404984049b4 ref="layer-sha256:5473b8d0b28cc5851e104d699a4304228bcee929d3edbccfb859e404984049b4"
time="2018-05-09T10:08:54+08:00" level=error msg="(*service).Write failed" error="rpc error: code = Unavailable desc = ref default/12/layer-sha256:12ce15d527c7183c18b91bd5d1f458e9ed9cc72badfc45e9b28013f911d48de7 locked: unavailable" expected=sha256:12ce15d527c7183c18b91bd5d1f458e9ed9cc72badfc45e9b28013f911d48de7 ref="layer-sha256:12ce15d527c7183c18b91bd5d1f458e9ed9cc72badfc45e9b28013f911d48de7"
time="2018-05-09T10:08:54+08:00" level=error msg="(*service).Write failed" error="rpc error: code = Unavailable desc = ref default/16/layer-sha256:895e7b13325aac67123ecbd4c6c112777664c8b48a62dcd83a824845c848d382 locked: unavailable" expected=sha256:895e7b13325aac67123ecbd4c6c112777664c8b48a62dcd83a824845c848d382 ref="layer-sha256:895e7b13325aac67123ecbd4c6c112777664c8b48a62dcd83a824845c848d382"
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by aish84** [comment]
Hi...
I am facing similar issue:

time="2021-06-23T10:33:09.356680772Z" level=info msg="(*service).Write started" expected=sha256:71d18c84b8bcf400ce1438e11d8ef083235f8a1b831377c6aaf3316c49a62577 ref="manifest-sha256:71d18c84b8bcf400ce1438e11d8ef083235f8a1b831377c6aaf3316c49a62577" total=1987 
time="2021-06-23T10:33:10.144400316Z" level=info msg="(*service).Write started" expected=sha256:f166560182f4b59caaac26cc85f995d35f6a4f2794dd12139c8836d9f30dce29 ref="layer-sha256:f166560182f4b59caaac26cc85f995d35f6a4f2794dd12139c8836d9f30dce29" total=9846978 
time="2021-06-23T10:33:10.144594931Z" level=info msg="(*service).Write started" expected=sha256:**86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61** ref="layer-sha256:**86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61**" total=452 
time="2021-06-23T10:33:10.144685817Z" level=info msg="(*service).Write started" expected=sha256:09c96d9ba319d99d87a04ac268665f4044fdb22604b6edf8df615a5fe3a48ce7 ref="config-sha256:09c96d9ba319d99d87a04ac268665f4044fdb22604b6edf8df615a5fe3a48ce7" total=4008 
time="2021-06-23T10:33:10.144935027Z" level=info msg="(*service).Write started" expected=sha256:30c4f36455780a4f0524c118b9e1bbc5090f23002fc833b5126cfe554e897772 ref="layer-sha256:30c4f36455780a4f0524c118b9e1bbc5090f23002fc833b5126cfe554e897772" total=159 
time="2021-06-23T10:33:10.145030504Z" level=info msg="(*service).Write started" expected=sha256:53145554340ff8935717a51df12b890131a4dc8bddd36f974d6e708295d5b479 ref="layer-sha256:53145554340ff8935717a51df12b890131a4dc8bddd36f974d6e708295d5b479" total=3558949 
time="2021-06-23T10:33:10.145026142Z" level=info msg="(*service).Write started" expected=sha256**:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61** ref="layer-sha256:**86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61**" total=452 
time="2021-06-23T10:33:10.145113013Z" level=info msg="(*service).Write started" expected=sha256:bfd56785b2072bf10c1ed547a45ac48a7692615c43eae0401aa6a948f3e38263 ref="layer-sha256:bfd56785b2072bf10c1ed547a45ac48a7692615c43eae0401aa6a948f3e38263" total=1359 
time="2021-06-23T10:33:10.145048824Z" level=info msg="(*service).Write started" expected=sha256:2608f212ec72d09f4c89635f4870cb4003ee40314da0ba94ffb8d442c8b1179b ref="layer-sha256:2608f212ec72d09f4c89635f4870cb4003ee40314da0ba94ffb8d442c8b1179b" total=2016 
time="2021-06-23T10:33:10.145107952Z" level=info msg="(*service).Write started" expected=sha256:098583992d2a8ece12ea30579d5c81c7930f8c1bbf4deae66e0a0871703f572a ref="layer-sha256:098583992d2a8ece12ea30579d5c81c7930f8c1bbf4deae66e0a0871703f572a" total=8054024 
time="2021-06-23T10:33:10.463532389Z" level=error msg="(*service).Write failed" error="rpc error: code = Unavailable desc = ref saberos/1/layer-sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61 locked: unavailable" expected=sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61 ref="layer-sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61" total=452 
time="2021-06-23T10:33:10.479514503Z" level=info msg="(*service).Write started" expected=sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61 ref="layer-sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61" total=452 
time="2021-06-23T10:33:10.742405154Z" level=error msg="(*service).Write failed" error="rpc error: code = Unavailable desc = ref saberos/1/layer-sha256:**86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61** locked: unavailable" expected=sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61 ref="layer-sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61" total=452 
time="2021-06-23T10:33:10.745139140Z" level=info msg="(*service).Write started" expected=sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61 ref="layer-sha256:86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61" total=452 



As we can see: Write fails always for this 86e3b68989a785191ae693e751fb25f97b1942e09c81545585e153df3407ca61 even after retries.
