### ISSUE TITLE
[bug] usage of "pouch volume rm" should be changed

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#129]
**Issue Description**
The usage of pouch volume remove is as following:
```
#pouch volume remove
Error: requires at least 1 arg(s), only received 0
Usage:
  pouch volume remove [volume] [flags]

Aliases:
  remove, rm

Flags:
  -h, --help   help for remove
```
According to this usage, [volume] is not mandatory，but actually it is.
The usage could be changed to：
```
Usage:
  pouch volume remove <volume name> [flags]
```
**Describe what happened**:

**Describe what you expected to happen**:
Usage format could refer to this:
https://stackoverflow.com/questions/9725675/is-there-a-standard-format-for-command-line-shell-help-text

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I totally agree with you. And we need more general usage for command line indeed.
This change needs to apply to all commands, not only volume command. Although this part of work seems not heavy, but important instead. I recommend you would help this? @Letty5411 🎏

**Comment by Letty5411** [comment]
@allencloud OK, np.
