### ISSUE TITLE
pouch version command shouldn't  access to pouchd

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#1292]
### Ⅰ. Issue Description
at present, it is irrelevant with pouchd or pouch server for major output information of pouch version command, so a non-root user can get pouch version information without any communicate with pouchd, such as Arch, BuildTime, GitCommit, GoVersion, KernelVersion, OS, Version and APIVersion, etc.

### Ⅱ. Describe what happened
a non-root user can't get pouch version information

### Ⅲ. Describe what you expected to happen
a non-root can get pouch version information

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. $pouch version
Error: failed to get system version: Get http://d/v1.24/version: dial unix /var/run/pouchd.sock: connect: permission denied

### Ⅴ. Anything else we need to know?
$docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   11fdb9f BUILDTIME:2018-04-23 17:35:23
 Built:        Mon Apr 23 09:35:22 2018
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?  <---need to access docker daemon then get output.

### Ⅵ. Environment:

pouch version (use pouch version):
$sudo pouch version
APIVersion: 1.24
Arch: amd64
BuildTime: unknown
GitCommit: unknown
GoVersion: go1.9.1
KernelVersion: 3.10.0-327.ali2012.alios7.x86_64
Os: linux
Version: 0.4.0

OS (e.g. from /etc/os-release):
$cat /etc/os-release
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

Kernel (e.g. uname -a):
$uname -r
3.10.0-327.ali2012.alios7.x86_64

Install tools:
default

Others:
nothing

**Comment by Letty5411** [comment]
If this bug if fixed, please also remember to edit test related script:
https://github.com/alibaba/pouch/blob/master/hack/testing/utils.sh#L46
