### ISSUE TITLE
[bug] pouchd shouldn't be started successfully if related kernel module missing

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#1301]
### Ⅰ. Issue Description
Running pouchd command in background shouldn't be started successfully if related kernel module missing, such as 'nf_nat'.

### Ⅱ. Describe what happened
To compile upstream pouch and running pouchd command in background in ecs, although 'nf_nat' module is missing in default ecs, pouchd still is running successfully with some warning information,
in fact, /var/run/pouchd.sock hasn't been created successfully, so it must be failed when trying to use pouch client later.

### Ⅲ. Describe what you expected to happen
some related kernel module are missing, pouchd should be failed to start and raise expected error.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. to compile pouch
2. running pouchd command 
3. open a new terminal and run pouch command

### Ⅴ. Anything else we need to know?

```
$ git rev-parse HEAD
188acff33e4b815b247b23ad04a340622bfa3071

$ sudo pouchd --debug
INFO[0000] start daemon at debug level                  
INFO[2018-05-10T13:31:56.727064068Z] ctrd: new containerd process, pid: 37        
INFO[0000] starting containerd                           module=containerd revision=773c489c9c1b21a6d78b5c538cd395416ec50f88 version=v1.0.3
INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd

<ignore .../>

INFO[2018-05-10T13:31:56.766900617Z] success to create 5 containerd clients, connect to: /var/run/containerd.sock 
DEBU[2018-05-10T13:31:56.767274772Z] Get a grpc client                             elapsed=2.568µs
DEBU[2018-05-10T13:31:56.772085364Z] Option DefaultDriver: bridge                 
DEBU[2018-05-10T13:31:56.772158972Z] Option DefaultNetwork: bridge                
WARN[2018-05-10T13:31:56.77288184Z] Running modprobe nf_nat failed with message: ``, error: exec: "modprobe": executable file not found in $PATH 
WARN[2018-05-10T13:31:56.772964225Z] Running modprobe xt_conntrack failed with message: ``, error: exec: "modprobe": executable file not found in $PATH 
DEBU[2018-05-10T13:31:56.773411276Z] Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory, using raw iptables instead 
DEBU[0000] garbage collected                             d=4.171956ms module="containerd/io.containerd.gc.v1.scheduler"
```

NOTE: pouchd is running without exiting

### Ⅵ. Environment:

- pouch version (use `pouch version`):
$ git rev-parse HEAD
188acff33e4b815b247b23ad04a340622bfa3071

- OS (e.g. from /etc/os-release):
# cat /etc/os-release   
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
$ uname -a
Linux e010125002163.bja 3.10.0-327.ali2012.alios7.x86_64 #1 SMP Mon Oct 9 14:09:14 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
related development packages to compile pouch

- Others:

**Comment by allencloud** [comment]
I do agree with you that pouchd should do some pre-checking to validate the running environment when startup. It could stop running or at least throw out some warning messages and so on.

Then I think we could split the work into two parts:

* list all the dependent environment conditions including kernel modules you mentioned;
* add a validateEnv function or something like that to make codes defensive.

WDYT? @chuanchang

**Comment by chuanchang** [comment]
@allencloud Absolutely agree!
