### ISSUE TITLE
there are many typos in pouch documents

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#1302]
### Ⅰ. Issue Description
there are many typos in pouch documents

### Ⅱ. Describe what happened
misspell error in documents

### Ⅲ. Describe what you expected to happen
typo

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.  it grep -E '(infrastucture|orchestraion|inovative|architeture|generlized|exiciting|provied|ident|fuctionality)'

and so on.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
➜  pouch git:(fix_typo) git rev-parse HEAD
8323ad0232bd06c5cb21c99ce293bf66cbcd2942

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
$ uname -a
Linux e010125002163.bja 3.10.0-327.ali2012.alios7.x86_64 #1 SMP Mon Oct 9 14:09:14 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by allencloud** [comment]
Yes, I have decided to add a tool which is named by `mispell` into our CI system to avoid this kind of issue. @chuanchang 
I am wondering if you have interest to help make it. 😄
