### ISSUE TITLE
[feature request]Add retry in auth request

### ISSUE THREAD

**Issue by fatkun** [alibaba/pouch#1310]
### Ⅰ. Issue Description
Our cluster in china and india, the registry deploy in china. The network between china and india is not good sometimes.

### Ⅱ. Describe what happened
Pouch pull image sometimes raise TLSHandshakeTimeout error, and exit.
The request url is  https://someregistryurl.com:5000/v2
Download image file have retry, should auth also should support retry.

### Ⅲ. Describe what you expected to happen

1. add some retry in auth period?
2. request timeout configurable?

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fuweid** [comment]
Hi @fatkun , Thanks for the suggestion. 

I think it's reasonable. But, could you mind to provide the information about how you use the `pouch pull`? If you use it in the shell script, you can handle retry in your script before we provide the functionality. What do you think?

We also welcome you to help us to build the functionality. Please let's know what do you think. Thanks

**Comment by fatkun** [comment]
@fuweid we use pouch in kubernetes, I'm new with it and I don't know if there have retry config.

I'm new in container world, and learn golang a little...

**Comment by fuweid** [comment]
@fatkun It's OK. We will handle the case. If you run into any issue or have any question about using pouch, please don't hesitate to file issue to us. 😄
