### ISSUE TITLE
[flaky test] PouchRestartSuite.TestPouchRestart fails unexpectedly

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#1323]
### Ⅰ. Issue Description

When I searching Ci failure of pr https://github.com/alibaba/pouch/pull/1307, I found some flaky test there. And I try to reproduce them in the CI system and on my local machine. Unfortunately, I failed to make it. 

Here is the flaky test error message. While although it is flaky, I have no idea about what happened in the test case. I am wondering if we could find a way to throw out some detailed error message? @Letty5411 

```shell
----------------------------------------------------------------------
FAIL: /go/src/github.com/alibaba/pouch/test/cli_restart_test.go:34: PouchRestartSuite.TestPouchRestart
/go/src/github.com/alibaba/pouch/test/cli_restart_test.go:40:
    c.Assert(res.Error, check.IsNil)
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420cb56c0), Stderr:[]uint8(nil)} ("exit status 1")
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Letty5411** [comment]
The following c.Assert could be changed to `res.Assert`
```	
        res := command.PouchRun("restart", "-t", "1", name)
	c.Assert(res.Error, check.IsNil)
```
