### ISSUE TITLE
[question] do we have a plan to revendor libnetwork to the latest version or stable one

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#1344]
### Ⅰ. Issue Description

We have vendor libnetwork to take advantages of libnetwork's ability on network management. While I am afraid that currently we met several serious issues ever which are not so easy to handle, so we did some tricky work to handle this:

* use a very strange way to vendor libnetwork in `extra`(https://github.com/alibaba/pouch/tree/master/extra/libnetwork);
* log package logrus brings so much inconvenience.

I think we should take more things into consideration whether to use latest or stable version of libnetwork to bring more convenience. 

ping @rudyfly

**Comment by idealhack** [comment]
I found this is not easy with govendor. Have you considered migrating to dep?

**Comment by fuweid** [comment]
Hi @idealhack，could you mind to explain the special thing in `dep`? Thanks

**Comment by idealhack** [comment]
@fuweid dep is a better package manager in general and it is maintain by Go team.

**Comment by idealhack** [comment]
In fact, I encounter some problems with pouch and govendor, for example:

1. setting up new dependencies in a fresh environment is somehow difficult.

2. some packages in are not direct dependencies of pouch currently in `vendor.json`.

3. why does so many different packages use a same revision `2b8ed96d2a422bf205adcdfa05272dc12c81613b`?
