### ISSUE TITLE
[test] blkio.weight_device: operation not supported

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#1346]
### Ⅰ. Issue Description

In CI testing of https://travis-ci.org/alibaba/pouch/jobs/380096926, we found the error log of pouchd:

`
time="2018-05-17T08:51:32.610992909Z" level=error msg="failed to create new containerd container: failed to create task for container(8ac3611239f4519c41fe09fc09f75ca2e2f9844d7b5893ae4ebb34d71edae156): OCI runtime create failed: container_linux.go:265: starting container process caused "process_linux.go:348: container init caused \"process_linux.go:320: setting cgroup config for procHooks process caused \\\"failed to write 8:0 100 to blkio.weight_device: write /sys/fs/cgroup/blkio/default/8ac3611239f4519c41fe09fc09f75ca2e2f9844d7b5893ae4ebb34d71edae156/blkio.weight_device: operation not supported\\\"\"": unknown"
`

I do not think this is reasonable. 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): master code 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Ace-Tang** [comment]
I check the ci log, found 
```
FAIL: /go/src/github.com/alibaba/pouch/test/cli_upgrade_test.go:143: PouchUpgradeSuite.TestPouchUpgradeContainerLabels
/go/src/github.com/alibaba/pouch/test/cli_upgrade_test.go:150:
    command.PouchRun("upgrade", "--label", "test1=bar", "--name", name, busyboxImage125).Assert(c, icmd.Success)
/go/src/github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd/command.go:61:
    t.Fatalf("at %s:%d - %s\n", filepath.Base(file), line, err.Error())
... Error: at cli_upgrade_test.go:150 - 
Command:  /usr/local/bin/pouch upgrade --label test1=bar --name TestPouchUpgradeContainerLabels registry.hub.docker.com/library/busybox:1.25
ExitCode: 1
Error:    exit status 1
Stdout:   
Stderr:   Error: {"message":"failed to create new container: failed to create task for container(d6cd78aeb7fa50d38c25cdcaa8c8aa24581b45cd0a9d35d567301541625419ec): OCI runtime create failed: container_linux.go:265: starting container process caused \"process_linux.go:348: container init caused \\\"process_linux.go:331: running prestart hook 0 caused \\\\\\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\\\\\\\\\"2018-05-17T08:54:35Z\\\\\\\\\\\\\\\" level=fatal msg=\\\\\\\\\\\\\\\"no sandbox present for d6cd78aeb7fa50d38c25cdcaa8c8aa24581b45cd0a9d35d567301541625419ec\\\\\\\\\\\\\\\" \\\\\\\\n\\\\\\\"\\\"\": unknown"}
```
The fail container is  d6cd78aeb7fa50d38c25cdcaa8c8aa24581b45cd0a9d35d567301541625419ec but not 8ac3611239f4519c41fe09fc09f75ca2e2f9844d7b5893ae4ebb34d71edae15 you post, could you double check this, @allencloud

**Comment by Letty5411** [comment]
The error message is from the following test:
```
// TestRunBlockIOWeightDevice tests running container with --blkio-weight-device flag.
func (suite *PouchRunSuite) TestRunBlockIOWeightDevice(c *check.C) {
  cname := "TestRunBlockIOWeightDevice"
  testDisk, found := environment.FindDisk()
  if !found {
    c.Skip("fail to find available disk for blkio test")
  }

  command.PouchRun("run", "-d", "--blkio-weight-device", testDisk+":100",
    "--name", cname, busyboxImage, "sleep", "10000").Stdout()
  defer DelContainerForceMultyTime(c, cname)

  // test if the value is in inspect result
  output := command.PouchRun("inspect", cname).Stdout()
  result := []types.ContainerJSON{}
  if err := json.Unmarshal([]byte(output), &result); err != nil {
    c.Errorf("failed to decode inspect output: %v", err)
  }

  c.Assert(len(result[0].HostConfig.BlkioWeightDevice), check.Equals, 1)
  c.Assert(result[0].HostConfig.BlkioWeightDevice[0].Path, check.Equals, testDisk)
  c.Assert(result[0].HostConfig.BlkioWeightDevice[0].Weight, check.Equals, uint16(100))

  // test if cgroup has record the real value
  //containerID := result.ID
  //{
  //  path := fmt.Sprintf("/sys/fs/cgroup/blkio/default/%s/blkio.weight_device", containerID)
  //  checkFileContains(c, path, "100")
  //}
}
```

**Comment by Letty5411** [comment]
In CI log, it shows this test PASS. I guess as the test code does't check the exit code of `pouch run`, it maybe fail at `pouch start` stage. In this situation, create container successfully and `inspect` could work.

**Comment by Letty5411** [comment]
In CI log, it shows this test PASS. I guess as the test code does't check the exit code of `pouch run`, it maybe fail at `pouch start` stage. In this situation, create container successfully and `inspect` could work.

**Comment by allencloud** [comment]
> The fail container is d6cd78aeb7fa50d38c25cdcaa8c8aa24581b45cd0a9d35d567301541625419ec but not 8ac3611239f4519c41fe09fc09f75ca2e2f9844d7b5893ae4ebb34d71edae15 you post.

You are correct, so I think the error log of pouchd and test case failure are unrelated. @Ace-Tang

**Comment by Letty5411** [comment]
>  the error log of pouchd and test case failure are unrelated
Yes.
Although the error log and fail case is unrelated, you have actually found a test bug! 
I will fix it.

**Comment by Ace-Tang** [comment]
@Letty5411 , #1381 fix blkio_device set error.

**Comment by allencloud** [comment]
I think we can close this after discussing about it with @Ace-Tang offline.
