### ISSUE TITLE
[bug] the image number in pouch info not equal to uniq count of pouch images 

### ISSUE THREAD

**Issue by lovejoy** [alibaba/pouch#1347]
### Ⅰ. Issue Description
```
# pouch images
IMAGE ID       IMAGE NAME                                       SIZE
8ac48589692a   registry.hub.docker.com/library/busybox:latest   710.83 KB
```

```
# pouch info  | grep Images
Images:  0
```

### Ⅲ. Describe what you expected to happen
 pouch info  | grep Images should be 1

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.install freshly on  centos  https://github.com/alibaba/pouch/blob/master/INSTALLATION.md 
2.pouch pull busybox
3.pouch images

### Ⅵ. Environment:

- pouch version (use `pouch version`):
Os:              linux
Version:         0.4.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       Wed, 18 Apr 2018 11:16:54 +0800
GitCommit:       5caea368e2adae0f173049bec2020d4e882dda66
GoVersion:       go1.9.1
KernelVersion:   3.10.0-514.el7.x86_64
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I would like to involve @fuweid as he is an image expert of Pouch.

**Comment by lovejoy** [comment]
Reproduce
on a newly created  CentOS Linux release 7.3.1611 (Core) vmMachine
```
yum install -y yum-utils
yum-config-manager --add-repo http://mirrors.aliyun.com/opsx/opsx-centos7.repo
yum install -y  pouch
systemctl start pouch
pouch pull busybox
pouch images -> have busybox
pouch info | grep Images -> 0
```
蛤？

**Comment by fuweid** [comment]
Hi @lovejoy , sorry that we missing the `gitCommit` info as you provided. 

The `Pouchv0.4` version you using doesn't support to show the image information. In the this PR #1238 , we have supported this field. Please wait for the next version or use the master version to build the pouch. 

BTW, we still have some empty fields and welcome to help us make pouch better. Please let us know if you have any issues during using pouch. Thanks 😄
