### ISSUE TITLE
[feature request] Is there a need to add a filter to `pouch ps`

### ISSUE THREAD

**Issue by wrfly** [alibaba/pouch#1358]
### Ⅰ. Issue Description

feature discussion 

### Ⅱ. Describe what happened

Add a filter to `pouch ps`

### Ⅲ. Describe what you expected to happen

`pouch ps -f image=hello-world`

`pouch ps -f state=stopped -f runtime=runc`

**Comment by shaloulcy** [comment]
good  feature!

**Comment by allencloud** [comment]
Yes, I think we need this feature. This will make tool much more user-friendly. @wrfly 
Would you help to make it?

**Comment by wrfly** [comment]
@allencloud Yeah, I'd happy to do that.

**Comment by allencloud** [comment]
Hi, @wrfly 
Could you share some details about the progress of this work?

**Comment by wrfly** [comment]
Time flies... I haven't start working on this for now...

I think it would be a break feature since not only `pouch ps` but also `pouch images` and other commands may need this `filter`. Only working on `ps` filter is short-sighted. I have to plan it well and then start to coding.

I'll update this issue after a deep consideration as soon as possible. And I'd appreciate it if you can give me some suggestions 🙇

**Comment by wrfly** [comment]
Hello @allencloud 

I'm a little confused with this filter function:

https://github.com/alibaba/pouch/blob/4fbc44f99eeff5f9ed7e624d5d7b7b4541ac88bf/daemon/mgr/container.go#L420-L426

I think we should treat `all` as a filter too. For example, if I want to get all `stopped` containers, I will add a filter(`status=stopped`), but in this case, although I passed this filter, I cannot get what I want. And there seems a conflict between the `ContainerListOption` and the `ContainerFilter` function.

So I suggest to combine these two arguments. I don't think it the caller's duty to make the filter function:

https://github.com/alibaba/pouch/blob/4fbc44f99eeff5f9ed7e624d5d7b7b4541ac88bf/apis/server/container_bridge.go#L105-L110

The caller should only tell the options, and then the manager will do the job for him.

The same as the image manager. (But the `ListImages` function just has a filter string slice and I cannot understand why.)

https://github.com/alibaba/pouch/blob/4fbc44f99eeff5f9ed7e624d5d7b7b4541ac88bf/daemon/mgr/image.go#L143-L147

As for the filter option, I think it should represent the container(or the image or other objects)'s specification(such as `runtime=runv`, `age>1d`, `image=nginx:latest`), we can use `reflect` to decide the types and select the containers we want.

I will write a snippet later.

**Comment by wrfly** [comment]
PTL, https://play.golang.org/p/o5JmVAL9RXL

**Comment by ZYecho** [comment]
@wrfly @allencloud the `ps filter` already have added, is current filter key satisfy your requirement？
