### ISSUE TITLE
[enhance] skip coverage for storage directory

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#1363]
### Ⅰ. Issue Description
PR#1338 has introduced a method to get test coverage of integration tests.
In  hack/build, it skips this directory: "github.com/alibaba/pouch/storage", because if not, the following CI will fail:
```
#go test -check.f TestInfo
[ceph demo local tmpfs]

----------------------------------------------------------------------
FAIL: api_system_test.go:33: APISystemSuite.TestInfo

api_system_test.go:58:
    c.Assert(len(got.VolumeDrivers), check.Equals, 3)
... obtained int = 4
... expected int = 3

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (0.06s)
```

This means that if this directory isn't skipped, volume driver `demo` will be registered into pouchd binary, which is not expected. 

And what is wired is that if we only skip `github.com/alibaba/pouch/storage/examples` or `github.com/alibaba/pouch/storage/examples/demo`, it can't solve the problem. That is the `demo` volume driver still registered.
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fuweid** [comment]
has been fixed.
