### ISSUE TITLE
Latest fpm fails to install on centos:7.2.1511: "ruby-xz requires Ruby version >= 2.3.0"

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#1369]
### Ⅰ. Issue Description
Latest fpm fails to install on centos:7.2.1511: "ruby-xz requires Ruby version >= 2.3.0"

### Ⅱ. Describe what happened
Trying to build RPM by ./hack/package/package.sh, and will got error as follows:
**ERROR:  Error installing fpm:
	ruby-xz requires Ruby version >= 2.3.0.**

### Ⅲ. Describe what you expected to happen
success to install fpm.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. docker build https://raw.githubusercontent.com/alibaba/pouch/master/hack/package/rpm/centos-7/Dockerfile.x86_64

### Ⅴ. Anything else we need to know?
The latest fpm requires Ruby version >= 2.3.0, and the current centos:7.2.1511
only can provide ruby-2.0.0.648-33.el7_4, so the result is failed to build RPM.

$ sudo docker build https://raw.githubusercontent.com/alibaba/pouch/master/hack/package/rpm/centos-7/Dockerfile.x86_64
Downloading build context from remote url: https://raw.githubusercontent.com/alibaba/pouch/master/hack/package/rpm/centos-7/Dockerfile.x86_64 1.066 kB
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM centos:7.2.1511
 ---> 0a2bad7da9b5
Step 2 : RUN yum update -y     && yum install -y     wget     git     gcc     ruby-devel     fuse     fuse-devel     pam-devel     automake     autoconf     libtool     make     rpm-build     rpm-sign     rubygems     vim     tree     && yum clean all
 ---> Using cache
 ---> adbb3ed6d82b
Step 3 : RUN gem install --no-ri --no-rdoc fpm
 ---> Running in 36bf8925a296
Successfully installed cabin-0.9.0
Successfully installed backports-3.11.3
Successfully installed arr-pm-0.0.10
Successfully installed clamp-1.0.1
Building native extensions.  This could take a while...
**ERROR:  Error installing fpm:
	ruby-xz requires Ruby version >= 2.3.0.**
Successfully installed ffi-1.9.23
Successfully installed childprocess-0.9.0
The command '/bin/sh -c gem install --no-ri --no-rdoc fpm' returned a non-zero code: 1

### Ⅵ. Environment:

- pouch version (use `pouch version`):
$ git rev-parse HEAD
1e75a1190a46d8b84113462ad33b96636d5242a5

- OS (e.g. from /etc/os-release):
$ sudo cat /etc/os-release 
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

- Kernel (e.g. `uname -a`):
$ uname -r
3.10.0-327.ali2012.alios7.x86_64

- Install tools:
$ rpm -q alidocker
alidocker-1.12.6.27-1615116.alios7.x86_64

- Others:
nothing

**Comment by allencloud** [comment]
Has this issue fixed? @chuanchang 
If the answer is yes, we will close this issue.

**Comment by allencloud** [comment]
Discussed with @chuanchang offline. It has been solved in fact. Closing this.
