### ISSUE TITLE
pouch logs command doesn't work

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#1371]
### Ⅰ. Issue Description
pouch logs can't get logs on running container

### Ⅱ. Describe what happened
using pouch logs to get log from running a container, nothing is returned 

### Ⅲ. Describe what you expected to happen
pouch logs command should work as docker logs

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. cid=$(pouch run --name test -d busybox sh -c "while true; do $(echo date); sleep 1; done")
2. pouch logs $cid

### Ⅴ. Anything else we need to know?
$ cid=$(sudo docker run --name test -d busybox sh -c "while true; do $(echo date); sleep 1; done")
$ sudo docker logs $cid
Mon May 21 10:08:46 UTC 2018
Mon May 21 10:08:47 UTC 2018
Mon May 21 10:08:48 UTC 2018
Mon May 21 10:08:49 UTC 2018
Mon May 21 10:08:50 UTC 2018
Mon May 21 10:08:51 UTC 2018
Mon May 21 10:08:52 UTC 2018
Mon May 21 10:08:53 UTC 2018
Mon May 21 10:08:54 UTC 2018
Mon May 21 10:08:55 UTC 2018
Mon May 21 10:08:56 UTC 2018
Mon May 21 10:08:57 UTC 2018
Mon May 21 10:08:58 UTC 2018
Mon May 21 10:08:59 UTC 2018
Mon May 21 10:09:00 UTC 2018
Mon May 21 10:09:01 UTC 2018
Mon May 21 10:09:02 UTC 2018
Mon May 21 10:09:03 UTC 2018
Mon May 21 10:09:04 UTC 2018

$ rpm -q alidocker
alidocker-1.12.6.27-1615116.alios7.x86_64

### Ⅵ. Environment:

- pouch version (use `pouch version`):
$ git rev-parse HEAD
1e75a1190a46d8b84113462ad33b96636d5242a5

- OS (e.g. from /etc/os-release):
$ sudo cat /etc/os-release 
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

- Kernel (e.g. `uname -a`):
$ uname -r
3.10.0-327.ali2012.alios7.x86_64

- Install tools:
nothing

- Others:
nothing

**Comment by allencloud** [comment]
Could you help to take a look at this? @fuweid

**Comment by fuweid** [comment]
Hi @allencloud and @chuanchang , since I have only finished the Pouch Logs API in the last PR, the Pouch Logs CLI is no-op. I will make it works. For now, it's expected.

**Comment by allencloud** [comment]
Any update on this? @fuweid
