### ISSUE TITLE
[question] It seems that pouch won't pull the image automatically when run a container?

### ISSUE THREAD

**Issue by wrfly** [alibaba/pouch#1379]
If that image doesn't exist on my host, `pouch` won't pull the image thus failed to run. It looks wired since `docker` will pull images automatically if the image doesn't exist.

Is it by design?

```bash
➜  pouch git:(master) sudo ./pouch run --name test registry.hub.docker.com/library/busybox:latest echo "hi"
Error: failed to run container: {"message":"image: registry.hub.docker.com/library/busybox:latest: not found"}

➜  pouch git:(master)
```

The `pouch` is built from the master branch.

**Comment by fuweid** [comment]
Hi @wrfly , right now `pouch run` doesn't support it. I think we can use this issue to track this. 

BTW, welcome you to help us to make it happen  😄

**Comment by wrfly** [comment]
I'll contribute as long as I get familiarly with `pouch`(and have spare time if I can...)
