### ISSUE TITLE
[enhancement request]  image management implementation

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#138]
**Issue Description**

We need to polish image management in pouch, in API side, daemon side, client side, cli side, doc side and test side. Please record in this issue if some parts are finished.

In every aspect, if finished, please add a reference to the corresponding PR.

## image pull

- [x] image pull 
  - [x] API design in swagger:
  - [x] daemon side implement:
  - [x] client side implement:
  - [x] cli implement:
  - [x] document:
  - [x] test: 

## image list

- [x] image list
  - [x] API design in swagger:
  - [x] daemon side implement:
  - [x] client side implement:
  - [x] cli implement:
  - [x] document:
  - [x] test: 

## image rm

- [x] image rm
  - [x] API design in swagger:
  - [x] daemon side implement:
  - [x] client side implement:
  - [x] cli implement:
  - [x] document:
  - [x] test: 

## image inspect  

- [x] image inspect @0x04C2
  - [x] API design in swagger:
  - [x] daemon side implement:
  - [x] client side implement:
  - [x] cli implement:
  - [x] document:
  - [x] test:

**Comment by allencloud** [comment]
Could you help to finish the **Image Inspect** part? @0x04C2 
Thanks a lot. 🍷

**Comment by 0x04C2** [comment]
Yes. Sure. I have created branch in my local :)

**Comment by allencloud** [comment]
I think we could close this. In the future, we need to work out the build and push functionality.
