### ISSUE TITLE
[feature request] support lxcfs in pouch to improve isolation

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#140]
**Issue Description**

[LXCFS](https://github.com/lxc/lxcfs) is a small FUSE filesystem written with the intention of making Linux containers feel more like a virtual machine.

Pouch takes lxcfs support as a high priority.

We need to add these things in pouch with lxcfs:

- [ ] Design document of pouch and lxcfs;
- [ ] API integration in Pouch via lxcfs;
- [ ] daemon side implementation
- [ ] test for lxcfs
  - [ ] unit test
  - [ ] integration test

/cc @CodeJuan

**Comment by allencloud** [comment]
Any update with this, maybe you could make a plan to attach your thought under this issue. Thanks @CodeJuan

**Comment by CodeJuan** [comment]
According to the issue from lxcfs [Anyone think about the problem of restart the lxcfs.service](https://github.com/lxc/lxcfs/issues/193), when lxcfs stopped(or crashed) and restarted, it would be unmounted in the process and caused `Transport endpoint is not connected`. So we should monitor the lxcfs mount/umount event, and exec mount command in container.

**Comment by CodeJuan** [comment]
I found a non-intrusive method to integrate lxcfs with Pouch.
1. Bind the path of lxcfs and the **/proc** to container, `-v /var/lib/lxc/:/var/lib/lxc/:shared  -v /var/lib/lxc/lxcfs/proc/uptime:/proc/uptime -v /var/lib/lxc/lxcfs/proc/swaps:/proc/swaps  -v /var/lib/lxc/lxcfs/proc/stat:/proc/stat  -v /var/lib/lxc/lxcfs/proc/diskstats:/proc/diskstats -v /var/lib/lxc/lxcfs/proc/meminfo:/proc/meminfo -v /var/lib/lxc/lxcfs/proc/cpuinfo:/proc/cpuinfo`
2. If the lifecycle of Pouch is managed by systemd, just add a `remount script` to lxcfs.service.ExecStartPost
3. When lxcfs restarted, systemd would run the `remount script` to remount **/proc** in container

**Comment by allencloud** [comment]
I am wondering what is the kernel version requirement of lxcfs.
If you know that, could you update you comment with adding  kernel requirement?
Thanks @CodeJuan

**Comment by CodeJuan** [comment]
pseudocode of container_remount_lxcfs.sh
```sh
LXCFS="/var/lib/lxc/lxcfs"

containers=$(pouch ps | awk '{print $1}' | grep -v CONTAINER)
for container in $containers;do
        echo "remout $container"
        PID=$(pid of $container)
        for file in meminfo cpuinfo stat uptime swaps diskstats;do
                nsenter $PID --mount --  mount -B "$LXCFS/proc/$file" "/proc/$file"
        done
done
```

**Comment by CodeJuan** [comment]
```
+---------------------+
|                     |        +------------+
|                     |        |            |
|                     +--------+  lxcfs     +-------------------------+
|                     |        |            |                         |
|Pouchd --enable-lxcfs|        +------------+                   +-----+-------------------+
|                     |                                         |                         |
|                     |                             +------------>/var/lib/lxc/lxcfs      |
|                     |                             |           |                         |
+----+----------------+                             |     +------>/var/lib/lxc/lxcfs/proc |
     |                                              |     |     |                         |
     |                                              |     |     +-------------------------+
     |                                              |     |
     |                                              |     |
     |                                              |     |
     |                                              |     |
     |            +---------------------------+     |     |
     |            |                           |     |     |
     |            | Container                 |     |     |
     |   create   |                           |     |     |
     +------------>                           |     |     |
     |            |                           |     |     |
     |            |                           |     |     |
     |            |                           |     |     |
     |            |    +----------------------+     |     |
     |            |    | /var/lib/lxc+--------------+     |
     | remount    |    |                      |           |
     +-----------------> /proc/meminfo        |           |
                  |    | /proc/cpuinfo+-------------------+
                  |    | ...                  |
                  |    | ...                  |
                  |    |                      |
                  +----+----------------------+

```

**Comment by allencloud** [comment]
Yeah, thanks for your design. In your architecture, I found that you enabled this flag in pouchd. If that, I am afraid all containers will be influenced by lxcfs.
I am wondering if we could add the functionality that enable every single container by `pouch create --enable-lxcfs` or something like other?
@CodeJuan

**Comment by CodeJuan** [comment]
@allencloud Great idea. Please have a look at the updated diagram.

**Comment by allencloud** [comment]
Set this in 0.1 milestone. And we are supposed to finish before Jan 10. @CodeJuan 😄

**Comment by mdianjun** [comment]
@CodeJuan  I used your method like this, but nsenter failed:
```
# nsenter --target 25043 --mount -- mount -B /var/lib/lxc/lxcfs/proc/meminfo /proc/meminfo
nsenter: failed to execute mount: No such file or directory
```
Do you known why?

**Comment by mdianjun** [comment]
ssss

**Comment by markzhang0928** [comment]
@CodeJuan  hi, i had already tried this command as you mentioned,
nsenter --target ${PID} --mount -- mount -B /var/lib/lxc/lxcfs/proc/meminfo /proc/meminfo
but it doesn't work and return mount: mount point /proc/meminfo does not exist.

I also found a solution for remount a volume to a running docker container , it's said that the major:minjor device id of block dev should be send to container mnt namespace via nsenter . But , lxcfs seems to be a special device in container, i am not sure if that it's necessory .

when i tried to use this command,
./importenv /proc/2738/environ nsenter --target 2738 --mount --uts --ipc --net --pid -- sh -c "mount -t fuse.lxcfs lxcfs /tmpmnt"

it returns:
mount: wrong fs type, bad option, bad superblock on /lxcfs, missing codepage or helper program, or other error In some cases useful info is found in syslog - try dmesg | tail or so

i'm really confused. looking forward to your answer. thx!

**Comment by senthilnathann** [comment]
Hi ,

Not able to remount the proc files inside the containers ,
whil executing below command ,

nsenter --target 8799 --mount -- mount -B /usr/local/var/lib/lxcfs/proc/meminfo /proc/meminfo

mount: mount /usr/local/var/lib/lxcfs/proc/meminfo on /proc/meminfo failed: Transport endpoint is not connected

Pls check and help

**Comment by fanhaozzu** [comment]
@senthilnathann me too,@CodeJuan help?

**Comment by fanhaozzu** [comment]
nsenter --target 8799 --mount -- mount -B /usr/local/var/lib/lxcfs/proc/meminfo /proc/meminfo

mount: mount /usr/local/var/lib/lxcfs/proc/meminfo on /proc/meminfo failed: Transport endpoint is not connected

**Comment by fanhaozzu** [comment]
![image](https://user-images.githubusercontent.com/5517088/47850320-c8d3ce80-de0f-11e8-9952-199fc7b8e2c9.png)

**Comment by senthilnathann** [comment]
@CodeJuan Pls help on this

**Comment by xigang** [comment]
@senthilnathann @fanhaozzu Please use this script:)
https://github.com/xigang/lxcfs-admission-webhook/blob/dev/script/container_remount_lxcfs.sh

**Comment by Billyxxu** [comment]
> @senthilnathann @fanhaozzu Please use this script:)
> https://github.com/xigang/lxcfs-admission-webhook/blob/dev/script/container_remount_lxcfs.sh

Hi, I used your script, but still couldn't solve the problem.Pls help

**Comment by g0194776** [comment]
@senthilnathann @Billyxxu 
We've solved the problem. You have to use 2 layers folder path to mount lxcfs directory into your container.

for example:
---
OLD: /usr/local/var/lib/lxcfs

NEW: /usr/local/var/lib/lxc/lxcfs

and...please mount path `/usr/local/var/lib/lxc` into your container. After lxcfs crashed and restarted, You can use bash command to remount it again.

**Comment by Billyxxu** [comment]
> @senthilnathann @Billyxxu
> We've solved the problem. You have to use 2 layers folder path to mount lxcfs directory into your container.
> 
> ## for example:
> OLD: /usr/local/var/lib/lxcfs
> 
> NEW: /usr/local/var/lib/lxc/lxcfs
> 
> and...please mount path `/usr/local/var/lib/lxc` into your container. After lxcfs crashed and restarted, You can use bash command to remount it again.

Thks for your help, I have solved the problem in the container according to your method. But is there a good solution in Kubernetes? I see that pouchcontainer handles this problem in the source code, but I use docker, and I have to change the source code as well?

**Comment by g0194776** [comment]
@Billyxxu 
You can use admission hook to mount those of paths automatically, [Here](https://github.com/g0194776/lxcfs-admission-webhook) is my copy.

**Comment by Billyxxu** [comment]
> @Billyxxu
> You can use admission hook to mount those of paths automatically, [Here](https://github.com/g0194776/lxcfs-admission-webhook) is my copy.

good idea. thks
