### ISSUE TITLE
[flaky test case] about Image Create API test

### ISSUE THREAD

**Issue by fuweid** [alibaba/pouch#1433]
### Ⅰ. Issue Description

The case uses timeout to wait for the pull action. We should read the data until server finishes.

```
// TestImageCreateWithoutTag tests creating an image without tag, will use "latest" by default.
func (suite *APIImageCreateSuite) TestImageCreateWithoutTag(c *check.C) {
        q := url.Values{}
        q.Add("fromImage", environment.HelloworldRepo)
        query := request.WithQuery(q)
        resp, err := request.Post("/images/create", query)
        c.Assert(err, check.IsNil)
        CheckRespStatus(c, resp, 200)

        time.Sleep(5000 * time.Millisecond)

        resp, err = request.Delete("/images/" + environment.HelloworldRepo + ":latest")
        c.Assert(err, check.IsNil)
        CheckRespStatus(c, resp, 204)
}
```

### Ⅱ. Describe what happened

If the network is not stable, the case will fail.

### Ⅲ. Describe what you expected to happen

The case should be stable!!!!!!!

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiechengsheng** [comment]
This seems to be the same case as `pouch wait` test ^_^

**Comment by fuweid** [comment]
@xiechengsheng Could you mind to help us to fix the flaky case? We need to read the data from data stream like [PullImage](https://github.com/alibaba/pouch/blob/master/test/util_api.go#L284). Do you want to have a try? 😄

**Comment by xiechengsheng** [comment]
I'm sorry I'm not familiar with PullImage's data stream. :joy:

**Comment by fuweid** [comment]
fixed by https://github.com/alibaba/pouch/pull/2042
