### ISSUE TITLE
name conflicts of lxcfs

### ISSUE THREAD

**Issue by eryx** [alibaba/pouch#1476]
### Ⅰ. Issue Description

lxcfs is not included in the CentOS's default repository, so pouch includes of lxcfs or lxcfs.service in the pouch.rpm package. the problem is, lxcfs is a shared service, other projects (docker, rkt, ...) may also use lxcfs, so here's a question of name or paths conflicts in yum/rpm. 

advice:
1. individually packaged as lxcfs-*.rpm, use the default file paths and service name of lxcfs, can share with other projects.
2. use customized file paths (/usr/pouch/*, /var/lib/pouch-lxcfs/, ...) and service name (pouch-lxcfs.service) of lxcfs, continue to be included in pouch.rpm, for pouch use only.

### Ⅵ. Environment:

- pouch version (use `pouch version`): 0.5.0
- OS (e.g. from /etc/os-release): CentOS 7.x
- Kernel (e.g. `uname -a`): 3.10.0
- Install tools: yum
- Others:

**Comment by Letty5411** [comment]
I would prefer the later one, use a new name like `pouch-lxcfs`.
