### ISSUE TITLE
[panic] restart pouchd may panic

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#1481]
### Ⅰ. Issue Description
restart pouchd chance occur panic:
![image](https://user-images.githubusercontent.com/10414039/41087257-c66bfec0-6a6e-11e8-910c-c806291d2c01.png)

the panic caused by the running container `abc85` , and if i kill the container process,  restarting pouchd  will success 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
+1

**Comment by zhuangqh** [comment]
**How to reproduce**
1. Up a container
2. In https://github.com/alibaba/pouch/blob/master/daemon/mgr/container.go#L210, just assign `container.Config.OpenStdin = false`.
3. compile & restart pouchd

**Where is the problem**

In https://github.com/alibaba/pouch/blob/master/daemon/containerio/container_io.go#L58, if opt.stdin is false, io.stdin would be nil, which leads to panic.
```
github.com/alibaba/pouch/daemon/containerio.NewIO at container_io.go:58
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).openContainerIO at container.go:1477
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).Restore.func1 at container.go:212
github.com/alibaba/pouch/pkg/meta.(*Store).ForEach at store.go:197
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).Restore at container.go:232
github.com/alibaba/pouch/daemon.(*Daemon).Run at daemon.go:181
main.runDaemon.func2 at main.go:202
runtime.goexit at asm_amd64.s:2337
```
As a result, in https://github.com/alibaba/pouch/blob/master/daemon/containerio/cio.go#L125, ioset.in may be nil value. But it is not simply equal to nil. https://golang.org/doc/faq#nil_error
```
github.com/alibaba/pouch/daemon/containerio.copyIO at cio.go:120
github.com/alibaba/pouch/daemon/containerio.WithAttach.func1 at cio.go:214
github.com/alibaba/pouch/vendor/github.com/containerd/containerd.attachExistingIO at container.go:304
github.com/alibaba/pouch/vendor/github.com/containerd/containerd.(*container).loadTask at container.go:274
github.com/alibaba/pouch/vendor/github.com/containerd/containerd.(*container).Task at container.go:143
github.com/alibaba/pouch/ctrd.(*Client).RecoverContainer at container.go:183
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).Restore.func1 at container.go:217
github.com/alibaba/pouch/pkg/meta.(*Store).ForEach at store.go:197
github.com/alibaba/pouch/daemon/mgr.(*ContainerManager).Restore at container.go:232
github.com/alibaba/pouch/daemon.(*Daemon).Run at daemon.go:181
main.runDaemon.func2 at main.go:202
runtime.goexit at asm_amd64.s:2337
```

**Comment by HusterWan** [comment]
@zhuangqh can you help us to fix this bug ? 🍻 😃

**Comment by zhuangqh** [comment]
@HusterWan sure. 

It is tricky that `ioset.in == nil` is always false(see https://golang.org/doc/faq#nil_error). My solution is adding a condition `&& ioset.in.(*ContainerIO) != nil` to avoid nil pointer. But the data in `ioset` is just a interface `io.Reader`. I am afraid that my solution may lose the generality.

I am wondering anybody has a better solution or WDYT about my solution

**Comment by fuweid** [comment]
keep eyes on this issue. will reopen it if show up again.
