### ISSUE TITLE
[bug] open file but does't close in lxcfs.go  

### ISSUE THREAD

**Issue by truth** [alibaba/pouch#1488]
in "lxcfs.go " file, open the file "/proc/1/mountinfo" , but does't  close it. 

add this code after opening:
`defer f.Close() `

**Comment by HusterWan** [comment]
@truth Thanks a lot for your feedback, Could you help us to fix this problem? 😆

**Comment by truth** [comment]
file : 'lxcfs/lxcfs.go'
line 32: 
`fr := bufio.NewReader(f)`
add code:
`f.Close()`

**then:**
`f.Close()
fr := bufio.NewReader(f)
`

**Comment by HusterWan** [comment]
@truth we hope you can create a pull request for pouch, and fix the problem.  feel free to contact us, if you have any problem. 

how to PR you can read doc below: 
https://github.com/alibaba/pouch/blob/master/CONTRIBUTING.md#workspace-preparation
