### ISSUE TITLE
bridge networks can not work if the docker and pouch been installed in the same host

### ISSUE THREAD

**Issue by eryx** [alibaba/pouch#1497]
### Ⅰ. Issue Description

bridge networks can not work if the docker and pouch been installed in the same host.

### Ⅱ. Describe what happened

i found pouch used the same bridge gateway of 172.17.0.1, that with the same default value of docker.

``` shell
docker network inspect bridge
[
    {
        "Name": "bridge",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        }
    }
]


pouch network inspect bridge
[
    {
        "Driver": "bridge",
        "IPAM": {
            "Config": [
                {
                    "Gateway": "172.17.0.1",
                    "Subnet": "172.17.0.1/24"
                }
            ],
            "Driver": "default"
        }
    }
]


ifconfig

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ...

p0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ...
```

### Ⅲ. Describe what you expected to happen

add a logic for gateway conflict check before pouch create the default bridge networking ?

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): 0.5.0
- OS (e.g. from /etc/os-release): CentOS 7.x
- Kernel (e.g. `uname -a`):
- Install tools: yum
- Others:

**Comment by chuanchang** [comment]
@eryx AFAIK, the docker and pouch can't coexist in the same host, maybe, you may wait for other developers confirm this.
