### ISSUE TITLE
[bug] CI fail with TestTailLine

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#1517]
### Ⅰ. Issue Description
```bash
11:45:40 FAIL: /go/src/github.com/alibaba/pouch/test/cli_logs_test.go:94: PouchLogsSuite.TestTailLine
11:45:40 
11:45:40 /go/src/github.com/alibaba/pouch/test/cli_logs_test.go:120:
11:45:40     c.Assert(allLogs, check.HasLen, tc.expected)
11:45:40 ... obtained []string = []string{"hello-1", "hello-2", "hello-3", "hello-4", "hello-5", "hello-6", "hello-7", "hello-8", "hello-9", "hello-10", "hello-11", "hello-12", "hello-13", "hello-14", "hello-15", "hello-16", "hello-17", "hello-18", "hello-19", "hello-20", "hello-21", "hello-22", "hello-23", "hello-24", "hello-25", "hello-26", "hello-27", "hello-28", "hello-29", "hello-30", "hello-31", "hello-32", "hello-33", "hello-34", "hello-35", "hello-36", "hello-37", "hello-38", "hello-39", "hello-40", "hello-41", "hello-42", "hello-43", "hello-44", "hello-45", "hello-46", "hello-47", "hello-48", "hello-49", "hello-50", "hello-51", "hello-52", "hello-53", "hello-54", "hello-55", "hello-56", "hello-57", "hello-58", "hello-59", "hello-60", "hello-61", "hello-62", "hello-63", "hello-64", "hello-65", "hello-66", "hello-67", "hello-68", "hello-69", "hello-70", "hello-71", "hello-72", "hello-73", "hello-74", "hello-75", "hello-76", "hello-77", "hello-78", "hello-79", "hello-80", "hello-81", "", "hello-85", "hello-86", "hello-87", "hello-88", "hello-89", "hello-90", "hello-91", "hello-92", "hello-93", "hello-94", "hello-95", "hello-96", "hello-97", "hello-98", "hello-99"}
11:45:40 ... n int = 100
```

### Ⅱ. Describe what happened
as above, and sometimes test cases will exit due to timeout

### Ⅲ. Describe what you expected to happen
the test result is ok for PouchLogsSuite.TestTailLine

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. to compile upstream pouch
2. run pouch daemon in background
3. run test PouchLogsSuite.TestTailLine

### Ⅴ. Anything else we need to know?
Test result is passed on Ubuntu 16.04.4

# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

# uname -a
Linux virtualbox 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Ⅵ. Environment:

- pouch version (use `pouch version`):
#git rev-parse HEAD
3f0c62f324c0fbcd4a648f561973bb9a4334847e

- OS (e.g. from /etc/os-release):
#cat /etc/os-release 
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

- Kernel (e.g. `uname -a`):
#uname -a
Linux r10a07137.sqa.zmf 4.9.65-006.ali3000.alios7.x86_64 #1 SMP Mon Dec 4 14:39:09 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by fuweid** [comment]
This issue has been fixed basically. If the issue comes up again, please reopen it, thanks @chuanchang
