### ISSUE TITLE
[refactor] The code related to CRI has a lot of redundancy

### ISSUE THREAD

**Issue by Starnop** [alibaba/pouch#1524]
### Ⅰ. Issue Description
For compatibility with the two versions of kubernetes CRI, we have maintained two pieces of code temporarily. Now it is time to optimize it. Actually, we have to maintain two pieces of code to some extent, but we can extract the common part to reduce redundancy. It is necessary even will take a lot of effort.

### Ⅱ. Describe what happened
as above

### Ⅲ. Describe what you expected to happen
 reduce the code redundancy

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

None

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Starnop** [comment]
I will do that！

**Comment by allencloud** [comment]
Any update on this?

**Comment by Starnop** [comment]
@allencloud  Yes, the code about `Stream` and `CNI` has been refactored. More work will be done later.
