### ISSUE TITLE
[feature request] pouch [ps|containers list API] with filter functionality

### ISSUE THREAD

**Issue by fuweid** [alibaba/pouch#1562]
### Ⅰ. Issue Description

For now, the pouch list containers API doesn't support filter function. It's very useful for the monitor or schedule system. PouchContainer has the following requirements:

- [ ] id - Container’s ID
- [ ] name - Container’s 
- [ ] status - One of created, restarting, running, removing, paused, exited, or dead
- [ ] label - An arbitrary string representing either a key or a key-value pair. 

For example, we can use the following command to filter container by id:

```
pouch ps --filter id=fcd6279d2069
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yyb196** [comment]
filter according to label name and value is another requirment, moby only support filter by label euqals, we need filter by label doesn't equal. 
eg:
```
pouch ps --filter "label=color!=blue"
```

**Comment by Ace-Tang** [comment]
Already support the follow:
- id - Container’s ID
- name - Container’s 
- status - One of created, restarting, running, removing, paused, exited, or dead
- label - An arbitrary string representing either a key or a key-value pair. 

also support unequal condition, like `pouch ps --filter "label=color!=blue"`
