### ISSUE TITLE
[help wanted]How to successfully get a full list of prometheus-formatted metrics

### ISSUE THREAD

**Issue by ZeroMagic** [alibaba/pouch#157]
**Issue Description**
https://github.com/alibaba/pouch/blob/master/docs/pouch_with_prometheus.md#how-to-use
When I use the above way, I think the default port is 4243,  but after running pouchd the port 4243 isn't being used. 

Then I search the way to run pouchd with the specific port. Nothing gained.

I can't find the command line flags to specify port. 

And no configuration files to change port.

So, I can't get a full list of prometheus-formatted metrics by `curl http://127.0.0.1:4243/metrics`

**Comment by WIZARD-CXY** [comment]
You can use ```pouchd -l tcp://0.0.0.0:4243```. I know our doc may be not enough, feel free to add it in the doc.

**Comment by ZeroMagic** [comment]
@WIZARD-CXY  Works fine. Thanks.

**Comment by WIZARD-CXY** [comment]
Glad I can help
