### ISSUE TITLE
[help wanted][test] need to supplement new test cases.

### ISSUE THREAD

**Issue by sunyuan3** [alibaba/pouch#1594]
### Ⅰ. Issue Description
Currently, integrated test case don’t cover most of pouch command. We need to supplement some test cases.

Resource Management:
- [x] --blkio-weight
- [x] --blkio-weight-device
- [x] --cpu-period
- [x] --cpu-quota
- [x] --cpu-share
- [x] --cpuset-cpus
- [x] --cpuset-mems
- [x] --device-read-bps
- [x] --device-read-iops
- [x] --device-write-bps
- [x] --device-write-iops
- [x] -m, --memory
- [x] --memory-swap
- [x] --memory-swappiness
- [x] --memory-wmark-ratio
- [x] --oom-kill-disable
- [x] --oom-score-adj
- [x] --pids-limit

**Comment by allencloud** [comment]
What is the status of this issue? @sunyuan3 
I am afraid that we could update this. 😄

**Comment by sunyuan3** [comment]
@allencloud The above command options have be covered in test cases. So I would close this issue.

**Comment by allencloud** [comment]
thanks greatly for your work on quality improvement. @sunyuan3 😄 🍻
