### ISSUE TITLE
[bug] log output from `pouch exec -it xxx bash` is out of order

### ISSUE THREAD

**Issue by layneYoo** [alibaba/pouch#1596]
### Ⅰ. Issue Description
The pouch's output is out of order while running the command of "pouch exec -it containerName bash"

### Ⅱ. Describe what happened
a. pouch exec -it containerName bash 
b. ls -l 
the output like this (out of order):
total 0
lrwxrwxrwx.   1 root root    7 Nov 29  2017 bin -> usr/bin

wxr-xr-x.   3 root root   18 May 14 12:19 boot
drwxr-xr-x.  15 root root 3160 Jun 25 19:54 dev
drwxr-xr-x.   1 root root   68 Jun 25 20:00 etc
drwxr-xr-x.   2 root root    6 Nov  5  2016 home
lrwxrwxrwx.   1 root root    7 Nov 29  2017 lib -> usr/lib
lrwxrwxrwx.   1 root root    9 Nov 29  2017 lib64 -> usr/lib64
drwxr-xr-x.   2 root root    6 Nov  5  2016 media

wxr-xr-x.   2 root root    6 Nov  5  2016 mnt
drwxr-xr-x.   1 root root   31 May 15 09:44 opt
dr-xr-xr-x. 384 root root    0 Jun 25 19:54 proc

-xr-x---.   1 root root   43 Jun 26 10:28 root
drwxr-xr-x.   4 root root  100 Jun 25 19:54 run
lrwxrwxrwx.   1 root root    8 Nov 29  2017 sbin -> usr/sbin
drwxr-xr-x.   2 root root    6 Nov  5  2016 srv
dr-xr-xr-x.  13 root root    0 Mar 20 12:28 sys
drwxrwxrwt.   1 root root    6 Jun 26 10:00 tmp
drwxr-xr-x.   1 root root   54 Nov 29  2017 usr
drwxr-xr-x.   1 root root   41 May 14 12:19 var

### Ⅲ. Describe what you expected to happen
**The correct result：**
total 12
lrwxrwxrwx   1 root root    7 Nov 29  2017 bin -> usr/bin
drwxr-xr-x   3 root root   18 May 14 12:19 boot
drwxr-xr-x  14 root root 3020 Jun 20 15:56 dev
drwxr-xr-x  70 root root 4096 Jun 20 16:43 etc
drwxr-xr-x   2 root root    6 Nov  5  2016 home
lrwxrwxrwx   1 root root    7 Nov 29  2017 lib -> usr/lib
lrwxrwxrwx   1 root root    9 Nov 29  2017 lib64 -> usr/lib64
drwxr-xr-x   2 root root    6 Nov  5  2016 media
drwxr-xr-x   2 root root    6 Nov  5  2016 mnt
drwxr-xr-x   4 root root   31 Jun 20 16:38 opt
dr-xr-xr-x 206 root root    0 Jun 20 15:56 proc
dr-xr-x---   6 root root  317 Jun 23 14:48 root
drwxr-xr-x  13 root root  195 May 17 12:19 run
lrwxrwxrwx   1 root root    8 Nov 29  2017 sbin -> usr/sbin
drwxr-xr-x   2 root root    6 Nov  5  2016 srv
dr-xr-xr-x  13 root root    0 Jun 20 15:56 sys
drwxrwxrwt  27 root root 4096 Jun 26 10:41 tmp
drwxr-xr-x  13 root root  155 Nov 29  2017 usr
drwxr-xr-x  19 root root  265 May 14 12:19 var

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Run a container using pouch
2. pouch exec -it xxx bash
3. Run a bash command, eg: ls -l

### Ⅴ. Anything else we need to know?
Most commands have the same problem.

### Ⅵ. Environment:

- pouch version (use `pouch version`): 0.5.0
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Install tools: 
- Others:

**Comment by fuweid** [comment]
Hi @layneYoo , Sorry for the late reply.

I used the vagrant to setup centos7 to test it, but I don't get the bug as you mentioned. So, Could you mind to use master branch to check again?  or help us to identify the issue? Thanks

**Comment by layneYoo** [comment]
OK，Thanks~
