### ISSUE TITLE
[help wanted][doc] add doc to describe how to use `pouch run --log-driver`

### ISSUE THREAD

**Issue by fuweid** [alibaba/pouch#1599]
### Ⅰ. Issue Description

The PouchContainer has supported the `json`, `syslog` log driver, but user doesn't have the document to check how to use `pouch run --log-driver`. 

We need to add document like [rich container mode](https://github.com/alibaba/pouch/blob/master/docs/features/pouch_with_rich_container.md) to describe the `log-driver` usage.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hellolijj** [comment]
Is there anybody do this work? if not, i'd like to do this work :)

**Comment by fuweid** [comment]
fixed by #2677
