### ISSUE TITLE
[help wanted][robot] avoid the old, untracked issue 

### ISSUE THREAD

**Issue by fuweid** [alibaba/pouch#1600]
### Ⅰ. Issue Description

The user or developer will create issue to PouchContainer for issue report or something. For some issues, with some reason, we cannot reproduce the issue or has it fixed. However, the issue will look like orphan in the system. 

For this reason, I propose to add the functionality in the PouchRobot to close the issue if no-one comments in **30** days. If PouchContainer still has the issue, this action will let the owner know that there is one orphan need help.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Frankzhaopku** [comment]
Close this one and move the issue to pouchrobot repo instead. The link is [here](https://github.com/pouchcontainer/pouchrobot/issues/30).
