### ISSUE TITLE
[bug] pouch api response should return all the fields in one request

### ISSUE THREAD

**Issue by fuweid** [alibaba/pouch#1601]
### Ⅰ. Issue Description

For example, In the `/exec/{execID}/json`, if the exec has been finished successfully, both the `running` and `exitCode` are omitted in the JSON response because the tag is `json:"xx,omitempty"`. 

If the consumer is build on the ruby or other language, both the `running` and `exitCode` will disappear in the hash map. It's not correct. 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I think we have fixed this, right? See the `ContainerExecInspect` definition:
```
// ContainerExecInspect holds information about a running process started.
// swagger:model ContainerExecInspect

type ContainerExecInspect struct {

	// can remove
	// Required: true
	CanRemove bool `json:"CanRemove"`

	// The ID of this container
	// Required: true
	ContainerID string `json:"ContainerID"`

	// detach keys
	// Required: true
	DetachKeys string `json:"DetachKeys"`

	// The last exit code of this container
	// Required: true
	ExitCode int64 `json:"ExitCode"`

	// The ID of this exec
	// Required: true
	ID string `json:"ID"`

	// open stderr
	// Required: true
	OpenStderr bool `json:"OpenStderr"`

	// open stdin
	// Required: true
	OpenStdin bool `json:"OpenStdin"`

	// open stdout
	// Required: true
	OpenStdout bool `json:"OpenStdout"`

	// process config
	// Required: true
	ProcessConfig *ProcessConfig `json:"ProcessConfig"`

	// running
	// Required: true
	Running bool `json:"Running"`
}
```

If my thought is correct, please help to close this? Otherwise please give us more update about this. Thanks a lot. @fuweid

**Comment by fuweid** [comment]
@allencloud this is one case. I think we should make all response like this case. But there is limitation from swagger, which we can't share the same struct on both request and response. We need to investigate the way to make it happen in swagger, I guess.

**Comment by allencloud** [comment]
I think in master this issue is solved by pr https://github.com/alibaba/pouch/pull/2350
