### ISSUE TITLE
[help wanted] add tests for TODO test

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#1603]
### Ⅰ. Issue Description
Some tests in pouch/test are not implemented yet. 
You need to check files under pouch/test and find them.
Here is a raw list: 

- [ ] PouchRichContainerSuite.TestRichContainerDumbInitWrongArgs
- [x] PouchExecSuite.TestExecInteractive
- [x] APIImageTagSuite.TestImageTagUsingNoFoundSourceImage
- [ ] APIImageSearchSuite.TestImageSearchOk
- [x] APIImageListSuite.TestImageListFilter
- [x] APIImageDeleteSuite.TestDeleteNonExisting
- [x] APIImageCreateSuite.TestImageCreateNil
- [x] APIContainerStopSuite.TestNonExistingContainer
- [x] APIContainerStopSuite.TestInvalidParam
- [x] APIContainerStartSuite.TestNonExistingContainer
- [ ] APIContainerStartSuite.TestInvalidParam
- [x] APIContainerPauseSuite.TestNonExistingContainer
- [x] APIContainerLogsSuite.TestNoSuchContainer
- [x] APIContainerInspectSuite.TestNonExistingContainer
- [x] APIContainerInspectSuite.TestInspectNoSuchContainer
- [ ] APIContainerExecStartSuite.TestContainerExecStartStopped
- [ ] APIContainerExecStartSuite.TestContainerExecStartPaused
- [ ] APIContainerExecStartSuite.TestContainerExecStartDup
- [x] APIContainerDeleteSuite.TestDeleteNonExisting
- [ ] APIContainerCreateSuite.TestBadParam
- [ ] APIContainerAttachSuite.TestContainerAttachStdin
- [ ] PouchRichContainerSuite.TestRichContainerDumbInitWrongArgs
- [x] PouchExecSuite.TestExecInteractive
- [x] APIImageTagSuite.TestImageTagUsingNoFoundSourceImage
- [ ] APIImageSearchSuite.TestImageSearchOk
- [x] APIImageListSuite.TestImageListFilter
- [x] APIImageDeleteSuite.TestDeleteNonExisting
- [x] APIContainerWaitSuite.TestWaitNonExistingContainer
- [x] APIContainerStopSuite.TestNonExistingContainer
- [x] APIContainerStopSuite.TestInvalidParam
- [x] APIContainerStartSuite.TestNonExistingContainer
- [ ] APIContainerStartSuite.TestInvalidParam
- [x] APIContainerPauseSuite.TestNonExistingContainer
- [x] APIContainerLogsSuite.TestNoSuchContainer
- [x] APIContainerInspectSuite.TestNonExistingContainer
- [x] APIContainerInspectSuite.TestInspectNoSuchContainer
- [ ] APIContainerExecStartSuite.TestContainerExecStartStopped
- [ ] APIContainerExecStartSuite.TestContainerExecStartPaused
- [x] APIContainerExecStartSuite.TestContainerExecStartNotFound
- [ ] APIContainerExecStartSuite.TestContainerExecStartDup
- [x] APIContainerDeleteSuite.TestDeleteNonExisting
- [ ] APIContainerCreateSuite.TestBadParam
- [ ] APIContainerAttachSuite.TestContainerAttachStdin

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sunyuan3** [comment]
Nice catch.

**Comment by allencloud** [comment]
Could you help to check whether all these listed TestSuites have been done? @sunyuan3 @chuanchang 

If we have done one, we can mark one.
