### ISSUE TITLE
[help wanted] add unit and integration test for pouch

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#1607]
### Ⅰ. Issue Description
Currently, the test coverage for pouch is about 40%. We need help to enhance pouch test coverage.

For test coverage of each file, you could find it here: https://codecov.io/gh/alibaba/pouch
Take pouch/ctrd for instance:
1. click the ctrd directory: https://codecov.io/gh/alibaba/pouch/tree/master/ctrd
2. check test coverage for each files, we could focus on files that with test coverage less than 60%.
3. we could click the file, like: https://codecov.io/gh/alibaba/pouch/src/master/ctrd/image_proxy_util.go
4. now you could see which line is not tested.
5. you could choose to add either unit test or integration test to test it.

If you have no idea where  to start, here is a list of functions need unit test:

- [ ] apis/opts/cpu.go:ValidateCPUPeriod

- [ ] apis/opts/cpu.go:ValidateCPUQuota
- [ ] apis/opts/oom_score.go: ValidateOOMScore

- [ ] ctrd/image_proxy_util.go: canonicalAddr

- [ ] ctrd/image_proxy_util.go: hasPort

- [ ]  ctrd/image_proxy_util.go: useProxy

- [ ] daemon/config/config.go:Validate

- [ ] daemon/config/config.go: getConflictConfigurations

- [ ] daemon/config/config.go: getUnknownFlags

- [ ] client/container_list.go: ContainerList

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhuangqh** [comment]
I have split these test cases into individual issue. Close @Letty5411
