### ISSUE TITLE
[help wanted] add unit-tests for VolumeCore

### ISSUE THREAD

**Issue by shaloulcy** [alibaba/pouch#1612]
### Ⅰ. Issue Description

Currently, the Volume Core has no unit-tests, and the volume core has the following interface

* GetVolume
* CreateVolume 
* ListVolumes
* ListVolumeName
* RemoveVolume
* VolumePath
* AttachVolume
* DetachVolume

You can add fake drivers for the unit tests

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhuangqh** [comment]
For the convenience to count the participant of "Bainian Technology" 's job, I will split this issue to 8 part. Each issue correspond to a test case. @shaloulcy
