### ISSUE TITLE
[bug] image not found if an image sha256 updated

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#1618]
### Ⅰ. Issue Description

some application use image sha256 to visit the image, so when the image updated, it will occur `image not found` error.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Any update? Please sync with the community about the status. @HusterWan
