### ISSUE TITLE
Pouch introduction page needs revision for better readability 

### ISSUE THREAD

**Issue by justicezyx** [alibaba/pouch#162]
**Issue Description**
The introduction page needs several minor revisions to better express the project’s definition, objectives, benefits, and technical approach.

**Describe what happened**:
The page has several imprecise descriptions and ambiguous statements regarding the project.

**Describe what you expected to happen**:
An overhaul of the introduction.

**How to reproduce it (as minimally and precisely as possible)**:
Not applicable 

**Anything else we need to know?**:
None

**Environment**:
Not applicable

**Comment by justicezyx** [comment]
I can produce a pull request, could the maintainer assign this issue to me please?

Thanks!

**Comment by allencloud** [comment]
Yes, off course. You can attach a comment `#dibs` to assign yourself to this issue. Because @pouchrobot will detect this and assign that to you. Just have a try and enjoy hacking.

**Comment by allencloud** [comment]
Any update ? 
@justicezyx 
Feel free to tell us if you need any help.

**Comment by justicezyx** [comment]
I will send out a pull request this Saturday. I will not have time to work on this during work days though. Let me know if that's a problem.
