### ISSUE TITLE
[help wanted] add unit-test for ValidateCPUPeriod

### ISSUE THREAD

**Issue by zhuangqh** [alibaba/pouch#1637]
### Ⅰ. Issue Description
Add unit-test for ValidateCPUPeriod method which locate on `apis/opts/cpu.go`.

You can take [env_test.go](https://github.com/alibaba/pouch/blob/master/apis/opts/env_test.go) for reference.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?
please "Baiji" developer refer to this issue in your PR for the convenience for us to count your score.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhuangqh** [comment]
Why is there no `areas/test` label? I think the description of this issue is similar to #1638 
please cc @ZouRui89

**Comment by ZouRui89** [comment]
Checked the logics of add-labels-to-issue part in cute robot...
This situation should not have happened. I think something might have stuck the label event. 😢
