### ISSUE TITLE
[feature request] Consider updating containerd to v1.1.1?

### ISSUE THREAD

**Issue by xiechengsheng** [alibaba/pouch#1713]
### Ⅰ. Issue Description
The newest released containerd version is v1.1.1, which fixes some bugs and brings new features for CRI. Do we need update the pouch's containerd version? 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Yes, we need to update containerd 1.0.3 to container 1.1+, while I think we still need to do lots of update in the ctrd part. 

When we are doing this part, I think we need to improve the encapsulation and interface definition of  ctrd. We have tried in https://github.com/alibaba/pouch/pull/1428 by @HusterWan 

But there is some block there. Could you please help to do some research on this challenging work? And your evaluation could definitely help a lot. @xiechengsheng

**Comment by xiechengsheng** [comment]
ok, I would like to do some research on this.

**Comment by allencloud** [comment]
This has been finished in https://github.com/alibaba/pouch/pull/2725. Closing.
