### ISSUE TITLE
[help wanted] add more unit-test for CRI

### ISSUE THREAD

**Issue by YaoZengzeng** [alibaba/pouch#1756]
### cri/stream/httpstream.go

- [x] IsUpgradeRequest
- [x] negotiateProtocol
- [x] Handshake

### cri/stream/remotecommand/errors.go

- [ ] NewInternalError
- [ ] Status
- [ ] Error

### cri/stream/errors.go

- [x] WriteError

### cri/stream/request_cache.go

- [x] the whole file

### cri/v1alpha1/cri_stream.go

- [x] toCNIPortMappings

### cri/v1alpha1/cri_utils.go

 - [x] generateMountBindings

- [x] modifySandboxNamespaceOptions

- [ ] applySandboxSecurityContext

- [ ] applySandboxLinuxOptions

- [ ] makeSandboxPouchConfig // complete TODO

- [x] toCriSandbox //  complete TODO

- [ ] parseDNSOptions

- [ ] setupSandboxFiles

- [ ] makeContainerName // complete TODO

- [x] modifyContainerNamespaceOptions // complete TODO

- [x] getAppArmorSecurityOpts

- [x] getSELinuxSecurityOpts

- [x] getSeccompSecurityOpts

- [x] modifyHostConfig

- [x] modifyContainerConfig

- [ ] updateCreateConfig

- [x] toCriContainer // compelet TODO

- [x] containerNetns

- [x] imageToCriImage // complete TODO

- [x] getUserFromImageUser // complete TODO

- [x] parseUserFromImageUser // complete TODO

- [ ] getContainerMetrics

- [ ] imageFSPath

- [x] parseWeightDeviceFromCRI

- [x] parseWeightDeviceFromPouch

- [x] parseThrottleDeviceFromCRI

- [x] parseThrottleDeviceFromPouch

- [x] parseUlimitFromCRI

- [x] parseUlimitFromPouch

**Comment by YaoZengzeng** [comment]
@fuweid @Starnop @ZouRui89 Welcome to complete the list and make it more correct :)

**Comment by YaoZengzeng** [comment]
It would be so appreciate that if you would help us finish this target list.

Please declare which case you will finish under this issue to avoid conflict with others.

Thanks! 😄

**Comment by YaoZengzeng** [comment]
I'll finish `cri/stream/request_cache.go` today.

**Comment by ZouRui89** [comment]
If a method exists in both v1alpha1 and v1alpha2, do we write the same test cases or just leave one side blank? @YaoZengzeng

**Comment by ZouRui89** [comment]
```generateMountBindings``` and ```modifySandboxNamespaceOptions``` for me then.

**Comment by Starnop** [comment]
@ZouRui89 I think both of them should have test cases even though the methods are actually the same. And if you find that this method can be extracted as a public method, don't hesitate  to reconstruct it. Thanks :)

**Comment by Starnop** [comment]
I will complete the following tests:
cri/v1alpha1/cri_utils.go
  `applySandboxSecurityContext`
  `applySandboxLinuxOptions`

**Comment by Starnop** [comment]
Today, I will complete the following tests:
cri/v1alpha1/cri_utils.go

 `parseWeightDeviceFromCRI`
 ` parseWeightDeviceFromPouch`
 ` parseThrottleDeviceFromCRI`
  `parseThrottleDeviceFromPouch`
 ` parseUlimitFromCRI`
  `parseUlimitFromPouch`

**Comment by YaoZengzeng** [comment]
Today, I will complete the tests in `cri/stream/errors.go`.

**Comment by Starnop** [comment]
Today, I will complete the following tests:
cri/v1alpha1/cri_utils.go

 `getUserFromImageUser`
  `parseUserFromImageUser`

**Comment by Starnop** [comment]
Today, I will complete the following tests:
cri/v1alpha1/cri_utils.go

`modifyHostConfig`

**Comment by Starnop** [comment]
Today, I will complete the following tests:
cri/v1alpha1/cri_utils.go
 
`modifyHostConfig`
` containerNetns`

**Comment by Starnop** [comment]
Today, I will complete the following tests:
cri/v1alpha1/cri_utils.go
 
`applySandboxSecurityContext`
 `applySandboxLinuxOptions`
`makeSandboxPouchConfig`
