### ISSUE TITLE
[Summary] kernel requirement of all components in Pouch

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#181]
**Issue Description**

We know that Pouch is composed of many different component to provide service. While to make it more clear for users to get a try, I think we should first be clear and summary of kernel requirement of all component in Pouch.

I list all these parts and please fill the content according to your knowing (just edit the issue directly):

## Pouchd @allencloud

The lowesr kernel supported: 
The highest kernel not supported:
The reason why not supported: 

## containerd @Ace-Tang 

The lowesr kernel supported:  **3.10**
The highest kernel not supported:
The reason why not supported: 

## runC @skoo87 

The lowesr kernel supported: 
The highest kernel not supported:
The reason why not supported: 

## runlxc @skoo87 

The lowesr kernel supported: 
The highest kernel not supported:
The reason why not supported: 

## runV @Ace-Tang 

The lowesr kernel supported: 
The highest kernel not supported:
The reason why not supported: 

## clearcontainer @Ace-Tang 

The lowesr kernel supported: 
The highest kernel not supported:
The reason why not supported: 

## lxcfs @CodeJuan 

The lowesr kernel supported:  **2.6.14**
The highest kernel not supported:
The reason why not supported: 

## cri-containerd @YaoZengzeng 

The lowesr kernel supported: 
The highest kernel not supported:
The reason why not supported: 

Thanks a lot.

**Comment by Ace-Tang** [comment]
containerd fails to run on kernel 2.6, and they will declare that they only support kernel >= 3.10
[https://github.com/containerd/containerd/issues/1827](url)

**Comment by CodeJuan** [comment]
lxcfs depends on the kernel module (FUSE), and FUSE was merged into the mainstream Linux kernel tree in kernel version 2.6.14[via WIKI](https://en.wikipedia.org/wiki/Filesystem_in_Userspace).
So lxcfs is compatible with kernel >= 2.6.14
