### ISSUE TITLE
How can I pull an images or Run a container?

### ISSUE THREAD

**Issue by cai980273879** [alibaba/pouch#185]
[root@VM_58_62_centos ~]# pouch pull centos
centos:latest: resolving      |--------------------------------------| 
elapsed: 0.0 s total:   0.0 B (0.0 B/s)                                         
failed to pull image: object required
[root@VM_58_62_centos ~]# 

Because I failed to pull an images.I wandered how can i search for an images such as centos7 or ubuntu.
And the documents about the pouch-cli is null.So can guys help me to figure out this problems?

**Comment by cai980273879** [comment]
I figured out this problem by the https://github.com/alibaba/pouch/issues/123 . Duplicate #123 close it.
Sucessfully pull an images with the registry docker.io.
[root@VM_58_62_centos ~]# pouch pull docker.io/library/hello-world:latest
docker.io/library/hello-world:latest:                                             resolved       |++++++++++++++++++++++++++++++++++++++| 
index-sha256:be0cd392e45be79ffeffa6b05338b98ebb16c87b255f48e297ec7f98e123905c:    done           |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:8072a54ebb3bc136150e2f2860f00a7bf45f13eeb917cca2430fcd0054c8e51b: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:ca4f61b1923c10e9eb81228bd46bee1dfba02b9c7dac1844527a734752688ede:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:f2a91732366c0332ccd7afd2a5c4ff2b9af81f549370f7a19acd460f87686bc7:   done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 9.5 s                                                                    total:  2.0 Ki (214.0 B/s)                                       
[root@VM_58_62_centos ~]# pouch images
IMAGE ID             IMAGE NAME                                               SIZE
be0cd392e45b         docker.io/library/hello-world:latest                     3074
[root@VM_58_62_centos ~]#

**Comment by allencloud** [comment]
Thanks for your feedback. And we will support pulling images without specify registry address. And we will make user have ability to config default registry. 
Please wait a moment for this feature. Thanks again and closing this. @cai980273879
