### ISSUE TITLE
How to Run a container with Pouch ?

### ISSUE THREAD

**Issue by cai980273879** [alibaba/pouch#187]
[root@VM_58_62_centos ~]# pouch images
IMAGE ID             IMAGE NAME                                               SIZE
be0cd392e45b         docker.io/library/hello-world:latest                     3074
f1ca87d9adb6         docker.io/library/nginx:alpine                           434
[root@VM_58_62_centos ~]# pouch create docker.io/library/nginx:alpine
container ID: 546d3d323c442dc637581441449d362c9e4d9afbf373e1e50cbc9385955e98c8, name: 546d3d 
[root@VM_58_62_centos ~]# pouch start 54
Error: failed to start container 54: {"message":"failed to create task, container id: 546d3d323c442dc637581441449d362c9e4d9afbf373e1e50cbc9385955e98c8: OCI runtime create failed: unable to retrieve OCI runtime error (open /var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/546d3d323c442dc637581441449d362c9e4d9afbf373e1e50cbc9385955e98c8/log.json: no such file or directory): exec: \"runc\": executable file not found in $PATH: unknown"}

failed to start container 54: {"message":"failed to create task, container id: 546d3d323c442dc637581441449d362c9e4d9afbf373e1e50cbc9385955e98c8: OCI runtime create failed: unable to retrieve OCI runtime error (open /var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/546d3d323c442dc637581441449d362c9e4d9afbf373e1e50cbc9385955e98c8/log.json: no such file or directory): exec: \"runc\": executable file not found in $PATH: unknown"}

------------------------------------------------------OR----------------------------------------------------------------------------
[root@VM_58_62_centos ~]# pouch images
IMAGE ID             IMAGE NAME                                               SIZE
be0cd392e45b         docker.io/library/hello-world:latest                     3074
f1ca87d9adb6         docker.io/library/nginx:alpine                           434
[root@VM_58_62_centos ~]# pouch start docker.io/library/nginx:alpine   
Error: failed to start container docker.io/library/nginx:alpine: {"message":"failed to get container info with prefix: docker.io/library/nginx:alpine, there are 0 containers"}

failed to start container docker.io/library/nginx:alpine: {"message":"failed to get container info with prefix: docker.io/library/nginx:alpine, there are 0 containers"}

------------------------------------------------------------------------------------------------------------------------------------------
I am a college Student. The Pouch-CLI Document is Wanted ~~ @allencloud @JacksonTian  @zhuzhaoyuan @jlusdy  #130

**Comment by cai980273879** [comment]
HA~HA~ I figure out this problems by add the runc.I made a mistakes by moving the runc to another path.
So i take the runc in correct way that now i can run the container perfectly. 
[root@VM_58_62_centos ~]# pouch ps
Name     ID       Status    Image
546d3d   546d3d   Created   docker.io/library/nginx:alpine
[root@VM_58_62_centos ~]# pouch start 546


Thank you to  @allencloud .
The Documents is imminently wanted.!

**Comment by cai980273879** [comment]
By now I met a problems that I can't exec to my container.

[root@VM_58_62_centos ~]# pouch exec help
Error: requires at least 2 arg(s), only received 1
requires at least 2 arg(s), only received 1
[root@VM_58_62_centos ~]# pouch exec 546 /bin/bash
^C
[root@VM_58_62_centos ~]# pouch exec -it 546 /bin/bash


the Output is null.What the error happened to me?@allencloud .

**Comment by allencloud** [comment]
I would like to cc @skoo87 to take a look at this.

**Comment by skoo87** [comment]
Thanks for your report, when the cmd "/bin/bash" is not found in PATH, there is a error, I will fix it. @cai980273879 ,  In addition, you can try:  pouch exec -ti 546 /bin/sh

**Comment by allencloud** [comment]
Although we can get the point of this issue, while I still recommend that we could follow the [issue template](https://github.com/alibaba/pouch/blob/master/.github/ISSUE_TEMPLATE.md) to track issues. And this will make issue more readable for everyone, not only team members in Pouch, but  also the community. WDYT? @cai980273879  
And feel free to tell us if you need any help. Thanks. 🍻

**Comment by cai980273879** [comment]
Oh！That it～ I made a stupid mistake：There's only 'sh shell' but no 'bash shell'. No wander I can't execute into my shell.！
Thank you for your guys~ @skoo87 @allencloud 
I am Sorry for disturbing you~I will not make a second mistake！Thank you again～

**Comment by cai980273879** [comment]
I wrote a guide about the introduction of 'pouch' in Chinese on http://www.jianshu.com/p/3e4ca915b287.
If you have time,I sincerely hope that you will correct me about the guide.@allencloud
Thank you~
