### ISSUE TITLE
[proposal] support loading docker format image

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#1897]
### Ⅰ. Issue Description
At present, it's incompatible to load docker save image from pouch, perhaps, a --format option can be added into pouch load command, and OCI image is a default, if users set --format docker, and then convert docker image to oci image automatically.

### Ⅱ. Describe what happened
#pouch load -i busybox.tar 
Error: {"message":"failed to import image into containerd by tarstream: no index.json found"}

### Ⅲ. Describe what you expected to happen
Pouch can load docker format image

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. docker pull $image
2. docker save $image -o $image.tar
3. pouch load -i $image.tar

### Ⅴ. Anything else we need to know?
A tool convert docker image to oci image:  https://github.com/coolljt0725/docker2oci
Please reference PR: https://github.com/alibaba/pouch/issues/1163

### Ⅵ. Environment:

- pouch version (use `pouch version`):
$ pouch version
BuildTime:       2018-07-26T11:10:46+08:00
GitCommit:       1.0.0.rc1-53-gb469e1e
GoVersion:       go1.9.4
KernelVersion:   3.10.0-693.2.2.el7.x86_64
Os:              linux
Version:         1.0.0-rc1
APIVersion:      1.24
Arch:            amd64

- OS (e.g. from /etc/os-release):
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
$ uname -a
Linux izj6cfln087djyclspbpngz 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
docker

- Others:

**Comment by allencloud** [comment]
What is the status of this issue? @chuanchang @xiechengsheng @fuweid

**Comment by xiechengsheng** [comment]
In fact moby project is working on this in this [issue](https://github.com/moby/moby/issues/25779) and [Pull Request](https://github.com/moby/moby/pull/33355), seems very large feature in moby...
