### ISSUE TITLE
[bug] failure in pouch save image which is converted by docker2oci

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#1910]
### Ⅰ. Issue Description
Using docker2oci to convert an image from docker save to OCI format then load and save it by pouch, you will get error like this "Error:" when save image again by pouch

### Ⅱ. Describe what happened
as Issue Description

### Ⅲ. Describe what you expected to happen
success to pouch save

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. docker save $image -o $image.tar
2. go get -u github.com/coolljt0725/docker2oci
3. cat d2c.sh
```shell
#!/usr/bin/env bash

set -euo pipefail

# check_docker2oci checks the docker2oci command has been installed.
check_docker2oci() {
  command -v docker2oci > /dev/null || {
    echo >&2 "required docker2oci command, please use 'go get -u github.com/coolljt0725/docker2oci'"
    exit 1
  }
}

# import_image imports images.
import_image() {
  local tarfile name tmpdir tmptar

  tarfile=$1
  name=$2

  # docker image format to oci format in tmpdir
  tmpdir=$(mktemp -d -t 'tmpimagedir.XXXXX')
  docker2oci -i "${tarfile}" "${tmpdir}"

  # make oci tar
  tmptar=$(mktemp -t 'tmpimagetar.XXXXX.tar')
  tar -C "${tmpdir}" -cf "${tmptar}" ./

  # load oci tar
  pouch load -i "${tmptar}" "${name}"
}

main() {
  check_docker2oci
  import_image "$@"
}

main "$@"
```

4. $ bash d2c docker-nginx-test.tar docker-nginx-test
5. $ pouch save d0b08147c874 -o docker-nginx-test.pouch.tar

### Ⅴ. Anything else we need to know?

``` shell
$ pouch images
IMAGE ID       IMAGE NAME                                       SIZE
22c2dd5ee85d   registry.hub.docker.com/library/busybox:latest   720.62 KB

$ go get -u github.com/coolljt0725/docker2oci

$ bash d2c docker-nginx-test.tar docker-nginx-test

$ pouch images
IMAGE ID       IMAGE NAME                                       SIZE
d0b08147c874   docker-nginx-test:latest                         223.36 MB
22c2dd5ee85d   registry.hub.docker.com/library/busybox:latest   720.62 KB

NOTE: the docker-nginx-test.tar is saved by docker

$ pouch images
IMAGE ID       IMAGE NAME                                       SIZE
d0b08147c874   docker-nginx-test:latest                         223.36 MB
22c2dd5ee85d   registry.hub.docker.com/library/busybox:latest   720.62 KB 

$ pouch --debug save d0b08147c874 -o docker-nginx-test.pouch.tar
INFO[0000] start client at debug level                  
Error: 
```

### Ⅵ. Environment:

- pouch version (use `pouch version`):
$ pouch version
GitCommit:       155087c
GoVersion:       go1.9.1
KernelVersion:   3.10.0-327.ali2011.alios7.x86_64
Os:              linux
Version:         0.5.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-07-17T06:53:09+00:00

- OS (e.g. from /etc/os-release):
$ cat /etc/os-release 
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

- Kernel (e.g. `uname -a`):
$ uname -a
Linux r10d11145.sqa.zmf 3.10.0-327.ali2011.alios7.x86_64 #1 SMP Tue Jun 6 14:29:12 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
docker

- Others:

**Comment by fuweid** [comment]
ping @xiechengsheng

**Comment by chuanchang** [comment]
I haven't met this issue after updating local pouch version, please feel free to reopen it if you met it again, thanks.
