### ISSUE TITLE
[bug] CMD "pouch start" can't handle input with space

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#192]
**Issue Description**
pouch CMD can't handle name with space
**Describe what happened**:
```
[root@10.218.145.76 /home/sit/letty/src/github.com/alibaba/pouch]
#pouch create registry.hub.docker.com/library/busybox:latest
container ID: fbb47a61efdd367c6c0d635560fe086923f52a1e5ba4dbd158c8d007407ad60c, name: fbb47a

[root@10.218.145.76 /home/sit/letty/src/github.com/alibaba/pouch]
#pouch start "  fbb47a  "
Error: failed to start container   fbb47a  : failed to get container info with prefix:   fbb47a  , there are 0 containers
failed to start container   fbb47a  : failed to get container info with prefix:   fbb47a  , there are 0 containers

```

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wrfly** [comment]
Hello there, I don't think it is a bug, because you quotes the container ID.

I tested it in docker, and the daemon also told me that he doesn't recognize it:
```bash
➜  ~ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS               NAMES
265ef7fcc874        ca915f68b5ad        "/bin/sh -c 'apk a..."   6 days ago          Exited (1) 6 days ago                       jolly_murdock
➜  ~ 
➜  ~ docker inspect "   265ef7fcc874"
[]
Error: No such object:    265ef7fcc874
➜  ~ 
```

Besides, if you quotes something, that is something:

```bash
➜  ~ echo -n "   123" | wc -c
6
➜  ~ echo -n    123 | wc -c 
3
➜  ~ 
```

In my opinion, if you trim the whitespace I quoted, that is really a bug.

**Comment by allencloud** [comment]
Actually, I am on @wrfly 's side this time.
/cc @Letty5411

**Comment by allencloud** [comment]
If we met problem via this, please reopen this.
