### ISSUE TITLE
CMD "pouch start xxx"  return err "no such device: unknown"

### ISSUE THREAD

**Issue by Deen12520** [alibaba/pouch#205]
**Issue Description**
CMD "pouch start xxx"  doesn't start a container successfully.

**Describe what happened**:

```
[root@VM_centos ~]# pouch images
IMAGE ID             IMAGE NAME                                               SIZE
bbc3a0323522         docker.io/library/busybox:latest                         2699
be0cd392e45b         docker.io/library/hello-world:latest                     3074
34aa80bb22c7         docker.io/library/nginx:alpine                           434

[root@VM_centos ~]# pouch ps
Name     ID       Status    Image
e0737f   e0737f   Created   reg.docker.alibaba-inc.com/base/busybox:latest
b71269   b71269   Created   docker.io/library/busybox:latest
59c33d   59c33d   Created   docker.io/library/hello-world:latest
foo      cd616f   Created   busybox:latest
fbb22c   fbb22c   Created   docker.io/library/nginx:alpine

[root@VM_centos ~]# pouch start b71269
Error: failed to start container b71269: {"message":"failed to create task, container id: b712692c849eb77243f92ff12ec1635ade999c0cc02cc4c937712d1da0f2c1e6: failed to mount rootfs component &{overlay overlay [workdir=/var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/21/work upperdir=/var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/21/fs lowerdir=/var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.overlayfs/snapshots/5/fs]}: **no such device: unknown"**}
```

**Describe what you expected to happen**:
I want to start a container using cmd "pouch start xxx".
**How to reproduce it (as minimally and precisely as possible)**:
1. `pouch start b71269`
2.
3.

**Anything else we need to know?**:
None

**Environment**:
- pouch version (use `pouch version`):
`
APIVersion:      1.24
Arch:            amd64
BuildTime:       2017-12-02T10:11:16.538572572+08:00
GitCommit:       
GoVersion:       go1.9.2
KernelVersion:   
Os:              linux
Version:         0.1.0-dev
`
- OS (e.g. from /etc/os-release):
`
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
`
- Kernel (e.g. `uname -a`):
`
Linux VM_5_157_centos 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools:
- Others:

I have read all issues which other people had proposed,but I don't find the solusion.
Please help me. Thanks a lot :)

**Comment by skoo87** [comment]
maybe a bug in containerd, I will try to reproduce it.  Thanks for report. @Deen12520

**Comment by Deen12520** [comment]
Thanks. I'm looking forward to the solusion.

**Comment by allencloud** [comment]
Can you reproduce this? @skoo87

**Comment by 0x04C2** [comment]
I use vagrant/ubuntu/trusty64 box and meet this issue....no clue about this.😂 @skoo87 @allencloud

**Comment by 0x04C2** [comment]
Hi @Deen12520  @skoo87 @allencloud  , I found one solution.

http://blog.ciplogic.com/index.php/blog/107-docker-with-overlayfs-on-ubuntu-14-04

The overlayfs is available only from kernel version 3.18 and up. I use vagrant/ubuntu/trusty64 box and upgrade from kernel-3.14 to 3.19. the problem has been solved. You can try to upgrade your kernel.

hope it can help. 😄

**Comment by vizv** [comment]
I had the same problem today on my Gentoo, which turns out that I didn't compile my kernel with `CONFIG_OVERLAY_FS` enabled.

So, @Deen12520 Could you verify the kernel module `overlay` is loaded?

Please verify `cat /boot/config-$(uname -r) | grep OVERLAY` outputs `CONFIG_OVERLAY_FS=m`
and `lsmod | grep overlay` also gives output such as `overlay 51863 0`.
If `lsmod` shows `overlay` kernel module is not loaded, you may want to `modprobe overlay` before creating containers.

**Comment by allencloud** [comment]
Hi, Viz. It is really good to see you here. @vizv 

I think this kind of information is really important for our users. Once we confirm this, we need to add this info into document of pouch's. @Letty5411 @sunyuan3 WDYT?

**Comment by Letty5411** [comment]
@allencloud Maybe we could add this kind of issue into FAQ or trouble shooting docs.

**Comment by sunyuan3** [comment]
@allencloud I agree with @Letty5411 .

**Comment by sunyuan3** [comment]
@Deen12520 Which version of centos do you use? Could you please provide iso file link?

**Comment by sunyuan3** [comment]
my log:
```
[root@bogon ~]# pouch create docker.io/library/busybox:latest
container ID: d26c931e16c6d544b395cf95732be353ba4a99663c6648ddbc0704ea50eaff3a, name: d26c93
[root@bogon ~]#
[root@bogon ~]# pouch ps
Name   ID   Status   Created   Image   Runtime
[root@bogon ~]# pouch ps -a
Name     ID       Status    Created          Image                              Runtime
d26c93   d26c93   created   29 seconds ago   docker.io/library/busybox:latest   runc
[root@bogon ~]# pouch start d26c93
[root@bogon ~]# cat /boot/config-$(uname -r) | grep OVERLAY
CONFIG_OVERLAY_FS=m
[root@bogon ~]# lsmod | grep overlay
overlay                51863  1
[root@bogon ~]# uname -a
Linux bogon 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@bogon ~]# pouch version
Os:              linux
Version:         0.1.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-01-29T19:43:04.239706311+08:00
GitCommit:
GoVersion:       go1.9.1
KernelVersion:
```

**Comment by sunyuan3** [comment]
I have 2 questions.
@Deen12520
1. Why is your go version is 1.9.2, not 1.9.1?
2. In your log, "pouch ps" lists created containers. I think it should be "pouch ps -a".

**Comment by sunyuan3** [comment]
Overlay module would be loaded when start a pouch container.
log:
```
[root@bogon ~]# systemctl start pouch
[root@bogon ~]# lsmod | grep overlay
[root@bogon ~]# pouch create docker.io/library/busybox:latest
container ID: 695ba3d2c2a60bb730d50ed6155074c2e6fd6923865fa3bd2f3bf0f6c57b9b3f, name: 695ba3
[root@bogon ~]# lsmod | grep overlay
[root@bogon ~]# pouch start 695ba3d2c2a60bb730d50ed6155074c2e6fd6923865fa3bd2f3bf0f6c57b9b3f
[root@bogon ~]# lsmod | grep overlay
overlay                51863  1
```
