### ISSUE TITLE
bugfix: ContainerManager create haven't deal with error

### ISSUE THREAD

**Issue by rudyfly** [alibaba/pouch#2061]
### Ⅰ. Issue Description
ContainerManager Create haven't deal with error, no set defer to err != nil, such as
succeed to `CreateSnapshot`, but do `generateMountPoints` is error, so just return
and Snapshot is remain. 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiaoxubeii** [comment]
Agree. It seems that `ContainerManager.Create` lacks of resource fallback mechanism to recycle allocated resources when failed.

**Comment by allencloud** [comment]
Could you help to fix this? @xiaoxubeii

**Comment by xiaoxubeii** [comment]
@allencloud OK, i will do that.

**Comment by rudyfly** [comment]
@xiaoxubeii Thank you for your contribution, looking forward to your pr.
