### ISSUE TITLE
[feature request] support statistic api interface

### ISSUE THREAD

**Issue by calmhawk** [alibaba/pouch#2086]
### Ⅰ. Issue Description
Currently no statistic api interface support, in some cases container statistic collection ability is necessary.
We need statistic api interface.

**Comment by allencloud** [comment]
This is similar to https://github.com/alibaba/pouch/issues/637

**Comment by allencloud** [comment]
I will split the work into three parts:

* implement the API in daemon side;
* implement the API in client side;
* since we have the client side, we could add test for stats API.

**Comment by allencloud** [comment]
This has been fixed in https://github.com/alibaba/pouch/pull/2640. Closing now.
