### ISSUE TITLE
pouch pull image "docker.io/library/redis:alpine" error

### ISSUE THREAD

**Issue by zjumoon01** [alibaba/pouch#2095]
### Ⅰ. Issue Description
"pouch pull --help" shows the example of pulling images. As the example, I executed "pouch pull docker.io/library/redis:alpine" .  But returned error.

### Ⅱ. Describe what happened
/# pouch pull docker.io/library/redis:alpine
docker.io/library/redis:alpine:                                                   resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:43e4d14fcffa05a5967c353dd7061564f130d6021725dd219f0c6fcbcc6b5076:    exists         |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:a4b72529acce4055542ea684d2f11484da9fb3b70318a23d6f2eb8a71318bc20: exists         |++++++++++++++++++++++++++++++++++++++|
layer-sha256:3ff30b3bc14850c8bc7d0770ee90622b5f7e95fae87b6b342b2dfb407f1887b8:    exists         |++++++++++++++++++++++++++++++++++++++|
config-sha256:08bef618c30adc2eebe5c590150c7f16f20a0dcec1152171e78a3a028df92545:   exists         |++++++++++++++++++++++++++++++++++++++|
layer-sha256:8e3ba11ec2a2b39ab372c60c16b421536e50e5ce64a0bc81765c2e38381bcff6:    exists         |++++++++++++++++++++++++++++++++++++++|
layer-sha256:1f20bd2a5c234ffab42de6cbf83522946614b21b642a8208dca6b0fd614c31db:    exists         |++++++++++++++++++++++++++++++++++++++|
layer-sha256:782ff7702b5cd0a7c0109740838c74945fc27e4ce34e1028c24bf73f8249a63a:    exists         |++++++++++++++++++++++++++++++++++++++|
layer-sha256:82d1d664c6a7b8305e96d7833492a206c6cbacc86ce5b870114251eebe9da4b5:    exists         |++++++++++++++++++++++++++++++++++++++|
layer-sha256:69f8979cc3105273cbe7e6d13f52c014b1f8061e457d132ae928f8f09701df2e:    exists         |++++++++++++++++++++++++++++++++++++++|
elapsed: 0.2 s
Error: failed to display progress: failed to pull image: failed to extract layer sha256:9f8f870604a08909589f09337944210db2bf72b2a71f0f707642b3aa9d225f9b: rpc error: code = Unknown desc = failed to mount: no such device
### Ⅲ. Describe what you expected to happen
image is pulled successfully.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. pouch pull docker.io/library/redis:alpine
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): 0.5.0
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`):  3.10.0-123.9.3.el7.x86_64
- Install tools:
- Others:
containerd -v :  containerd github.com/containerd/containerd v1.0.3 773c489c9c1b21a6d78b5c538cd395416ec50f88

**Comment by allencloud** [comment]
![image](https://user-images.githubusercontent.com/9465626/44097601-b9c2657e-a010-11e8-9f9b-7aaab2428958.png)

Hi, @zjumoon01 
I am afraid that for CentOS 7 series, kernel 3.10.0-327 is the start version of supporting overlay2. While pouch is relying on containerd which is based on overlay2.

As a result, your kernel is 3.10.0-123 which is under 3.10.0-327, so no support of your kernel.

**Comment by fuweid** [comment]
link to https://github.com/containerd/containerd/issues/1883

**Comment by fuweid** [comment]
it's caused by lower version of kernel. please update the kernel.
