### ISSUE TITLE
[feature request] build pouch push functionality (only cli side not finished now)

### ISSUE THREAD

**Issue by fuweid** [alibaba/pouch#2099]
### Ⅰ. Issue Description

PouchContainer should `push` image to remote registry.

The help info is here.
```
$ pouch push -h

Usage:  pouch push NAME[:TAG]

Push an image or a repository to a registry
```

And the usage is like:

```
$ pouch push localhost:5000/xxx
$ pouch push xx/yy # it will push to defaultRegistry/xx/yy:latest
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ZYecho** [comment]
Hi, I want to know does anyone are working on this issue? @fuweid  If not, maybe I can try to fix it.

**Comment by allencloud** [comment]
I think that @xiechengsheng used to work on it, but met some issues on it. If I could remember, it is some compatible issue between docker registry and local image? 

While could @xiechengsheng give some feedback about this? 
We could check whether to make this move on. @fuweid @ZYecho

**Comment by allencloud** [comment]
push feature is a little bit related with https://github.com/alibaba/pouch/issues/1919. just record the connection of two issues.

**Comment by xiechengsheng** [comment]
Emmm, I did a little bit research on containerd's push functionality. It seems that the present containerd version(`v1.0.3`) that pouch uses doesn't support the `--all-platforms` flag in `ctr` client, which will lead to `ctr push` command error : `unexpected status: 400 Bad Request`, and this bug has been fixed in [newer containerd version](https://github.com/containerd/containerd/pull/2200). So I think we need to upgrade containerd version first...
WDYT? @fuweid

**Comment by allencloud** [comment]
What is new movement in container v1.2.0? Do you know that? 
Actually we are very active on migrating containerd to v1.2.0. @xiechengsheng

**Comment by xiechengsheng** [comment]
For me the changelog seems too big to read 😢 ... But one thing I can ensure is that this `400 Bad Request` bug has been fixed from containerd v1.0.0(https://github.com/containerd/containerd/pull/2200/commits/c3cf3d78229b273c32242c51710a3fb29bc6e45f) ...

**Comment by allencloud** [comment]
cc @cpaasarch

**Comment by fuweid** [comment]
We are missing pouch cli side implementation.
