### ISSUE TITLE
[doc] No "Git Flow" part in CONTRIBUTING.md

### ISSUE THREAD

**Issue by AlertBear** [alibaba/pouch#210]
**Issue Description**
"Git Flow" part was mentioned in the guide, but can not be found.

**Describe what happened**:
Please see step 2 under Workspace Preparation
CLONE your own repository to develop locally. Use git clone https://github.com/<your-username>/pouch.git to clone repository to your local machine. Then you can create new branches to finish the change you wish to make. Branch creation should be read the Git Flow part.

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Yeah, thanks for your report. @AlertBear 
Actually this part is never used, so the `Git Flow` could be removed.
Could you submit a PR to remove this part in the CONTRIBUTING.md?
If you are interested, please feel free to tell us if you have any problem.

**Comment by AlertBear** [comment]
@allencloud , Yes, hornored and very glad to, will submit a PR later.
