### ISSUE TITLE
Pouch bridge network does not work

### ISSUE THREAD

**Issue by Shawnpku** [alibaba/pouch#2101]
### Ⅰ. Issue Description
Pouch bridge network does not work

### Ⅱ. Describe what happened
Can not reach internet in container. Can not reach container using port banding.

### Ⅲ. Describe what you expected to happen
none

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
none

### Ⅴ. Anything else we need to know?
I have tried uninstall docker and delete docker net bridge. Did not work.

### Ⅵ. Environment:

- pouch version (use `pouch version`):1.0.0
- OS (e.g. from /etc/os-release):centos 7
- Kernel (e.g. `uname -a`):3.10.0-327
- Install tools:
- Others:

**Comment by allencloud** [comment]
Could you describe more about what happened in the container:

you can add

* how to create a container
* how to get access to internet

@Shawnpku

**Comment by Shawnpku** [comment]
@allencloud 
Use command `sudo pouch run -it -p 8080:80 nginx /bin/bash` to run container then command `curl localhost:8080` show nothing. Executing `apt update` in container can not connect internet either.

**Comment by Shawnpku** [comment]
I use the same command in docker and it works fine. What command should I use? Also wondering what command should I use to let container be able to reach internet. Thank you~ @allencloud

**Comment by fuweid** [comment]
@Shawnpku how do you install pouchd? by yum or source code? If it's done by yum, it has the issue. you can try it from master branch.

**Comment by Shawnpku** [comment]
@fuweid I install pouch by yum.

**Comment by fuweid** [comment]
@Shawnpku we have fixed this issue by https://github.com/alibaba/pouch/pull/2025, could you mind to install by the source code? 😄

**Comment by Shawnpku** [comment]
Nginx works after I delete /bin/bash part. The command is really different with which I used in docker. I have not been used to it yet.

**Comment by Shawnpku** [comment]
@fuweid Happy to see it has been fixed. Please add the new version to yum resource soon. Thank you~

**Comment by fuweid** [comment]
@Shawnpku thanks! please feel free to close the issue 😄
