### ISSUE TITLE
can't parse image name with underline

### ISSUE THREAD

**Issue by chuanchang** [alibaba/pouch#2113]
### Ⅰ. Issue Description
can't parse image name with underline and got error like this "Error: invalid reference"

### Ⅱ. Describe what happened
as Description

### Ⅲ. Describe what you expected to happen
can parse image name with underline
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. pouch pull registry.hub.docker.com/library/foo_
or
2. pouch pull registry.hub.docker.com/library/foo__bar

### Ⅴ. Anything else we need to know?
$ pouch pull registry.hub.docker.com/library/foo_
Error: invalid reference

$ pouch pull registry.hub.docker.com/library/foo__bar
Error: invalid reference

$ pouch pull registry.hub.docker.com/library/busybox:foo_
Error: invalid reference

$ pouch pull registry.hub.docker.com/library/busybox:foo__bar
Error: invalid reference

### Ⅵ. Environment:

- pouch version (use `pouch version`):
$ pouch version
BuildTime:       2018-08-16T12:48:25+00:00
GitCommit:       33dd176
GoVersion:       go1.9.1
KernelVersion:   3.10.0-327.ali2012.alios7.x86_64
Os:              linux
Version:         1.0.0-rc1
APIVersion:      1.24
Arch:            amd64

- OS (e.g. from /etc/os-release):
$ cat /etc/os-release
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

- Kernel (e.g. `uname -a`):
$ uname -a
Linux e010125004158.bja 3.10.0-327.ali2012.alios7.x86_64 #1 SMP Mon Oct 9 14:09:14 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by fuweid** [comment]
Actually, the `_` is separator so that it can't be the ending of reference.

The link is here. https://github.com/opencontainers/image-spec/blob/fc936c78346d017dcdbc6dd220a8ff60675ce3b5/annotations.md#L31

@chuanchang
