### ISSUE TITLE
[enhancement required] add more library functions in test framework

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#215]
**Issue Description**
Integration test framework should add more library function to make it easy to add tests.

## library Funtions

- [ ] library function
  - [ ] wrapper for commandline:
    - [] RunCmdBareNeu
    - [] RunCmdPos
    - [] RunCmdNeg
    - [] RunCmdOut
  - [ ] debug info in TearDownTest/TearDownSuite

**Comment by allencloud** [comment]
I think RunCmdPos and RunCmdNeg are not so directly readable. What about `RunCmdWithError` and `RunCmdWithNoError`, like Moby does. @Letty5411 @0x04C2

**Comment by 0x04C2** [comment]
@allencloud , agree. I think `WithNoError` should be default. Basically, the command can be run successfully. Only for run in wrong way, we need `RunCmdWithError`.

**Comment by allencloud** [comment]
Any update on this? @Letty5411 What is the progress of this?
If we finished these, maybe we can close it.

**Comment by allencloud** [comment]
Any update on this? If finished, we will close this. @Letty5411

**Comment by Letty5411** [comment]
We could close this PR as now we use icmd lib.
