### ISSUE TITLE
[feature request] Pouchd supports --log-opt flag

### ISSUE THREAD

**Issue by zjumoon01** [alibaba/pouch#2177]
### Ⅰ. Issue Description
I want to constrain container logs as using "--log-opt max-file=" and "--log-opt max-size=" flags in dockerd. However, pouchd doesn't  support "--log-opt" flags. So is there a way of constraining container logs ?
### Ⅱ. Describe what happened
[root@acs-test3 ~]# pouchd --log-opt
Error: unknown flag: --log-opt
ERRO[0000] unknown flag: --log-opt

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): pouchd version: 0.5.0, build: 0.4.0-469-g7f0f998, build at: 2018-06-20T03:04:05+00:00
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fuweid** [comment]
The `--log-opt` is supported by pouchd/pouch cli. However, we just support opt for the `syslog-driver`.
