### ISSUE TITLE
[enhancement request] network management implementation

### ISSUE THREAD

**Issue by YaoZengzeng** [alibaba/pouch#218]
**Issue Description**

we need to polish network management in pouch, in API side, daemon side, client side, doc side and test side. Please record in this issue if some parts are finished.

# network create
- [ ]  network create
   - [x]  API design in swagger: https://github.com/alibaba/pouch/pull/311
   - [x]  daemon side implement: https://github.com/alibaba/pouch/pull/311
   - [x]  client side implement: https://github.com/alibaba/pouch/pull/311
   - [x]  cli implement: https://github.com/alibaba/pouch/pull/311
   - [ ]  test:

# network connect
- [ ]  network connect
   - [ ]  API design in swagger:
   - [ ]  daemon side implement:
   - [ ]  client side implement:
   - [ ]  cli implement:
   - [ ]  test:

# network disconnect
- [ ]  network disconnect
   - [ ]  API design in swagger:
   - [ ]  daemon side implement:
   - [ ]  client side implement:
   - [ ]  cli implement:
   - [ ]  test:

# network inspect
- [ ]  network inspect
   - [x]  API design in swagger: https://github.com/alibaba/pouch/pull/489
   - [x]  daemon side implement: https://github.com/alibaba/pouch/pull/489
   - [x]  client side implement: https://github.com/alibaba/pouch/pull/571
   - [x]  cli implement: https://github.com/alibaba/pouch/pull/571
   - [ ]  test:

# network ls
- [ ]  network ls
   - [x]  API design in swagger:
   - [x]  daemon side implement:
   - [x]  client side implement:
   - [x]  cli implement:
   - [ ]  test:

# network rm
- [ ]  network rm：https://github.com/alibaba/pouch/pull/489
   - [x]  API design in swagger: https://github.com/alibaba/pouch/pull/489
   - [x]  daemon side implement: https://github.com/alibaba/pouch/pull/489
   - [x]  client side implement: https://github.com/alibaba/pouch/pull/560
   - [x]  cli implement: https://github.com/alibaba/pouch/pull/560
   - [x]  test:

**Comment by allencloud** [comment]
Is there any possible to make tc network bandwidth limit support of Alinet in Pouch's network solution? @yyb196

**Comment by yyb196** [comment]
@allencloud yes, Alinet is a plugin implementation of libnetwork(cnm)，if pouch's network management base on libnetwork, Alinet will run on it smoothly.  btw bandwidth limitation in Alinet depends on other artifact which isn't open source, so it only can be used in ali company. 
I will try to support bandwidth limitation in public version of pouch if tc is installed on host running pouchd, and for the sake of making plugins support this function i think it should be implemented in container create or start routine, whose command line arguments should allow users passing in bandwidth limit which pouchd then passes to libnetwork interface `createEndpoint` and when plugins got the limit arguments, some may try to setup limitation to new interface via tc, some may just ignore the arguments in which way most open source libnetwork plugins that already exist implement.

**Comment by allencloud** [comment]
Could you help to finish the rest part of `network inspect` and `network remove`? @ZouRui89

**Comment by allencloud** [comment]
Could you help to finish the rest part of `network ls`? @ZouRui89

**Comment by eryx** [comment]
+1
tc network bandwidth limit support
