### ISSUE TITLE
[proposal] create a container with a given ID

### ISSUE THREAD

**Issue by zjumoon01** [alibaba/pouch#2180]
### Ⅰ. Issue Description
Container ID is generated by pouch automatically. I have a management tool in which container ID is related to other members. When restoring a rich container in fault recover scene，I want to create a container with a given ID (actually the ID is the same as the container which is in fault) . It will be nice that `pouch run` can support a given container ID

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Any update with this issue? @zjumoon01
