### ISSUE TITLE
pouch start runv container failed

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#219]
**Issue Description**

execute cli command: pouch start CONTAINER_ID
no error print when start return, but the container status is still stopped 

**Describe what happened**:

pouch:
```
[root@docker-registry github.com]# pouch start test
[root@docker-registry github.com]#
[root@docker-registry github.com]#
[root@docker-registry github.com]# pouch ps
Name   ID       Status    Image
tt     e5e7d8   Stopped   docker.io/library/nginx:latest
test   7d396b   Stopped   docker.io/library/nginx:latest
```
pouchd:
```
INFO[2017-12-04 20:37:19.193081302] Calling POST /containers/test/start, client @
INFO[2017-12-04 20:37:19.193574781] start to subscribe io, backend: raw-file, id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
INFO[2017-12-04 20:37:19.194413131] success to get image: docker.io/library/nginx:latest, container id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
DEBU[0002] Preparing snapshot                            key=7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e module="containerd/snapshot" parent="sha256:7fcb1f7f8194a8cd7e706d4fc8a0f864cf48bf3937384c4b0a4797af05cc54c6"
DEBU[0002] event published                               module="containerd/snapshot" ns=default topic="/snapshot/prepare" type=containerd.services.events.v1.SnapshotPrepare
DEBU[0002] event published                               module="containerd/containers" ns=default topic="/containers/create" type=containerd.services.events.v1.ContainerCreate
INFO[2017-12-04 20:37:19.216741552] success to new container: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
DEBU[0002] Getting snapshot mounts                       key=7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e module="containerd/snapshot"
INFO[0003] shim containerd-shim started                  address="/containerd-shim/default/7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e/shim.sock" debug=true module="containerd/tasks" pid=15103
DEBU[0000] registering grpc server
DEBU[0000] serving api on unix socket                    socket="[inherited from parent]"
DEBU[0009] event published                               module="containerd/events" ns=default topic="/tasks/create" type=containerd.services.events.v1.TaskCreate
INFO[2017-12-04 20:37:25.773068929] success to new task, container id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e, pid: 15143
DEBU[0009] event published                               module="containerd/events" ns=default topic="/tasks/start" type=containerd.services.events.v1.TaskStart
INFO[2017-12-04 20:37:26.187138843] success to start task, container id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
INFO[2017-12-04 20:37:26.187215221] success to add container, id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
INFO[2017-12-04 20:37:26.189470395] End of Calling POST /containers/test/start, costs 6996 ms. client @
DEBU[0009] event published                               module="containerd/events" ns=default topic="/tasks/exit" type=containerd.services.events.v1.TaskExit
INFO[2017-12-04 20:37:26.212161504] the task has quit, id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e, err: <nil>, exitcode: 255, time: 2017-12-04 12:37:26.21113973 +0000 UTC
DEBU[0010] event published                               module="containerd/events" ns=default topic="/tasks/delete" type=containerd.services.events.v1.TaskDelete
DEBU[0010] received signal                               module=containerd signal=child exited
INFO[0010] shim reaped                                   id=7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e module="containerd/tasks"
DEBU[0010] received signal                               module=containerd signal=child exited
DEBU[0010] Removing snapshot                             key=7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e module="containerd/snapshot"
DEBU[0010] event published                               module="containerd/snapshot" ns=default topic="/snapshot/remove" type=containerd.services.events.v1.SnapshotRemove
DEBU[0010] event published                               module="containerd/containers" ns=default topic="/containers/delete" type=containerd.services.events.v1.ContainerDelete
DEBU[0010] scheduling snapshotter cleanup                module="containerd/containers" snapshotter=overlayfs
DEBU[0010] metadata garbage collected                    d=999.536µs module="containerd/containers"
INFO[2017-12-04 20:37:26.434415634] close containerio backend: raw-file, id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
INFO[2017-12-04 20:37:26.434454240] close containerio backend: raw-file, id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
INFO[2017-12-04 20:37:26.434809256] finished to subscribe io, backend: raw-file, id: 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
DEBU[0010] removed snapshot                              key="default/18/7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e" snapshotter=overlayfs
DEBU[0010] garbage collected                             snapshotter=overlayfs t=1.880668ms
DEBU[0010] received signal                               module=containerd signal=child exited
```
containerd configuration file:
```
[root@docker-registry pouch]# cat /etc/containerd/config.toml
root = "/var/lib/containerd"
state = "/run/containerd"
subreaper = true
oom_score = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0

[debug]
  address = "/run/containerd/debug.sock"
  uid = 0
  gid = 0
  level = "info"

[metrics]
  address = ""

[cgroup]
  path = ""

[plugins.linux]
  shim = "containerd-shim"
  no_shim = false
  runtime = "runv"
  shim_debug = true
```
**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
```
[root@docker-registry pouch]# pouch version
APIVersion:      1.24
Arch:            amd64
BuildTime:       2017-12-04T20:37:16.208366474+08:00
GitCommit:
GoVersion:       go1.9.2
KernelVersion:
Os:              linux
Version:         0.1.0-dev
```
- OS (e.g. from /etc/os-release):
```
[root@docker-registry pouch]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
[root@docker-registry pouch]# uname -r
3.10.0-327.4.5.el7.x86_64
```
- Install tools:
```
[root@docker-registry github.com]# qemu-system-x86_64 --version
QEMU emulator version 2.6.2, Copyright (c) 2003-2008 Fabrice Bellard
```
- Others:

**Comment by HusterWan** [comment]
watch runv execute command:

root     16650  0.3  0.0 350988  8384 pts/8    Sl   19:29   0:00 runv --root /run/containerd/runc/default --log /var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e/log.json --log-format json create --bundle /var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e --pid-file /var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e/init.pid 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e
root     16659  0.8  0.0 350988  8100 ?        Ssl  19:29   0:00 runv --root /run/containerd/runc/default --log_dir /var/log/hyper proxy --vmid vm-JtNRZmQNTe --hyperstart-ctl-sock unix:///var/run/hyper/vm-JtNRZmQNTe/hyper.sock --hyperstart-stream-sock unix:///var/run/hyper/vm-JtNRZmQNTe/tty.sock --proxy-hyperstart /var/run/hyper/vm-JtNRZmQNTe/hyperstartgrpc.sock --watch-vm-console /var/run/hyper/vm-JtNRZmQNTe/console.sock --watch-hyperstart



root     16659  1.2  0.0 352044  8584 ?        Ssl  19:29   0:00 runv --root /run/containerd/runc/default --log_dir /var/log/hyper proxy --vmid vm-JtNRZmQNTe --hyperstart-ctl-sock unix:///var/run/hyper/vm-JtNRZmQNTe/hyper.sock --hyperstart-stream-sock unix:///var/run/hyper/vm-JtNRZmQNTe/tty.sock --proxy-hyperstart /var/run/hyper/vm-JtNRZmQNTe/hyperstartgrpc.sock --watch-vm-console /var/run/hyper/vm-JtNRZmQNTe/console.sock --watch-hyperstart
root     16696  0.0  0.0 137828  5800 ?        Ssl  19:29   0:00 runv --root /run/containerd/runc/default --log_dir /var/log/hyper/shim-7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e shim --container 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e --process init --proxy-stdio --proxy-exit-code --proxy-signal
root     16719  0.0  0.0 417580  6316 pts/8    Sl   19:29   0:00 runv --root /run/containerd/runc/default --log /var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e/log.json --log-format json start 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e



root     16659  1.5  0.0 352044  8584 ?        Ssl  19:29   0:00 runv --root /run/containerd/runc/default --log_dir /var/log/hyper proxy --vmid vm-JtNRZmQNTe --hyperstart-ctl-sock unix:///var/run/hyper/vm-JtNRZmQNTe/hyper.sock --hyperstart-stream-sock unix:///var/run/hyper/vm-JtNRZmQNTe/tty.sock --proxy-hyperstart /var/run/hyper/vm-JtNRZmQNTe/hyperstartgrpc.sock --watch-vm-console /var/run/hyper/vm-JtNRZmQNTe/console.sock --watch-hyperstart
root     16756  0.0  0.0 359984  6308 pts/8    Sl   19:30   0:00 runv --root /run/containerd/runc/default --log /var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e/log.json --log-format json delete 7d396bc56f795c5b2ac3bc2d745189b66966cd85805ffcde9c956381da5bbe6e


maybe the runv container has no entrypoint(not use image entrypoint), so the container exit immediately just after start

**Comment by HusterWan** [comment]
maybe we should give a default spec, like this:
{
	"ociVersion": "1.0.0",
	"process": {
		"terminal": true,
		"user": {
			"uid": 0,
			"gid": 0
		},
		"args": [
			"sh"
		],
		"env": [
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"TERM=xterm"
		],
		"cwd": "/"
	},
	"root": {
		"path": "rootfs",
		"readonly": true
	},
	"hostname": "shell",
	"linux": {
		"resources": {}
	}
}

**Comment by allencloud** [comment]
What image is the container from? Just get more information.

**Comment by HusterWan** [comment]
download from docker hub
```
[root@docker-registry github.com]# pouch images
IMAGE ID             IMAGE NAME                                               SIZE
b81f317384d7         docker.io/library/nginx:latest                           2029
```

**Comment by HusterWan** [comment]
hi @allencloud  any progress ?

**Comment by allencloud** [comment]
https://github.com/alibaba/pouch/issues/202 is related and @Ace-Tang is debugging and fixing this. If you need discussion or have any good idea, please feel free to @ her. 😄 
@HusterWan

**Comment by HusterWan** [comment]
@Ace-Tang i still can not start runv container with pouch,  but i can start runv container with containerd using same docker image. any advice?

**Comment by Ace-Tang** [comment]
@HusterWan ,please try this, [commit](https://github.com/Ace-Tang/containerd/commit/8cdd9cc94946860d412530c6d372afce9cc46175), only way I found can run pouch with runv,
add this in containerd config.json
```
[plugins.linux]
 shim = "containerd-shim"
 no_shim = false
 runtime = "runv"
 runtime_args = ["--root", "/run/runv"]
 shim_debug = true
```
I also have no idea why should change runv root, in my [test code](https://github.com/Ace-Tang/containerd-test/blob/master/run.go), there is no need to do this.

**Comment by HusterWan** [comment]
still not work in my environment,  i think we should not specify root directory, because runv default root is /run/runv
```
   --root value            root directory for storage of container state (this should be located in tmpfs) (default: "/run/runv")
```

**Comment by Ace-Tang** [comment]
containerd will pass a specified  root to runtime,  `/run/runv` is just a default runv root, or can you try this
patch
```
diff --git a/ctrd/container.go b/ctrd/container.go
index 47cc1f7..cab138f 100644
--- a/ctrd/container.go
+++ b/ctrd/container.go
@@ -276,7 +276,8 @@ func (c *Client) createContainer(ctx context.Context, ref, id string, container
                // containerd.WithNewSnapshot(id, img),
                containerd.WithSpec(container.Spec, specOptions...),
                containerd.WithRuntime(fmt.Sprintf("io.containerd.runtime.v1.%s", runtime.GOOS), &runctypes.RuncOptions{
-                       Runtime: config.HostConfig.Runtime,
+                       Runtime:     config.HostConfig.Runtime,
+                       RuntimeRoot: "/run",
                }),
        }
```
and I can got this work in my environment.

**Comment by allencloud** [comment]
Any update on this? Could you try the latest master or Pouch 0.2.0? @HusterWan 
If this has been fixed, please close this. Thanks a lot.

**Comment by Ace-Tang** [comment]
I close this issue since pouch can run with runv, if still get issue, you can reopen it, @HusterWan
