### ISSUE TITLE
No network function on Ubuntu 16.04

### ISSUE THREAD

**Issue by ofrzeta** [alibaba/pouch#2197]
### Ⅰ. Issue Description

I have installed Pouch on two machines with Ubuntu 16.04 from the official repository and couldn't get networking to work. 

### Ⅱ. Describe what happened

When I start a new container with `pouch run -ti ubuntu:18.04` and try to update the Apt repo with` apt update` the hostnames seem to get resolved (apt shows "0% [Connecting to archive.ubuntu.com (91.189.88.152)] ..." but the container can't create a connection. Using Ubuntu 16.04 as a "guest" gives the same result.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?

I had Docker installed on both machines and after I found an issue on the bug tracker about the supposed incompatibility with simultaneously running Pouch (although the issue is just colliding IP address spaces as far as I can see) I purged Docker from the machines and also removed the remaining bridge device "docker0" by hand as well as all iptables chains. 

When I am running a container with Pouch as described above the corresponding device "veth.." gets created and added to the p0 bridge:

```
bridge name	bridge id		STP enabled	interfaces
p0		8000.0242c0a80501	no		veth6796a8d
```

The p0 device configuration looks like this:

```
9: p0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
     link/ether 02:42:c0:a8:05:01 brd ff:ff:ff:ff:ff:ff
     inet 192.168.5.1/24 brd 192.168.5.255 scope global p0
        valid_lft forever preferred_lft forever
     inet6 fe80::42:c0ff:fea8:501/64 scope link 
```

### Ⅵ. Environment:

- pouch version (use `pouch version`): 1.0.0-rc1
- OS (e.g. from /etc/os-release): 16.04.3 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): 4.4.0-134-generic
- Install tools:
- Others:

**Comment by fuweid** [comment]
@ofrzeta this issue has been fixed. Please try update the pouch by apt-get install, like `sudo apt-get install pouch=1.0.0-0~ubuntu`.

**Comment by ofrzeta** [comment]
Awesome, thanks!
