### ISSUE TITLE
[help wanted] questions about stop comand

### ISSUE THREAD

**Issue by ZYecho** [alibaba/pouch#2199]
### Ⅰ. Issue Description
Is there is plan to support more commands that docker support, such as kill/search/port ?

### Ⅱ. Describe what happened
None

### Ⅲ. Describe what you expected to happen
Node

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

None

### Ⅴ. Anything else we need to know?
None

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ZYecho** [comment]
Ping @allencloud, if there's a plan, I'm willing to work on it.

**Comment by fuweid** [comment]
@ZYecho please go ahead. it is our plan 😄 thank you!

**Comment by ZYecho** [comment]
@fuweid Hi, I'm trying to implement kill command, and when I came into the stop command which already implemented and I have some questions, can you explain for me?  thanks.
1. Why the stop command lastly goto delete containers, which  located in destroyContainer func:
```
	if err := pack.container.Delete(ctx); err != nil {
		if !errdefs.IsNotFound(err) {
			return msg, errors.Wrap(err, "failed to delete container")
		}
	}

	logrus.Infof("success to destroy container: %s", id)

	return msg, c.watch.remove(ctx, id)
```
When I look into the logic in [docker,](https://github.com/docker/docker-ce/blob/master/components/engine/daemon/stop.go) I didn't find it.
2. When I look into rm command, it also called delete container, why the delete operation be called twice?

I'm a freshman to golang and pouch, it maybe some misunderstanding, sorry about that.

**Comment by ZYecho** [comment]
add to Question 1, if you physically delete the container, why release the resource same as the rm command?
Question 3
docker rm example said default send SIGKILL signal to containers, but pouch send SIGTERM first, why the difference? 
@fuweid @allencloud  Hope for your reply, Thanks.

**Comment by fuweid** [comment]
@ZYecho we try to stop the container by SIGTERM. it's the normal way to stop program, like `kill pid`. If it fails, you will try to use `kill -9 pid` right, like `SIGKILL`? 

> if you physically delete the container, why release the resource same as the rm command?
the delete container action is to remove the metadata in containerd. but we still have the container configuration in pouchd so that we can restart the stopped container. it's not same thing as rm command. rm command will remove container configuration in the pouchd.
