### ISSUE TITLE
[SoC2019][question] Is there a need for enabling `prune`?

### ISSUE THREAD

**Issue by xiechengsheng** [alibaba/pouch#2213]
### Ⅰ. Issue Description
The command helps delete unused objects in pouch system.
This subcommand can be used in five parts:
- [ ] pouch container prune
- [ ] pouch image prune
- [ ] pouch network prune
- [ ] pouch volume prune
- [ ] pouch system prune

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
In the next weekly meeting, we should talk about this. @alibaba/pouch @fuweid

**Comment by mathspanda** [comment]
Is there anyone working on this. I can help with it.

**Comment by xiechengsheng** [comment]
It seems that command `prune` is useful for CI tests, and the `prune` is completed in [test environment](https://github.com/alibaba/pouch/blob/master/test/environment/cleanup.go#L15), so close this issue :)

**Comment by fuweid** [comment]
@xiechengsheng I think it can be used to clean up, no just for test env. 

@mathspanda please go ahead.

**Comment by mathspanda** [comment]
OK. :-D

**Comment by fuweid** [comment]
@mathspanda you don't need implement all in one PR :) you can separate it into several PRs
