### ISSUE TITLE
how to recognize mysql containter hostname with other pouch container?

### ISSUE THREAD

**Issue by scm20008** [alibaba/pouch#2228]
### Ⅰ. Issue Description
I have 2 docker images from dockerhub.
other pouch container cannot recognize mysql container hostname, so the app cannot connect to mysql.

when I run mysql container, I add flags: --net mynet --hostname mysql

![2018-09-11_124416](https://user-images.githubusercontent.com/639305/45338583-740a9900-b5c0-11e8-97a2-e3dac5d3af09.jpg)

### Ⅱ. Describe what happened
app in the container cannot connect to mysql database.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
Arch:            amd64
BuildTime:       2018-07-13T05:34:59+00:00
GitCommit:       1.0.0.rc1-dirty
GoVersion:       go1.9.1
KernelVersion:   4.4.0-21-generic
Os:              linux
Version:         1.0.0-rc1
APIVersion:      1.24

- OS (e.g. from /etc/os-release):
ubuntu 16.04 LTS

- Kernel (e.g. `uname -a`):
Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by fuweid** [comment]
@scm20008 please try 1.0.0 version because this issue has been solved in https://github.com/alibaba/pouch/pull/2025

**Comment by scm20008** [comment]
@fuweid Thanks! I have upgraded to version 1.0.0.

but pouch cannot start the container mysql:5.6, its image is registry.hub.docker.com/library/mysql:5.6,
and the following is the error:
![mysql_error](https://user-images.githubusercontent.com/639305/45398842-57319c80-b678-11e8-8a6f-9e88b9c959a4.jpg)

**Comment by HusterWan** [comment]
@scm20008 
Maybe you should build a new Image from the ` registry.hub.docker.com/library/mysql:5.6`, do two things:

  * mkdir /var/run/mysqld/
  * chown -R mysql:mysql /var/run/mysqld/

Because the `mysql:5.6` defaut uses the `/var/run/mysqld/` as the service's data work directory.

BTW, pouch now not support `build` command, so you may need use other image building tool like moby.

**Comment by allencloud** [comment]
ping @scm20008 
Could you find a way to solve the problem? If you have any progress, please feel free to contact us. Thanks a lot.
