### ISSUE TITLE
[bug] Could not get the latest pouch packages when start yum update with specific pouch pkg version 

### ISSUE THREAD

**Issue by ireneYang** [alibaba/pouch#2232]
### Ⅰ. Issue Description
Could not yum update pouch package when start yum update with specific pouch pkg version 

### Ⅱ. Describe what happened
When preparing to update pouch from lower version to higher version, eg. from 0.5.2-1.el7.centos to 1.0.0-1.el7.centos, and execute cmd as below:
yum update pouch-1.0.0-1.el7.centos.x86_64 
then update failed and it displays that there is no package "pouch-1.0.0-1.el7.centos.x86_64"

### Ⅲ. Describe what you expected to happen
use `yum update pouch-$version` cmd, I can update pouch successfully from lower version to higher version

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?
when execute yum list|grep pouch, there is the higher version of pouch in the list

### Ⅵ. Environment:

- pouch version (use `pouch version`): from 0.5.2-1.el7.centos to 1.0.0-1.el7.centos
- OS (e.g. from /etc/os-release): centos 7.2
- Kernel (e.g. `uname -a`): 3.10
- Install tools:yum
- Others:

**Comment by allencloud** [comment]
> Yes. We will fix this issue in next release.

Could you help to share more details about the reason? @fuweid

**Comment by fuweid** [comment]
@allencloud there is some issue in the package build in the repo. we should move the script from the pouch to pouchcontainer group so that we change our build script without changing gitcommit.

**Comment by allencloud** [comment]
Any update with this issue? I think we are going to release the next version in few days. @fuweid

**Comment by fuweid** [comment]
yes. but something like IO issue is more important than that. 
We needs to move the release tool out of repo and make the script right.  
For this requirement, I would like to add the `help-wanted`. How do you think?

**Comment by fuweid** [comment]
sure. will file issue.
