### ISSUE TITLE
[feature request] CI need some like '/retest' or '/test' command to trigger the test process

### ISSUE THREAD

**Issue by xiaoxubeii** [alibaba/pouch#2249]
### Ⅰ. Issue Description
Sometimes the ci failed to some reason that are not caused by the code, and there is no way to trigger the ci test process manually.

### Ⅲ. Describe what you expected to happen
To trigger the ci test process by some commands, maybe '/retest'.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Starnop** [comment]
Maybe sign in `travis-ci.org` with your account of github will help you. ^_^

**Comment by xiaoxubeii** [comment]
> Maybe sign in `travis-ci.org` with your account of github will help you. ^_^

But I think the normal contributor have no permission to trigger the build in travis-ci.org.

**Comment by allencloud** [comment]
I will close this since I think it is another tool's work to make it work. @xiaoxubeii
