### ISSUE TITLE
[feature request] using etcd store pouch configs

### ISSUE THREAD

**Issue by knightXun** [alibaba/pouch#2251]
Disk corruption make damages to docker,for examples docker containers configuration,images configuration.Pouch will meet this problem too. maybe we can store some part of configuration into etcd. That will make pouch more stable.

**Comment by fengzixu** [comment]
Is this feature has been considered to implement? If I want to handle it, which steps I should follow? (Eg: tech design doc, open an issue to discuss it) @fuweid @allencloud

**Comment by allencloud** [comment]
> Is this feature has been considered to implement?

To be honest, current this feature is not so urgent for us. However in the future, this is definitely a very useful feature. We need to implement this.

> which steps I should follow? 

A design doc is essential. Yeah, open an issue. When we finish the design review, I think pull request could follow up to cover it.

@fengzixu

**Comment by knightXun** [comment]
@allencloud I will offer my helps to implement this feature if i have time. For this design doc, please let me know.
