### ISSUE TITLE
[bug] Can't get pid from container which was stopped 

### ISSUE THREAD

**Issue by changyaowei** [alibaba/pouch#2255]
### Ⅰ. Issue Description

When a pouch container is stopped,  we can't get pid by ```pouch inspect ```.
By the way, in CRI module, when we build  network namespace, we should judge pid with 0 not -1

### Ⅱ. Describe what happened
![image](https://user-images.githubusercontent.com/12136478/45745464-7a89b800-bc33-11e8-9a79-b44bccb9bcfe.png)

![image](https://user-images.githubusercontent.com/12136478/45746060-e882af00-bc34-11e8-9cdf-9a8b1491dba4.png)

### Ⅲ. Describe what you expected to happen
We can get pid through ```pouch inspect ``` cmd , even it was stopped

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
![image](https://user-images.githubusercontent.com/12136478/45745509-92613c00-bc33-11e8-8191-95f647eeefbe.png)

**Comment by fuweid** [comment]
@Starnop could we update the CRI part?
