### ISSUE TITLE
[bug] logging options doesn't have a valid check

### ISSUE THREAD

**Issue by zjumoon01** [alibaba/pouch#2276]
### Ⅰ. Issue Description
Pouch does not check the logging options key, that results pouchd can start with useless options

### Ⅱ. Describe what happened
1. start pouchd with any useless logging options:
\# /usr/local/bin/pouchd --log-opt max-size=10m --log-opt max-file=2 **--log-opt key=value**
2. pouchd start successfully without error. 

### Ⅲ. Describe what you expected to happen
We need valid check for logging option. Invalid keys should be refused.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): 1.0.0
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I think this is solved in https://github.com/alibaba/pouch/pull/2306. Please take a look. @zjumoon01 

And I we plan to release this in v1.0.1, right? @fuweid for double check.
