### ISSUE TITLE
[bug] Can't start container but can be inspected

### ISSUE THREAD

**Issue by luhaixun** [alibaba/pouch#233]
**Issue Description**
Can't start container although it can be created.

**Describe what happened**:
The new created container can't be started.

**Describe what you expected to happen**:
I want this container can be started successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Download image with "pouch pull index.docker.io/chef/chef:latest"
2. Create a container without specifying "latest" tag, eg: "pouch create --name chef index.docker.io/chef/chef"
2. Run "pouch ps" can see the container is created successfully and "pouch inspect" can see more details.

```
root@mo-e44a08205:~# pouch ps
Name     ID       Status    Image
chef     98ad7c   Created   index.docker.io/chef/chef

root@mo-e44a08205:~# pouch inspect chef
{
  "Id": "98ad7cbf2e4a3953d428169335b331688079b8420a75c3437a577a549e9c3d06",
  "Created": "0001-01-01 00:00:00",
  "Path": "",
  "Args": null,
  "State": {
    "StartedAt": "0001-01-01T00:00:00Z",
    "Status": 0,
    "FinishedAt": "0001-01-01T00:00:00Z",
    "Pid": 0,
    "ExitCode": 0,
    "Error": ""
  },
  "Image": "index.docker.io/chef/chef",
  "ResolvConfPath": "",
  "HostnamePath": "",
  "HostsPath": "",
  "LogPath": "",
  "Name": "chef",
  "RestartCount": 0,
  "Driver": "",
  "MountLabel": "",
  "ProcessLabel": "",
  "AppArmorProfile": "",
  "ExecIDs": null,
  "HostConfig": null,
  "HostRootPath": ""
}
```
4. "pouch start" failed with below error:
```
   root@mo-e44a08205:~# pouch start chef
   Error: failed to start container chef: {"message":"Image not found"}
```

**Anything else we need to know?**:
Root cause: If I didn't specify "latest" tag when creating container, although the container can be created successfully but failed to start, this is not user friendly as I shipping from "Docker". 
HOW-TO-FIX: Please consider fix it with verifying if the image exists and append the latest tag if the container is created without any default tag.

**Environment**:
- pouch version (use `pouch version`):0.1.0-dev
- OS (e.g. from /etc/os-release):Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`):Linux mo-e44a08205 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: pouch
- Others: N/A

**Comment by allencloud** [comment]
Yes, you are totally right. You created container with image `chef index.docker.io/chef/chef` without tag `latest`. However, when starting container, pouchd will search image at first. 

It is a bug of pouch currently. Thanks for your feedback. @luhaixun 

I think we should use the complete name of image all the time from the first time into Pouchd. While it could provide loose rule for users.

**Comment by luhaixun** [comment]
Thanks God it's a bug rather than by-design. :)

Thanks for your quick response, appreciate!

Thanks,
Tim

**Comment by allencloud** [comment]
Could you help fix this? @0x04C2 
From my point of view, we can use pkg reference to fix this, like https://github.com/alibaba/pouch/pull/333.
WDYT

**Comment by 0x04C2** [comment]
@allencloud , Sure. I will do that. :)
