### ISSUE TITLE
[feature request] Intend to provide pouch with a visual installation/management tool

### ISSUE THREAD

**Issue by Liberxue** [alibaba/pouch#2341]
### I. Issue Description
Intend to provide pouch with a visual installation/management tool
### II. Describe what you expected to happen
Solve installation management resource issues

### III.Support operating system
Mac
Ubuntu
Windows

### Ⅳ.Development language
C/C++/Golang +JavaScript

### Ⅴ.rely
[Webview](https://github.com/zserge/webview) + [Moon](https://github.com/kbrsh/moon)

### 👏
How do you feel about it, or what ideas and suggestions are there, welcome to discuss and collide?

**Comment by allencloud** [comment]
I have one question for this. @Liberxue 

Linux System is a little bit different from other system. Since PouchContainer only works on Linux, for other systems we need to start up a minor virtual machine for PouchContainer, just like boot2docker or something else.

**Comment by Liberxue** [comment]
@allencloud 

Ok👌. I understand this, 

I’m going to provide the function. Let’s discuss it together.

### Main interface
> * Dashboard (plugin, image market function, resource monitoring, etc.)
> * Network (created network list and network related management, etc.)
> * Data volume (created data volume list and data volume management, etc.)
> * Image (created mirror list and image management, etc.)
> * Container (running container list and container management, etc.)
> * Settings (pouch settings configuration information)
![image](https://user-images.githubusercontent.com/5831248/47613043-4e7b1580-dac2-11e8-8313-11a43d2ea329.png)
![image](https://user-images.githubusercontent.com/5831248/47613161-6a7fb680-dac4-11e8-8853-e43256519599.png)
