### ISSUE TITLE
can not upgrade pouch to 1.0.0 in CentOS

### ISSUE THREAD

**Issue by eryx** [alibaba/pouch#2357]
### Ⅰ. Issue Description

file list in centos repo:
``` shell
#  https://mirrors.aliyun.com/pouch/linux/centos/7/x86_64/stable/package/
pouch-1.0.0-1.el7.centos.x86_64.rpm                31-Aug-2018 14:37            44843610
pouch-1.0.0.rc1-1.el7.centos.x86_64.rpm            13-Jul-2018 04:11            43205048
pouch-1.0.0_rc2-1.el7.centos.x86_64.rpm            23-Aug-2018 06:44            44815771
```
in centos, the version 1.0.0_rc2 is newer than 1.0.0 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fuweid** [comment]
relate to https://github.com/alibaba/pouch/issues/2232. Sorry for that.

**Comment by purplegrape** [comment]
it's due to wrong rpm spec tag .

another rpm package you may want : https://github.com/purplegrape/pouch-rpm
