### ISSUE TITLE
[bug] pouch pull images with wrong tag return 0

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#237]
**Issue Description**

**Describe what happened**:
pull images with wrong tag, return 0
```
#pouch pull registry.hub.docker.com/library/busybox:xxxx
registry.hub.docker.com/library/busybox:xxxx: resolving      |--------------------------------------|
elapsed: 1.6 s                                total:   0.0 B (0.0 B/s)
failed to pull image: registry.hub.docker.com/library/busybox:xxxx not found

#echo $?
0
```

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HusterWan** [comment]
Yes, i just print error information, and return nil.  i should return error  information when  error occurred.  i will fix this problem soon, thanks @Letty5411
