### ISSUE TITLE
[question] Is there a need to support pouch images filter and no-trunc flag?

### ISSUE THREAD

**Issue by ZYecho** [alibaba/pouch#2371]
### Ⅰ. Issue Description
As the title desc.

### Ⅱ. Describe what happened
None.

### Ⅲ. Describe what you expected to happen
None.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?
None.

### Ⅵ. Environment:
None.

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- `Others:```

**Comment by allencloud** [comment]
Yes, I think so. It is a very helpful feature for cli end-users.

**Comment by ZYecho** [comment]
> Yes, I think so. It is a very helpful feature for cli end-users.

I plan to work on it, thanks.

**Comment by ZYecho** [comment]
@fuweid Why close it? still leave a flag `filter` to implement.

**Comment by fuweid** [comment]
Oops. The pr linked to this issue. When I merge the pr, this issue will be closed. Reopen it.
