### ISSUE TITLE
[feature request] pouch command flags can support --publish

### ISSUE THREAD

**Issue by hkebao** [alibaba/pouch#2377]
### Ⅰ. Issue Description
In docker command flags use --publish to expose services for the container.but in pouch the flags is --port. why cannt follow the open source rules? so I suggest pouch can support the same flags--publish.

### Ⅱ. Describe what happened
pouch run --publish  
Error: unknown flag: --publish

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
fixed in https://github.com/alibaba/pouch/pull/2478
