### ISSUE TITLE
doc incomplete: CriEnabled field  in the document is differen from that in the pouch info

### ISSUE THREAD

**Issue by hellolijj** [alibaba/pouch#2381]
### Ⅰ. Issue Description
when i develop pouch with kubernetes following [document](https://github.com/alibaba/pouch/blob/master/docs/kubernetes/pouch_with_kubernetes_deploying.md), `CriEnabled` field  in the document is differen from that in the pouch info. `CriEnabled` is in document, but `IsCriEnable` is in document.

### Ⅱ. Describe what happened
see above

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. use command  pouch info
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): 1.0.0-rc2
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools:
- Others:

**Comment by Starnop** [comment]
Could you please help fix it? :)

**Comment by hellolijj** [comment]
ok
