### ISSUE TITLE
`pouch inspect` info of NetworkSettings is incomplete

### ISSUE THREAD

**Issue by YvesChan** [alibaba/pouch#2386]
### Ⅰ. Issue Description
The output of pouch inspect does NOT contain the Ports info in NetworkSettings Section, unlike what *docker-ce* does.

### Ⅱ. Describe what happened
* run `pouch run -dt -p 8080:80 nginx`
* then `pouch inspect xxxx`
* there's no Ports in NetworkSettings

### Ⅲ. Describe what you expected to happen
using docker-ce instead. Here's what we got from `docker inspect`
```
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "85d090d927a763f61763ae0f69fd7f5c5985aebdac638f72e8ddb4186724058c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "20008"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/85d090d927a7",
...
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. pouch run -dt -p 8080:80 nginx
2. pouch inspect xxxx
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): 1.0.0-585-g19dfa08-dirty
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 4.9
- Install tools:
- Others:

**Comment by xiaoxubeii** [comment]
Indeed, working on it.
