### ISSUE TITLE
`kubeadm reset` support kill relative pods to release occupied port

### ISSUE THREAD

**Issue by hellolijj** [alibaba/pouch#2389]
## Why you need it?

When I deployed k8s + pouch with `kubeadm`, command `kubeadm reset` didn't kill relative pod, causing the port 6443、10250、10251、10252 to be occupied. But k8s + docker support that.

## How it could be?

Command `kubeadm reset` should kill relative pod, releasing occupied port.

## Other related information

kubeadm version: 1.11.2
k8s version: 1.11.2
pouch version: 1.0.0-rc2

**Comment by hellolijj** [comment]
maybe i could fix it

**Comment by allencloud** [comment]
Thanks @hellolijj for your thought.
Just do it and feel free to tell us if you need any help.

**Comment by allencloud** [comment]
Any update on this? @hellolijj

**Comment by hellolijj** [comment]
i am afried i can not fix it. maybe i need my senior's help @Starnop and a few more days...

**Comment by hellolijj** [comment]
Here is the what i try about this issue:
- The first time i encounterd this problem this, i use `kubeadm reset`. It doesn't clean pods, because i didn't take param `--cri-socket `
- Laterly, i still encounterd this problem even if i take the param `--cri-socket /var/run/pouchcri.sock`. the reson is the kubelet was stopped at first. so if you install crictl, this problem will be avoided. here are reason:
   
   ---
  my kubeadm version is v1.11.2, the sequence of `kubeadm reset --cri-socket /var/run/pouchcri.sock` is: 
    1.  stop kubelet service 
    2.  excuce  `docker ps -a --filter name=k8s_ -q | xargs -r docker rm --force --volumes` or excuse` crictlPath "-r", criSocketPath, "pods", "--quiet"`  here is [source code v1.11](https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kubeadm/app/cmd/reset.go#210))
    3.  delete related configuration file

- But in the latest k8s code, someone say [kubeadm will detect CRIs automatically ](https://github.com/kubernetes/kubernetes/pull/69366) . this bug will be fixed up in the next k8s version. 

- At last, i  will continue to focus on this problem in the latest k8s version

**Comment by Starnop** [comment]
In fact , it's has been supported by `pouch-container` , however , you should exec the command about `reset` with 
```
kubeadm reset --ignore-preflight-errors=all --cri-socket=unix:///var/run/pouchcri.sock
```
There is one thing you should pay attention to in this command, you should use `unix:///var/run/pouchcri.sock` as the value of cri-socket ,not `/var/run/pouchcri.sock`.

If you do that, you will get errors as follows:
```
[reset] failed to stop the running containers using crictl: exit status 1. Trying to use docker instead
```
you can exec the command to have a try:
```
# kubeadm reset --ignore-preflight-errors=all --cri-socket=/var/run/pouchcri.sock
[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] are you sure you want to proceed? [y/N]: y
[preflight] running pre-flight checks
[reset] stopping the kubelet service
[reset] unmounting mounted directories in "/var/lib/kubelet"
[reset] removing kubernetes-managed containers
[reset] cleaning up running containers using crictl with socket /var/run/pouchcri.sock
[reset] failed to stop the running containers using crictl: exit status 1. Trying to use docker instead[reset] no etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml". Assuming external etcd
[reset] deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]
[reset] deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
```

================================================================
The reason for the above error is that `crictl` suggest you consider using full url format like `"unix:///var/run/pouchcri.sock"`. If not , it will print a log as follows :
```
# crictl -r /var/run/pouchcri.sock pods --quiet
W1127 07:15:40.953035   14655 util_unix.go:75] Using "/var/run/pouchcri.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/pouchcri.sock".
```
and then, you will find that [the source code of kubelet](https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kubeadm/app/cmd/reset.go#L218) rely on the the output of `crictl`. And you will get `sandboxes` like this :
```
[W1127 07:25:24.469014 16012 util_unix.go:75] Using "/var/run/pouchcri.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/pouchcri.sock". f4d98c8c01ebdbc33a533d28a9cc5a22b7af10a75c6692c7f97910c8b412d0d3 a10739891920918b5a776c92328a6ab5123277b11745d9f6e358ca216a2b8ff7 73c19d589aa5be0ce0258b72e4d5b503167f26071d212cc0ce6909008431783f 1be07b789305af8dc27d38d5fc79de29100e8e3e2c6d80d00947262d8e1f1353 6a073e4013aeb7dccf895a094ab70791c45ced08193f0eb1dff45c78576dd5d1]
```
And then you will find the log as follows:
```
[reset] Executing command /usr/bin/crictl -r /var/run/pouchcri.sock stopp W1127
```

By now,  you should know why the `kubeadm reset` doesn't kill the pods.

===========================================================
Through this process of finding the problem, we find that something unreasonable:
kubeadm init expect an absolute path as the value of  `cri-socket` like `/var/run/pouchcri.sock` ,and you will get errors as follows when you use `unix:///var/run/pouchcri.sock`
```
# kubeadm init --ignore-preflight-errors=all --cri-socket=unix:///var/run/pouchcri.sock
nodeRegistration.criSocket: Invalid value: "unix:///var/run/pouchcri.sock": path is not absolute
```
and `kubeadm reset` expect `unix:///var/run/pouchcri.sock` as mentioned above.

In fact, to conclude, `kubeadm reset` relies heavily on the output of `crictl` when the cri runtime is not `dockershim`.

=============================================================
@hellolijj Maybe you can take an issue to kubernetes/kubeadm . By the way, there is another thing you should notice that `kubeadm reset` will not delete the downloaded images, you can also mention it and learn it further.
