### ISSUE TITLE
[feature request] support API extensions and hook

### ISSUE THREAD

**Issue by zhuangqh** [alibaba/pouch#2406]
## Why you need it?

There are many usage scenarios of PouchContainer. I propose **strengthening the customization ability** of PouchContainer to cover these scenarios. What's more, developers could **keep pace with upstream PouchContainer without pain**.

I propose adding a API plugin, which enable to extend PouchContainer's HTTP API and hook the API handler.

## How it could be?

**API extension**
Provide the router to API plugin, allow developers to register their custom API.

**API hook** (like middleware)
Provide the ability for developers to do something above or after all of the request.

**Comment by allencloud** [comment]
#dibs
