### ISSUE TITLE
[bug] We cannot see any metrics about gRPC which used in cri package  

### ISSUE THREAD

**Issue by fengzixu** [alibaba/pouch#2414]
### Ⅰ. Issue Description

When I resolved this issue #2395 , I revised the logic about metrics in cri package. I found that GRPCMetrics(https://github.com/alibaba/pouch/blob/master/cri/metrics/metrics.go#L23) was used in  https://github.com/alibaba/pouch/blob/1f7dbf60d406210c65fb96ea4682f6d04f97773e/cri/v1alpha2/service/cri.go#L21 . But, the GRPCMetrics wasn't registered to defaultPrometheusRegistry or customPrometheusRegistry.

### Ⅱ. Describe what happened

1. GRPCMetrics wasn't registered
2. Not found any metric about gRPC

### Ⅲ. Describe what you expected to happen

We should register GRPCMetrics to registry about Prometheus. After that, we can see the metrics through curl http://xxx/metrics

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

If someone can help me to identify this bug, I will revise it together with #2395.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Starnop** [comment]
At present, `GRPCMetrics` is not necessary actually, so delete it firstly. Sorry for forgot to add a `TODO` tag. Maybe you can help add it or make it registered. THX.

**Comment by fengzixu** [comment]
@Starnop OK. I will delete it.
