### ISSUE TITLE
Does pouch support docker-compose? 

### ISSUE THREAD

**Issue by marryton007** [alibaba/pouch#2456]
## Question
Please see the subject. I think that pouch maybe could instead of docker in some scenes. Does it support docker-compose or has an alike solution? thanks very much.

**Comment by HusterWan** [comment]
@marryton007 Actually, we have not investigated if pouch supports docker-compose, and I think it also not our core works.

But, I encourage you to describe what scenario that you want to use the docker-compose?  and does the k8s can meet your demand?

**Comment by marryton007** [comment]
Thanks, My means is looking for a simple solution to run a few of containers that have a relationship.  I think k8s is too heavy for me.

**Comment by allencloud** [comment]
> I think k8s is too heavy for me.

Totally agree. Actually Pouch's API is compatible with Docker's API. Then the API side is totally OK, I think. While for the the socket address part, whether docker-compose allows user to configure, we need to keep dig in. @marryton007
