### ISSUE TITLE
[docs] dead links exist in markdown documentation

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#2466]
### Ⅰ. Issue Description

We have enabled markdown-link-check in this repo. And the result shows that the following docs have dead links:

```
FILE: ./docs/kubernetes/pouch_with_cri_introduction.md
[✖] https://git.k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto

ERROR: dead links found!

FILE: ./docs/features/pouch_with_dragonfly.md
[✖] https://github.com/alibaba/Dragonfly/blob/master/docs/install_server.md
[✖] https://github.com/alibaba/Dragonfly/blob/master/docs/install_client.md
[✖] https://github.com/alibaba/Dragonfly/blob/master/docs/usage.md

ERROR: dead links found!

FILE: ./apis/README.md
[✖] ../docs/api/api.md

ERROR: dead links found!

FILE: ./storage/volume/README.md
[✖] ../docs/static_files/pouch_volume_architecture.png
[✖] volume/examples/demo/demo.go
[✖] docs/commandline/pouch_volume.md
```

This is also recorded in https://github.com/alibaba/pouch/pull/2465

### Ⅱ. Describe what happened
dead links exist in markdown files.

### Ⅲ. Describe what you expected to happen
no dead links exist in markdown files.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

none

### Ⅴ. Anything else we need to know?
none

### Ⅵ. Environment:

master code.

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
cc @rudyfly @Ace-Tang 
Please take a look at the dragonfly part and volume part. Thanks a lot.

**Comment by allencloud** [comment]
Could you help to handle the CRI part:? @Starnop 
```
FILE: ./docs/kubernetes/pouch_with_cri_introduction.md
[✖] https://git.k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto
```

And you to help handle the following part? @rudyfly 

```
FILE: ./storage/volume/README.md
[✖] ../docs/static_files/pouch_volume_architecture.png
[✖] volume/examples/demo/demo.go
[✖] docs/commandline/pouch_volume.md
```

**Comment by Starnop** [comment]
Of course, I will do that ASAP. ^_^

**Comment by allencloud** [comment]
fixed in https://github.com/alibaba/pouch/pull/2465
