### ISSUE TITLE
PouchContainer not support diskquota that kernel version < 4.5

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#2487]
## Why you need it?

Since PouchContainer's diskquota feature is dependent on the kernel, and only kernel version >=4.5 can support project quota, so how can we support diskquota on the kernels that below to 4.5

 **Notes**: In alibaba, we use group quota of kernel to support diskquota feature.

**Comment by allencloud** [comment]
How about support XFS on centos 7.x series?
Then diskquota feature on XFS seems working.
