### ISSUE TITLE
[feature request] remove SerialNumber getting function and make it general

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#2489]
## Why you need it?

The function `GetSerialNumber` is not general, it is a little bit coupled with alibaba's system, see  https://github.com/alibaba/pouch/blob/master/pkg/system/system.go#L88  

``` golang
// GetSerialNumber gets serial number or a machine.
func GetSerialNumber() string {
	var sn string
	if b, e := exec.Command("dmidecode", "-s", "system-serial-number").CombinedOutput(); e == nil {
		scanner := bufio.NewScanner(bytes.NewReader(b))
		for scanner.Scan() {
			sn = scanner.Text()
		}
	}
	if len(strings.Fields(sn)) != 0 {
		sn = strings.Fields(sn)[0]
	}
	for i := 0; i < 10; i++ {
		if _, ex := os.Stat("/usr/alisys/dragoon/libexec/armory/bin/armoryinfo"); ex == nil {
			if b, e := exec.Command("/usr/alisys/dragoon/libexec/armory/bin/armoryinfo", "sn").CombinedOutput(); e == nil {
				sn = strings.TrimSpace(string(b))
			}
		}
		if sn != "" {
			break
		}
		time.Sleep(100 * time.Millisecond)
	}
	return sn
}
```

Since it is not general, I think we should remove the implementation part of `alisys`.

## How it could be?

Use a general way to make it. Or encapsulate it into pouchd's daemon plugin.

## Other related information

none

**Comment by Ace-Tang** [comment]
Remove the `/usr/alisys/dragoon/libexec/armory/bin/armoryinfo` part, use other method instead

**Comment by houstar** [comment]
either dmidecode or systemd-uuid might be useful for this case.

**Comment by allencloud** [comment]
> either dmidecode or systemd-uuid might be useful for this case. 

Could you be more specific? @houstar
