### ISSUE TITLE
how can I run pouch with command like "echo 1"

### ISSUE THREAD

**Issue by Ace-Tang** [alibaba/pouch#249]
can we start container with such command like
```
$ sudo ctr run docker.io/library/busybox:latest runv112  echo 1
1
```
since I found no entry to add cmd with pouch start or pouch create, so I simplely hack in code
```
--- a/ctrd/container.go
+++ b/ctrd/container.go
@@ -252,6 +252,8 @@ func (c *Client) createContainer(ctx context.Context, ref, id string, container
                containerd.WithImageConfig(img),
                containerd.WithRootFSPath("rootfs"),
        }
+
+       container.Spec.Process.Args = []string{"echo", "1"}
        if args := container.Spec.Process.Args; len(args) != 0 {
                specOptions = append(specOptions, containerd.WithProcessArgs(args...))
        }
```

but start container not get result as I expect
```
ace@www:~/go/src/github.com/alibaba/pouch time-> 四 12月 07 10:50:21
$ sudo ./pouch start 8f9517
```

am I something wrong

**Comment by skoo87** [comment]
./pouch create registry.hub.docker.com/library/busybox:latest 
./pouch start 12345 "/bin/echo 1"

**Comment by allencloud** [comment]
I think we should support the way without " quoted commands.

just like `pouch run image:tag commandA ArgB ArgC`. But currently we must execute `pouch run image:tag "commandA ArgB ArgC"`, right? @skoo87
