### ISSUE TITLE
[feature request] more checker type are needed

### ISSUE THREAD

**Issue by ZYecho** [alibaba/pouch#2497]
## Why you need it?

the go-check now only support the following checker:
```
DeepEquals   = check.DeepEquals
ErrorMatches = check.ErrorMatches
FitsTypeOf   = check.FitsTypeOf
HasLen       = check.HasLen
Implements   = check.Implements
IsNil        = check.IsNil
Matches      = check.Matches
Not          = check.Not
NotNil       = check.NotNil
PanicMatches = check.PanicMatches
Panics       = check.Panics 
```
IMO, it's not enough, lack of many useful checker such as `strings.Containes` or `HasPrefix`.

## How it could be?

Add more checker type.

## Other related information

None.

**Comment by allencloud** [comment]
> IMO, it's not enough, lack of many useful checker such as strings.Containes or HasPrefix.

It seems that Moby project supports this, since I used to contribute to Moby project.

I think there are two ways:

* hack in PouchContainer's project
* contribute to upstream project `github.com/go-check/check`. I think someone definitely has done this work. Does it not work for the go-check owner?

@ZYecho

**Comment by ZYecho** [comment]
> > IMO, it's not enough, lack of many useful checker such as strings.Containes or HasPrefix.
> 
> It seems that Moby project supports this, since I used to contribute to Moby project.
> 
> I think there are two ways:
> 
> * hack in PouchContainer's project
> * contribute to upstream project `github.com/go-check/check`. I think someone definitely has done this work. Does it not work for the go-check owner?
> 
> @ZYecho

Yes, the moby project use both `go-check` and `github.com/vdemeester/shakers` packages, so this may be a third way to do that.

And I think the `go-check` is a little bit inactive, since someone have an issue [#60 ](https://github.com/go-check/check/issues/60) but seems nobody working on that.

**Comment by fuweid** [comment]
any update @ZYecho ?

**Comment by ZYecho** [comment]
close it now, if we have more voices to do it then we reopen it.
