### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:265: starting container process caused "open /dev/pts/2: no such file or directory": unknown

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#2511]
### Ⅰ. Issue Description
I cannot reproduce this error, but it indeed occurred in kubernetes product environment.

may related to https://github.com/docker/for-linux/issues/238
fixed in runc: https://github.com/opencontainers/runc/pull/1727

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Ace-Tang** [comment]
Could you provide more infomation, like error log or something? @HusterWan

**Comment by allencloud** [comment]
Have it been fixed in some version of containerd, which will vendor runc. @HusterWan

**Comment by Ace-Tang** [comment]
I have do a re-produce test, and it not related to opencontainers/runc#1727, I will do more check
