### ISSUE TITLE
[bug] pouch inspect can not get valid cpuquota

### ISSUE THREAD

**Issue by changyaowei** [alibaba/pouch#2538]
### Ⅰ. Issue Description
Through `pouch inspect ` cmd, we can't  get a valid CpuQuota

### Ⅱ. Describe what happened
When we create pouch container by CRI, we assigned CpuQuota, but after created , the CpuQuota we get by  `pouch inspect ` is zero.
![image](https://user-images.githubusercontent.com/12136478/49514989-9c104c80-f8d0-11e8-8756-9c8f6b06183b.png)

### Ⅲ. Describe what you expected to happen

The cpuQuota which get by `pouch inspect` cmd same to what we assigned.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
```
GitCommit:       633a2aa
GoVersion:       go1.9.1
KernelVersion:   3.10.0-327.ali2010.rc2.alios7.x86_64
Os:              linux
Version:         1.0.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-10-11T08:23:00+00:00
```
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

- Install tools:
- Others:

**Comment by Ace-Tang** [comment]
Can you post container create config, you can found that in `/var/log/pouch` @changyaowei

**Comment by changyaowei** [comment]
> Can you post container create config, you can found that in `/var/log/pouch` @changyaowei

I will give it to you in private.

**Comment by HusterWan** [comment]
I check the pouch logs, and found that during we were creating the container, we also got a request `UpdateContainerResources `, the update request parameters:

```
time="2018-12-05T01:06:26.354598534+08:00" level=info msg="UpdateContainerResources for "cdb744a994dfba300d1813db003b1de9a7f42d7339b8164173fe399b5f7250d0" with &LinuxContainerResources{CpuPeriod:0,CpuQuota:0,CpuShares:0,MemoryLimitInBytes:0,OomScoreAdj:0,CpusetCpus:0-7,CpusetMems:,DiskQuota:map[string]string{},BlkioWeight:0,BlkioWeightDevice:[],BlkioDeviceReadBps:[],BlkioDeviceWriteBps:[],BlkioDeviceRead_IOps:[],BlkioDeviceWrite_IOps:[],KernelMemory:0,MemoryReservation:0,MemorySwappiness:nil,Ulimits:[],}"
```

the `CpuQuota` is 0 and it is considered valid, so the container's `CpuQuota` was updated to 0

![image](https://user-images.githubusercontent.com/10414039/49522991-c9b2c100-f8e3-11e8-8705-7829499cdd7a.png)

**Comment by allencloud** [comment]
Any update on this? @HusterWan @fuweid @rudyfly

**Comment by HusterWan** [comment]
> Any update on this? @HusterWan @fuweid @rudyfly

@allencloud fix this problem is simple but before that @changyaowei should fix first. Am I right?
