### ISSUE TITLE
[Bug] Cannot get a valid user name by CRI ImageStatus or ListImages interface

### ISSUE THREAD

**Issue by changyaowei** [alibaba/pouch#2548]
### Ⅰ. Issue Description
When defines a container runtime user name in image, e.g.
![image](https://user-images.githubusercontent.com/12136478/49785416-76b19180-fd5b-11e8-877e-4ebc5972cdad.png)

Kubelet will read and parse it from CRI ImageStatus interface , and pass runtime user to createContainer CRI. 
In kubelet logic , first choose use uid if it is not nil, then we choose user name if it is not empty,
![image](https://user-images.githubusercontent.com/12136478/49785432-8335ea00-fd5b-11e8-9769-ee3e625eb9ef.png)

But in pouch CRI logic, ImageStatus and ListImages interface call `imageToCriImage`, which it will initialize `Uid` as `runtime.Int64Value{}`, so in any case, the `Uid` will not be nil
![image](https://user-images.githubusercontent.com/12136478/49785319-2df9d880-fd5b-11e8-8be2-ed4cd4397613.png)
So if user define user in image, it can't work as user expect.

### Ⅲ. Describe what you expected to happen
Return real uid and username in image info

### Ⅵ. Envronment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HusterWan** [comment]
@changyaowei Look forward your PR 😆
