### ISSUE TITLE
bug: `StringSliceEqual` is wrong

### ISSUE THREAD

**Issue by zhuangqh** [alibaba/pouch#2560]
### Ⅰ. Issue Description

The implementation of `StringSliceEqual` is wrong.

```go
// StringSliceEqual compare two string slice, ignore the order.
func StringSliceEqual(s1, s2 []string) bool {
	if s1 == nil && s2 == nil {
		return true
	}

	if s1 == nil || s2 == nil {
		return false
	}

	if len(s1) != len(s2) {
		return false
	}

	for _, s := range s1 {
		if ok := StringInSlice(s2, s); !ok {
			return false
		}
	}

	for _, s := range s2 {
		if ok := StringInSlice(s1, s); !ok {
			return false
		}
	}

	return true
}
```

### Ⅱ. Describe what happened

[]string{"a", "a", "b"} is not equal to []string{"a", "b","b"}. but StringSliceEqual return true

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HusterWan** [comment]
I have implemented a new function in https://github.com/pouchcontainer/d2p-migrator/pull/26/files#diff-cd575165f84eed10d10eb1460b0927b4R75

Maybe we can discuss whether it is proper :)
