### ISSUE TITLE
[issue report] pouch should support seccomp by default

### ISSUE THREAD

**Issue by KnoooW** [alibaba/pouch#2562]
As docker has already use seccomp as default configuration. pouch should support that, it
can enhance security significantly

**Comment by Ace-Tang** [comment]
@KnoooW , sorry but pouch won't make it default (more reasons cause ourself's usecase), followed by https://github.com/alibaba/pouch/blob/master/INSTALLATION.md#build-tags if you want this.
```
make BUILDTAGS='seccomp'
```

**Comment by allencloud** [comment]
Thanks for your feedback.
oh, let us wait a minute. I think we could make it support seccomp in the released package. Then end users could experience this feature in the next release. @KnoooW @Ace-Tang 

So, please support this in when we make the next release. @fuweid

**Comment by Ace-Tang** [comment]
This make sense for me.

**Comment by KnoooW** [comment]
the attack difficulty:
(1) without seccomp: 50 
(2) with seccomp: 98

**Comment by fuweid** [comment]
@KnoooW I have released new version 1.1.0 with seccomp. Please check it by deb or rpm package. Thanks

```
vagrant@ubuntu-xenial:~$ sudo pouch info | grep Security
Security Options:  [seccomp]
vagrant@ubuntu-xenial:~$ sudo pouch version
Os:              linux
Version:         1.1.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-12-24T08:22:16+00:00
GitCommit:       1.1.0
GoVersion:       go1.10.4
KernelVersion:   4.4.0-141-generic


[vagrant@localhost ~]$ sudo /usr/local/bin/pouch info | grep Secur
Security Options:  [seccomp selinux]
[vagrant@localhost ~]$ sudo /usr/local/bin/pouch version
Os:              linux
Version:         1.1.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-12-24T10:07:01+00:00
GitCommit:       1.1.0
GoVersion:       go1.10.4
KernelVersion:   3.10.0-862.2.3.el7.x86_64
```

**Comment by fuweid** [comment]
@KnoooW any update here?

**Comment by KnoooW** [comment]
> @KnoooW any update here?

Great! update and test, seccomp take effects by default.

**Comment by allencloud** [comment]
Thanks for your experiement. @KnoooW Could we close this issue?
