### ISSUE TITLE
[proposal] The CRI of "Status" returns more information of system

### ISSUE THREAD

**Issue by zjumoon01** [alibaba/pouch#2568]
## Why you need it?

The response of "Status" CRI contains extra information of the Runtime. However,  there is only "golang version" in the extra information returned. It will be useful if more information is returned, such as "pouch root dir". In my scenario, I intend to limit rootfs iops/bps for pods. So I need get pouch root dir first and translate into its device. Then I can set device and rate limit to pods.

## How it could be?

StatusResponse could contains more extra information, 

## Other related information

What other extra information can be returned ? That can be discussed. I think we can refer to "pouch info"

**Comment by Starnop** [comment]
Yes, you are absolutely right.  In fact, we don't know what the end users really needs. Thanks for your input, and I hope that you can have a list here. 👍

**Comment by zhuangqh** [comment]
RFC:

| key | value |
| --- | ---- |
| config | marshal [daemon config](  https://github.com/alibaba/pouch/blob/master/daemon/config/config.go#L30) |

**Comment by zhuangqh** [comment]
compared with directly put each kv to the map.
1. json value support not only string value
2. It is unnecessary to know the exactly spell of each key.
