### ISSUE TITLE
The command is unknown with containerd: 1.0.0#236

### ISSUE THREAD

**Issue by Starnop** [alibaba/pouch#259]
**Issue Description**
When I use containerd 1.0.0 as 
**Describe what happened**:
When I prepare the pouch environment, I uses containerd: 1.0.0 not containerd for beta, and then pouch images ls is unknown.
**Describe what you expected to happen**:
Use containerd: 1.0.0 not for beta.
**How to reproduce it (as minimally and precisely as possible)**:
1.Prepare the pouch environment with containerd: 1.0.0
2.start pouthd
3.run pouch images ls,and then
```
[root@localhost cli]# pouch images ls
Error: unknown command "ls" for "pouch images"
[root@localhost cli]# pouch images
IMAGE ID             IMAGE NAME                                               SIZE
bbc3a0323522         docker.io/library/busybox:latest                         2.64 KB
```
**Anything else we need to know?**:
NONE
**Environment**: 
- pouch version (use `pouch version`):0.1.0-dev
- OS (e.g. from /etc/os-release):Centos7
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Install tools:
- Others: containerd: 1.0.0

**Comment by allencloud** [comment]
I think we did not support `pouch images ls`, looking the code:
```
// Init initialize images command.
func (i *ImageCommand) Init(c *Cli) {
	i.cli = c
	i.cmd = &cobra.Command{
		Use:   "images",
		Short: "List all images",
		Long:  imagesDescription,
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return i.runImages(args)
		},
		Example: imagesExample(),
	}

	i.addFlags()
}
```
We said NoArgs after images. We know that containerd ctr can be used as `ctr images ls`. However it is not the way of Pouch, at least currently not.

@Starnop

**Comment by Starnop** [comment]
Oops, and then the pouch/INSTALLATION.md should be alerted around the end of file.

**Comment by allencloud** [comment]
😭  Oh, Installation.md has things which are incorrect. You got it. Would you like to submit a pull request to change that part? @Starnop

**Comment by Starnop** [comment]
Of course, my honor
