### ISSUE TITLE
[feature request] support more kubernetes version e2e test

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#2590]
## Why you need it?

Currently the latest upstream kubernetes release has been developed to be 1.13, while the default test version of kubernetes in PouchContainer is just 1.10, see https://github.com/alibaba/pouch/blob/master/hack/testing/run_daemon_cri_e2e.sh#L64

```
# integration::run_daemon_cri_test_e2e_cases runs CRI e2e test cases.
integration::run_daemon_cri_test_e2e_cases() {
  local cri_runtime code KUBERNETES_VERSION
  cri_runtime=$1

  if [[ "${cri_runtime}" == "v1alpha1" ]]; then
    KUBERNETES_VERSION="release-1.9"
  else
    KUBERNETES_VERSION="release-1.10"
  fi
```

Thus we have not tested kubernetes 1.11, 1.12 or 1.13.

In fact, we will try to choose several reasonable versions in node end-to-end test in CI system.

## How it could be?

In travisCI system, we support more new released version kubernetes testing.

## Other related information

none

**Comment by zhuangqh** [comment]
TODO

- [ ] create a table to illustrate the compatibility between PouchContainer and kubernetes
include 1.9/ 1.10～1.11/ 1.12, put it on README
