### ISSUE TITLE
[bug] cannot top a paused container

### ISSUE THREAD

**Issue by drpmma** [alibaba/pouch#2598]
### Ⅰ. Issue Description

cannot top a paused container

### Ⅱ. Describe what happened
```shell
# pouch ps
Name     ID       Status              Created      Image                                        Runtime
526664   526664   Up 4 days(paused)   4 days ago   registry.hub.docker.com/library/tomcat:8.0   runc

# pouch top 526664
Error: failed to execute top command in container 526664: {"message":"container 5266649ef248b86747390113555361c512cc939423b00e4e9691b560dc5a856f is not running, cannot execute top command"}
```

### Ⅲ. Describe what you expected to happen

I cannot top a paused container **while docker is able to do so**. 
So I'm wondering is it a feature or bug and whether it is possible to add this feature?
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. just start a pouch container.
2. pause it.
3. and top it.

### Ⅴ. Anything else we need to know?
nope

### Ⅵ. Environment:

- pouch version (use `pouch version`): 
GoVersion:       go1.10.4
KernelVersion:   3.10.0-327.ali2018.alios7.x86_64
Os:              linux
Version:         1.0.1
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-11-23T02:12:11+00:00
GitCommit:       1.0.1
- OS (e.g. from /etc/os-release):
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2
- Kernel (e.g. `uname -a`):
Linux mqperf.s09.03 3.10.0-327.ali2018.alios7.x86_64 #1 SMP Mon Jul 23 15:08:28 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
followed INSTALLATION.md with yum
- Others:
nope

**Comment by allencloud** [comment]
Does containerd support to top a paused container? @fuweid @Ace-Tang

**Comment by ZYecho** [comment]
@allencloud I dive into some codes about top in moby and pouch and find some result,
1. containerd support that, since both of pouch and moby use containerd's task listPids api
2. the problem may due to the definition of pouch's container state, when pouchd status pause a container, it just change the status to `Paused`, but the moby said `Note that `Running` and `Paused` are not mutually exclusive`, so I think this is the source which caused the behavior difference.
