### ISSUE TITLE
[community] Please join PouchContainer dev group via Dingtalk to have fun

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#2628]
## Question

PouchContainer team hopes that all people interested in container technology or PouchContainer could participant in the warm communication of community.

Currently, we have created a Dingtalk Group(钉钉群) for the community. While it is almost for the Chinese guys. This Group has also integrated the GitHub webhook to know the status change of this repo.

If you are interested in PouchContainer or container related engineers, please joins us to enjoy it.

Here is a scan code of PouchContainer Dev Group on DingTalk(钉钉)：
![ladpdgq9qatimilna97nau4_750_990](https://user-images.githubusercontent.com/9465626/50506321-497f1600-0ab3-11e9-9aa2-57c807c753a8.jpg)

**Comment by staugust** [comment]
Ah, this QR code is expired. Would you please replace the expired QR code with a fresh one?

**Comment by johnmelodyme** [comment]
expired

**Comment by Windfarer** [comment]
There's 2 years no commit and 3 years no release, is this project dead?

**Comment by johnmelodyme** [comment]
> There're 2 years no commit and 3 years no release, is this project dead?

Maybe.
