### ISSUE TITLE
Can pouchd support http protocol when pull image?

### ISSUE THREAD

**Issue by wzhx78** [alibaba/pouch#2663]
## Why you need it?
when we use pouch,  we want to use http protocol when pull image,  but pouchd failed to pull image.                                                     
## How it could be?
pouchd version: 1.1.0

Error message:
![image](https://user-images.githubusercontent.com/2056897/51094254-50619480-17e6-11e9-82f7-1e4750455982.png)

**Comment by houstar** [comment]
"Server gave HTTP response to HTTPS client", so I assume our Pouch Daemon might be only supports HTTP Protocol in v1.1.0.   please see source code  in pouch/ctrd/image_proxy_util.go  directly :-0
