### ISSUE TITLE
"pouch rmi" command not find

### ISSUE THREAD

**Issue by wuren1986** [alibaba/pouch#268]
**Issue Description**
"pouch rmi" command not find.
**Describe what happened**:
"pouch rmi" command not find.
**Describe what you expected to happen**:
The command to remove the local images.
**How to reproduce it (as minimally and precisely as possible)**:
None

**Anything else we need to know?**:
None
**Environment**:
- pouch version (use `pouch version`):0.1.0-dev
- OS (e.g. from /etc/os-release):CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`):3.10.0-514.el7.x86_64
- Install tools:
- Others:

**Comment by 0x04C2** [comment]
hi @wuren1986 , the feature is still under the review #226. please stay tuned. :)

**Comment by allencloud** [comment]
Yeah, like @0x04C2 mentioned.

**Comment by allencloud** [comment]
This feature is already in master, please enjoy with that.
And feel free to tell us if you need any help. Thanks for reporting. @wuren1986
