### ISSUE TITLE
[RFC] move CRI v1alpha1 support to END OF LIFE

### ISSUE THREAD

**Issue by zhuangqh** [alibaba/pouch#2689]
## What

CRI v1alpha1 version is deprecated nowadays.  **We are going to remove the CRI v1alpha1 interface support on March 31 2019.**  

Please leave a comment if you are using Kubernetes v1.9 and feel free to tell us what's your requirement.

## Support Metrics

Date: Jan 23 2019

| Kubernetes Version | CRI Version | PouchContainer Version |
| --- | --- | --- |
| 1.9 | v1alpha1 | v1.0+ |
| 1.10+ | v1alpha2 | v1.0+|

**Comment by allencloud** [comment]
Any update on this? @zhuangqh 
If we will do it on 31 March, which version will it be included in?

**Comment by zhuangqh** [comment]
> Any update on this? @zhuangqh
> If we will do it on 31 March, which version will it be included in?

The PouchContainer next release.
