### ISSUE TITLE
[feature request] support Intel RDT

### ISSUE THREAD

**Issue by CodeJuan** [alibaba/pouch#269]
# Introduction of RDT
Intel Resource Director Technology (RDT) is a key feature set to optimize application performance and enhance the capabilities of orchestration and virtualization management server systems using Intel® Xeon® processors.

RDT consisted of two resource allocation sub-feature:
1. **Cache Allocation Technology (CAT)**. CAT provides software-programmable control over the amount of cache space that can be consumed by a given thread, app, VM, or container. This allows, for example, OSs to protect important processes, or hypervisors to prioritize important VMs even in a noisy datacenter environment.
2. **Memory Bandwidth Allocation (MBA)**. MBA provides indirect and approximate throttle over memory bandwidth (b/w) for the software. A user controls the resource by indicating the percentage of maximum memory b/w.

# kernel requirement
1. CAT: 4.10+
2. MBA:  4.12+

# TODO
To support Intel RDT, We need to add these things in Pouch:
- [ ] Pouchd
  - [ ] Design document
  - [ ] API integration
- [ ] runc: thanks for the greate contribution of @xiaochenshen, [CAT PR](https://github.com/opencontainers/runc/pull/1279) was merged to master of runc. [MBA PR](https://github.com/opencontainers/runc/pull/1632) is opened.
- [ ] Integration of Pouchd and runc

# reference
- https://github.com/opencontainers/runc/issues/433
- https://github.com/opencontainers/runc/issues/1596
- https://software.intel.com/en-us/articles/introduction-to-cache-allocation-technology

**Comment by allencloud** [comment]
This has been finished in https://github.com/alibaba/pouch/pull/742, closing this.
