### ISSUE TITLE
[feature request] CRI support memory_swap 

### ISSUE THREAD

**Issue by wangforthinker** [alibaba/pouch#2698]
## Why you need it?

We want to set memory swap by CRI interface.

## How it could be?

There are two suggestion.
Add a field of MemorySwap in LinuxContainerResources struct.
Define an annotation key such as memory_swap and transfer it by Annotations field.

**Comment by zhuangqh** [comment]
good advise. Using annotation for extension fields to achieve the least break of CRI interface.
