### ISSUE TITLE
merge volume metadata store into meta module

### ISSUE THREAD

**Issue by rudyfly** [alibaba/pouch#27]
**Issue Description**
volume metadata store is different from container store, we should merge them into one module.

**Comment by allencloud** [comment]
Since this is a 20-days issue, could you sync with us the latest status of that? @rudyfly

**Comment by rudyfly** [comment]
I haven't started this job, can I pause this job?

**Comment by allencloud** [comment]
Thanks for feedback. Actually in my opinion, you can leave this issue just there. However maybe if you are current not on this part, you could sync with others on github under this issue, then more people know that this work may not be in your working queue currently. And it will improve a little bit in project management.  @rudyfly
