### ISSUE TITLE
pouch.rpm conflicts with the nvidia official libnvidia-container-runtime.rpm package

### ISSUE THREAD

**Issue by eryx** [alibaba/pouch#2729]
### Ⅰ. Issue Description

OS: CentOS 7.6

1. install pouch-1.2.0-1.el7.x86_64.rpm
repo:  https://mirrors.aliyun.com/pouch/centos7.repo

2. install nvidia CUDA framework
download from https://developer.nvidia.com/cuda-downloads?target_os=Linux
rpm -i cuda-repo-rhel7-10-1-local-10.1.105-418.39-1.0-1.x86_64.rpm
yum install cuda

3. install nvidia-docker
https://github.com/NVIDIA/nvidia-docker  (CentOS 7, docker-ce)
yum install -y nvidia-docker2

error message:
``` shell
Downloading packages:
(1/5): nvidia-docker2-2.0.3-1.docker18.09.2.ce.noarch.rpm                                                                                                                                 | 4.6 kB  00:00:00     
(2/5): libnvidia-container-tools-1.0.1-1.x86_64.rpm                                                                                                                                       |  33 kB  00:00:00     
(3/5): libnvidia-container1-1.0.1-1.x86_64.rpm                                                                                                                                            |  74 kB  00:00:01     
(4/5): nvidia-container-runtime-hook-1.4.0-2.x86_64.rpm                                                                                                                                   | 616 kB  00:00:09     
(5/5): nvidia-container-runtime-2.0.0-1.docker18.09.2.x86_64.rpm                                                                                                                          | 2.7 MB  00:00:33     
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                            103 kB/s | 3.4 MB  00:00:33     
Running transaction check
Running transaction test


Transaction check error:
  file /usr/lib64/libnvidia-container.so.1 from install of libnvidia-container1-1.0.1-1.x86_64 conflicts with file from package pouch-1.2.0-1.el7.x86_64

Error Summary
-------------

```
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): centos 7.6
- Install tools: rpm, yum
- Others:

**Comment by allencloud** [comment]
Do we provide an official way to install GPU's essential software? @CodeJuan 
I only find the doc with how to run containers with GPU https://github.com/alibaba/pouch/blob/master/docs/features/pouch_with_gpu.md, but no installation guidance.

**Comment by allencloud** [comment]
Any update on this? @CodeJuan @fuweid

**Comment by houstar** [comment]
@CodeJuan  @fuweid For this conflicts, I'd like to not integrate the libnvida-container library into Pouch RPM but set libnvidia-container as our Pouch's RPM dependency.

**Comment by fuweid** [comment]
Hi @houstar , thanks for comment. I am open to any suggestion. will appreciate if you can file a issue or pr to https://github.com/pouchcontainer/project  :)
