### ISSUE TITLE
enableLxcfs not work for alpine based containers

### ISSUE THREAD

**Issue by libnux** [alibaba/pouch#2768]
### Ⅰ. Issue Description
After enabling lxcfs, memory limit works for ubuntu containers,but  did not work for alpine-based containers.

### Ⅱ. Describe what happened
1. lxcfs enabled:

> $ ps aux | grep -E "(pouchd|lxcfs)"  
> root       931  0.0  0.0 161076  1724 ?        Ssl  20:39   0:00 /usr/bin/lxcfs /var/lib/lxcfs/
> root      2808  0.6  0.8 1211132 65500 ?       Ssl  20:40   0:03 /usr/local/bin/pouchd --enable-lxcfs
> 

2. worked for ubuntu

> $ pouch run -m 200m --enableLxcfs ubuntu  free -m
> WARNING: Current Kernel does not support memory swap, discard --memory-swap
>               total        used        free      shared  buff/cache   available
> Mem:            200           1         198           0           0         198
> Swap:          1952           0        1952

3. not work for alpine-based containers, showing the host memory size: **7872M**

> $pouch run -m 200m --enableLxcfs alpine  free -m
> WARNING: Current Kernel does not support memory swap, discard --memory-swap
>              total       used       free     shared    buffers     cached
> Mem:          7872       4037       3834         49        149          0
> -/+ buffers/cache:       3887       3984
> Swap:         1952          0       1952
> $pouch run -m 200m --enableLxcfs nginx:alpine  free -m
> WARNING: Current Kernel does not support memory swap, discard --memory-swap
>              total       used       free     shared    buffers     cached
> Mem:          7872       4037       3834         49        149          0
> -/+ buffers/cache:       3887       3984
> Swap:         1952          0       1952

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
```
KernelVersion:   4.15.0-46-generic
Os:              linux
Version:         1.2.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2019-02-14T02:21:34+00:00
GitCommit:       1.2.0
GoVersion:       go1.10.4
```
- OS (e.g. from /etc/os-release):
```
Ubuntu 18.04
```
- Kernel (e.g. `uname -a`):
```
Linux laptop 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by allencloud** [comment]
That is quite interesting. I do not think it is related to the specific images. While it seems strange things happened. We will dig on it.

**Comment by allencloud** [comment]
Quite strange. Actually I cannot reproduce this on my machine:
```
root@ubuntu:~# pouch run -m 200m --enableLxcfs alpine free -m
WARNING: Current Kernel does not support memory swap, discard --memory-swap
             total       used       free     shared    buffers     cached
Mem:          2000        580       1419          3         19        403
-/+ buffers/cache:        157       1842
Swap:         2045          0       2045
root@ubuntu:~# uname -a
Linux ubuntu 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

root@ubuntu:~# pouch info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
ID:
Name: ubuntu
Server Version: 1.2.0
Storage Driver: overlayfs
Driver Status: []
Logging Driver: json-file
Volume Drivers: [local tmpfs]
Cgroup Driver: cgroupfs
Default Runtime: runc
Runtimes: runc
runc: <nil>
containerd: <nil>
Security Options: []
Kernel Version: 4.4.0-87-generic
Operating System: "Ubuntu 16.04.3 LTS"
OSType: linux
Architecture: amd64
HTTP Proxy:
HTTPS Proxy:
Registry: https://index.docker.io/v1/
Experimental: false
Debug: false
Labels:
  node_ip=127.0.1.1
  SN=0
CPUs: 1
Total Memory: 1.953GiB
Pouch Root Dir: /var/lib/pouch
LiveRestoreEnabled: true
LxcfsEnabled: false
CriEnabled: false
Daemon Listen Addresses: [unix:///var/run/pouchd.sock]
```

Could you help to dig this issue as well? @libnux Please tell us if you have any problems.

**Comment by allencloud** [comment]
I have reproduced it:
```
root@ubuntu:~# pouch run -m 123m --enableLxcfs ubuntu:16.04 free -m
WARNING: Current Kernel does not support memory swap, discard --memory-swap
              total        used        free      shared  buff/cache   available
Mem:            123           0         122           3           0         122
Swap:          2045           0        2045
root@ubuntu:~# pouch run -m 123m --enableLxcfs alpine free -m
WARNING: Current Kernel does not support memory swap, discard --memory-swap
             total       used       free     shared    buffers     cached
Mem:          2000        558       1441          3         20          0
-/+ buffers/cache:        538       1461
Swap:         2045          0       2045
```

**Comment by allencloud** [comment]
I think the file /proc/meminfo inside of both container alpine and ubuntu are taken effect to take mem 123m, see:
```
root@ubuntu:~# pouch run -it -m 123m --enableLxcfs alpine sh
WARNING: Current Kernel does not support memory swap, discard --memory-swap
/ # cat /proc/meminfo
MemTotal:         125952 kB
MemFree:          125416 kB
MemAvailable:     125416 kB
Buffers:               0 kB
Cached:               16 kB
SwapCached:            0 kB
Active:              188 kB
...
/ # free -m
             total       used       free     shared    buffers     cached
Mem:          2000        576       1423          3         20          0
-/+ buffers/cache:        556       1443
Swap:         2045          0       2045
/ # top


root@ubuntu:~# pouch run -it -m 123m --enableLxcfs ubuntu:16.04 sh
WARNING: Current Kernel does not support memory swap, discard --memory-swap
# cat /proc/meminfo
MemTotal:         125952 kB
MemFree:          125172 kB
MemAvailable:     125172 kB
Buffers:               0 kB
Cached:               12 kB
SwapCached:            0 kB
Active:              316 kB
Inactive:              0 kB
# free -m
              total        used        free      shared  buff/cache   available
Mem:            123           0         122           3           0         122
Swap:
```

I begin to be suspicious of the binary `free` of two images. 
Do you have any input? @CodeJuan @libnux

**Comment by libnux** [comment]
@allencloud I see the same behavior as you. After stracing the "free" command in alpine container, seems that it calculated meminfo from the sysinfo  system call and the /proc/meminfo file. 

Closing this issue, since It should be problem of busybox toolbox in alpine. Thanks for you help.
According to https://github.com/lxc/lxcfs/issues/202, lxcfs does not support sysinfo virtualization.

> / # strace free -m
execve("/usr/bin/free", ["free", "-m"], 0x7fff8da9c4e8 /* 5 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7f6d8ac86b68) = 0
set_tid_address(0x7f6d8ac86ba8)         = 14
mprotect(0x7f6d8ac83000, 4096, PROT_READ) = 0
mprotect(0x5561ce48d000, 16384, PROT_READ) = 0
getuid()                                = 0
ioctl(1, TIOCGWINSZ, {ws_row=0, ws_col=0, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{iov_base="             total       used   "..., iov_len=73}, {iov_base="\n", iov_len=1}], 2             total       used       free     shared    buffers     cached
) = 74
sysinfo({uptime=277, loads=[30848, 33600, 16672], totalram=8254693376, freeram=4862984192, sharedram=23855104, bufferram=136732672, totalswap=2047864832, freeswap=2047864832, procs=663, totalhigh=0, freehigh=0, mem_unit=1}) = 0
open("/proc/meminfo", O_RDONLY)         = 3
read(3, "MemTotal:         125952 kB\nMemF"..., 1024) = 1024
lseek(3, -884, SEEK_CUR)                = 140
close(3)                                = 0
writev(1, [{iov_base="Mem:          7872       3234   "..., iov_len=73}, {iov_base="\n", iov_len=1}], 2Mem:          7872       3234       4637         22        130          2
) = 74
writev(1, [{iov_base="-/+ buffers/cache:       3101   "..., iov_len=40}, {iov_base="\n", iov_len=1}], 2-/+ buffers/cache:       3101       4770
) = 41
writev(1, [{iov_base="Swap:         1952          0   "..., iov_len=40}, {iov_base="\n", iov_len=1}], 2Swap:         1952          0       1952
) = 41
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by allencloud** [comment]
Thanks for your issue. Please feel free to contact us if you meet any problems. Thanks. @libnux 
If you wish to contact with us, please make sure you have read the issue https://github.com/alibaba/pouch/issues/2628.
