### ISSUE TITLE
[bug] pouch load docker_image failed

### ISSUE THREAD

**Issue by mushixun** [alibaba/pouch#2787]
### Ⅰ. Issue Description
I want load docker format image to pouch,but not success

### Ⅱ. Describe what happened
![image](https://user-images.githubusercontent.com/10143373/55317411-0dd55d00-54a3-11e9-9731-0c0cf2d1f357.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:
![image](https://user-images.githubusercontent.com/10143373/55317477-2ba2c200-54a3-11e9-8c25-2cca0a72f8b8.png)

![image](https://user-images.githubusercontent.com/10143373/55317515-437a4600-54a3-11e9-89a5-f85b8f26cf76.png)

![image](https://user-images.githubusercontent.com/10143373/55317542-512fcb80-54a3-11e9-89b2-7057d8123b17.png)

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
have you error tried to load this `pause.tar` with docker? Just confirm @mushixun

**Comment by fuweid** [comment]
@mushixun could you mind to provide the source image name? I mean where the pause.tar comes from.

**Comment by mushixun** [comment]
yes ,success
![image](https://user-images.githubusercontent.com/10143373/55319357-47a86280-54a7-11e9-8aa1-8b5df87c601d.png)
@allencloud

**Comment by mushixun** [comment]
test.registry.zj.chinamobile.com/kubernetes/pause:3.1 @fuweid

**Comment by fuweid** [comment]
@mushixun could you try `pouch load -i pause.tar test.registry.zj.chinamobile.com/kubernetes/pause`?

**Comment by mushixun** [comment]
good,this is success
![image](https://user-images.githubusercontent.com/10143373/55367654-a958e300-5520-11e9-8859-dd5d5c7ccfee.png)
can i not write the parameter test.registry.zj.chinamobile.com/kubernetes/pause? only write pouch load -i pause.tar

**Comment by fuweid** [comment]
Yep. I will handle this.

**Comment by allencloud** [comment]
Any update on this? @fuweid
