### ISSUE TITLE
[bug] IMAGE NAME changed after pouch load 

### ISSUE THREAD

**Issue by lgd8069465** [alibaba/pouch#2788]
## Question

CentOS Linux release 7.6.1810 (Core)
pouch Server Version: 1.2.0

![image](https://user-images.githubusercontent.com/7867042/55371217-fd1ef880-552f-11e9-90cb-65b639c705f9.png)

**Comment by xiechengsheng** [comment]
You should provide image name in `load` command. So please use `pouch load -i nginx` instead.

**Comment by lgd8069465** [comment]
OK! Thanks!

**Comment by fuweid** [comment]
@lgd8069465 thanks for report. For OCI image, we need to set the name for image. If the tar file is from docker save, we also set the name which is same to the docker image name. 

It is quite different with docker. But I think we can find a better to save the origin name.
