### ISSUE TITLE
Useless break statement

### ISSUE THREAD

**Issue by 360CodeSafe** [alibaba/pouch#2804]
### Ⅰ. Issue Description
`break` does nothing here:
https://github.com/alibaba/pouch/blob/9f56fefa28b2237b482540f0e217135ad14a276d/storage/quota/quota.go#L289-L293

Maybe you mean breaking the loop, so you need to add a label to the break statement.

**Comment by HusterWan** [comment]
@360CodeSafe thanks for what you have found, we should fix it @rudyfly

**Comment by allencloud** [comment]
Any update？ Or could you help to submit a PR to fix this？ @360CodeSafe
