### ISSUE TITLE
大神好！，请问下pouch到底是什么

### ISSUE THREAD

**Issue by githublaohu** [alibaba/pouch#2808]
看了很多资料都没有看懂pouch是什么，能有中文文档吗？毕竟国内的市场比别国（别人国家）还要大哈。

**Comment by houstar** [comment]
有志愿者做文档翻译吗？翻译成中文还是比较好的

**Comment by githublaohu** [comment]
> 有志愿者做文档翻译吗？翻译成中文还是比较好的

抱歉哈，我的英语水平太差了。但是我可以做一些开发哈。

**Comment by allencloud** [comment]
> 但是我可以做一些开发哈。

非常欢迎您来参与贡献PouchContainer代码，详见：https://github.com/alibaba/pouch/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

@githublaohu

**Comment by githublaohu** [comment]
好的，谢谢。进入一个开源项目需要一定的时间，需要一点时间了解开发流程，pr流程。我先把开发环境先搭建起来哈。
