### ISSUE TITLE
Add a function set let user set proxy

### ISSUE THREAD

**Issue by taoshaoyu** [alibaba/pouch#2814]
## Question

Hi
Can pouch be used behind a proxy. Just like docker 
https://docs.docker.com/config/daemon/systemd/#httphttps-proxy
I can create a /etc/systemd/system/docker.service.d/http-proxy.conf and set proxy in it
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:80/"

**Comment by hellolijj** [comment]
Actually, pouch support this feature. it is used like follow command `pouchd --image-proxy=http://proxy.example.com:80/`. obviously, it is unfriendly for non developer.
Docker implements this function by reading the configuration file `/etc/systemd/system/docker.service.d/http-proxy.conf`. Do we need optimize like this ? @allencloud

**Comment by taoshaoyu** [comment]
@hellolijj ,Hi, I has tried this function (--image-proxy=http://proxy.example.com:80/) , but it looks that just only support http proxy, not yet support https_proxy ? Is it right ?
Thanks

**Comment by hellolijj** [comment]
@taoshaoyu  Indeed,  you are right. here https://github.com/alibaba/pouch/blob/master/daemon/mgr/system.go#L150-L151 , we can see https_proxy  value does't be set.
