### ISSUE TITLE
[bug] can not use inspect -f "{{.Id}}" to get container id

### ISSUE THREAD

**Issue by rudyfly** [alibaba/pouch#2841]
### Ⅰ. Issue Description
can not use `pouch inspect -f "{{.Id}}"` to get container id
use `pouch inspect -f "{{.ID}}"` is ok, so need to fix it.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by CodeJuan** [comment]
@rudyfly Would you please add more details of `what you expected to happen` at your convenience?
Thank you very much.
