### ISSUE TITLE
Installation of runV components encountered problems, please ask how to solve them?

### ISSUE THREAD

**Issue by charlesqing** [alibaba/pouch#2858]
It's time to install the runV component, but I don't know which configuration information is added to the pouch configuration file. Please consult us. Thank you.

// 安装runV组件的时候到了下面这一步，但不知道这段配置信息添加到pouch的哪个配置文件中，请教一下大家，谢谢 

First, add runv into config file, restart pouchd, ensure that pouchd know the specified runtime.
{
    "add-runtime": {
        "runv": {
            "path": "/usr/local/bin/runv"
        }
    }
}

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by HusterWan** [comment]
add it to the pouch config file which default location is `/etc/pouch/config.json`, please create this file if not exist.

**Comment by charlesqing** [comment]
> add it to the pouch config file which default location is `/etc/pouch/config.json`, please create this file if not exist.

谢谢
