### ISSUE TITLE
pouch can not load offline image

### ISSUE THREAD

**Issue by kedy-zhao** [alibaba/pouch#2931]
### Ⅰ. Issue Description
pouch can not load the offlline docker image whch use  "pouch save"  command to save

### Ⅱ. Describe what happened
use “pouch save xxxxx -o hello-world.tar” to save the  image to local, then use "pouch load -i hello-world.tar" it shows "failed to import image into containerd by tarstream: unrecongnized image format"}

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. pouch save hello-world -o hello-world.tar
2. pouch rmi hello-world
3. pouch load -i hello-world.tar

### Ⅵ. Environment:

- pouch version (use `pouch version`):1.3.0
- OS (e.g. from /etc/os-release):centos7.6.1810
- Kernel (e.g. `uname -a`):3.10
- Install tools:
- Others:

**Comment by ZYecho** [comment]
@kedy-zhao  could you post more info about the image and pouchd? using `pouch image inspect `and `pouch version`

**Comment by kedy-zhao** [comment]
> 
> 
> @kedy-zhao could you post more info about the image and pouchd? using `pouch image inspect `and `pouch version`

I installed the pouch-1.3.0-1.el7.x86_64.rpm in centos7.6.1810,

pouch pull hello-world that from registry.hub.docker.com/library/hello-world:latest
then save the hello-world image to a offline one.
pouch save registry.hub.docker.com/library/hello-world:latest -o hello-world.tar

and last execute the below command
pouch load -i hello-world.tar

the terminal shows "failed to import image into containerd by tarstream: unrecongnized image format"

the pouch version is:

Version:             1.3.0
APIVersion:        1.2.4
Arch:                  amd64
BuildTime:          219-06-13T11:25:25
GitCommit:        1.3.0
GoVersion:         go.1.10.4
KernelVersion:    3.10.0-957.12.1
Os:                     linux

**Comment by ZYecho** [comment]
yep, this is a bug in pouch and didn't fix it now. But we will fix it ASAP. thanks for reporting it.

**Comment by fuweid** [comment]
When the image is multiple platform, it will be fail because pouchcontainer only downloads the default platform, for example, linux/amd64. It can be fixed by updated containerd version. It will be fixed late
