### ISSUE TITLE
Several pouch command questions. Please help. 

### ISSUE THREAD

**Issue by jeffgx619** [alibaba/pouch#2962]
Several questions about pouch:

// 几个关于pouch的问题：

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by allencloud** [comment]
Could you please provide more detailed information? Thanks. @jeffgx619

**Comment by ZYecho** [comment]
close it, feel free to open new one if you still have problems.
