### ISSUE TITLE
unknown command "push" for "pouch"

### ISSUE THREAD

**Issue by akawhy** [alibaba/pouch#2998]
### Ⅰ. Issue Description

I install pouch from `yum install pouch`.  The lastest version `1.3.0` don't have the `push` command.

version info

```

$sudo pouch version
BuildTime:       2019-06-13T11:25:25+00:00
GitCommit:       1.3.0
GoVersion:       go1.10.4
KernelVersion:   3.10.0-327.ali2018.alios7.x86_64
Os:              linux
Version:         1.3.0
APIVersion:      1.24
Arch:            amd64

```

package info

```

$sudo yum info pouch
Loaded plugins: branch, fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Installed Packages
Name        : pouch
Arch        : x86_64
Version     : 1.3.0
Release     : 1.el7
Size        : 145 M
Repo        : installed
Summary     : _
URL         : https://github.com/alibaba/pouch
License     : Apache License 2.0
Description :  .

```

command

```

$sudo pouch push ttttt
Error: unknown command "push" for "pouch"

Did you mean this?
        pull
        ps
        pause

```

### Ⅱ. Describe what happened

pouch push command failed

### Ⅲ. Describe what you expected to happen

the push command can work

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fuweid** [comment]
@akawhy thanks for reporting. We already have `push` in master branch. But we still have few patches need to update. Will release soon.

**Comment by cxz66666** [comment]
Seem that `push` command is already can use, just use `pouch push --help` to show how to use!

So this question is closed.
