### ISSUE TITLE
Rich mode containers: Are they safe to run?

### ISSUE THREAD

**Issue by shinebayar-g** [alibaba/pouch#3006]
## Question

[Rich mode](https://pouchcontainer.io/#/pouch/docs/features/pouch_with_rich_container.md) containers: Are they safe to run?

In docs it says:

> Also --privileged is required in this situation.

In docker environment `--privileged` container isn't considered as safe to run as root. So is it same in pouch containers? Or is it safe somehow? Or [runv](https://pouchcontainer.io/#/pouch/docs/features/pouch_with_runV.md) is the way to go for untrusted workloads?

**Rich mode** container is exactly what I was looking for. Please consider adding more realistic scenario in documentation instead of `sleep 10000`? such as running webserver and database on it.

Thank you.

**Comment by fuweid** [comment]
Hi @shinebayar-g, thanks for asking. The rich mode is used to setup systemd/initd/supervisor as pid 1 process. Basically, it is used to be reaper to avoid zombie processes and provide systemctl functionality. And `sleep 10000` is just as example to show how to using it. You can change it to your own process.

**Comment by shinebayar-g** [comment]
Indeed, that's exactly what I needed. However that doesn't answer my question about `--privileged` flag concern.

**Comment by fuweid** [comment]
> Indeed, that's exactly what I needed. However that doesn't answer my question about `--privileged` flag concern.

Yeah. It might have security issue. It depends on your case. The workload is trust and it is fine. Might be rootless can help you if the workload is untrusted.

**Comment by houstar** [comment]
Kata Containers is your choice
