### ISSUE TITLE
no support go 1.15.6

### ISSUE THREAD

**Issue by BaSO4** [alibaba/pouch#3028]
### Ⅰ. Issue Description
quota.go does not match to target system, File will be ignored by build system

### Ⅱ. Describe what happened

in main.go unresolved reference quota.SetQuotaDriver
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:
go 1.15.6
mac 10.15.6 (19G73)

**Comment by yyb196** [comment]
it's not a bug relevant to golang version. It's your GOPATH envrionment variable which set incorrect.

You can use following steps to get it right:
```
# in your work directory where you want pouch source code put
mkdir -p $(pwd)/pouch/src/github.com/alibaba; cd $(pwd)/pouch/src/github.com/alibaba;
git clone git@github.com:alibaba/pouch.git
cd pouch
# the output is the GOPATH you should use.
echo "export GOPATH=$(cd ../../../..; pwd):$(pwd)/vendor"
```

You can open pouch source using vscode or vim, set the GOPATH to the output the above instruction. Pouch source code root is `$(pwd)/pouch/src/github.com/alibaba/pouch`
