### ISSUE TITLE
How to Install pouch on ubuntu18.04

### ISSUE THREAD

**Issue by youbeny** [alibaba/pouch#3030]
### Ⅰ. Issue Description
i follow the steps of ```https://github.com/alibaba/pouch/blob/master/INSTALLATION.md``` ,install pouch on ububtu, but get the following error:
curl -fsSL http://mirrors.aliyun.com/opsx/pouch/linux/debian/opsx@service.alibaba.com.gpg.key | sudo apt-key add -
curl: (22) The requested URL returned error: 404 Not Found
gpg: no valid OpenPGP data found.

it seems the mirrors website is not existed, what should i do？

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
cat /etc/issue
Ubuntu 18.04.5 LTS \n \l
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cardyok** [comment]
The installation manual is outdated. Will update the manual recently :)
