### ISSUE TITLE
Kubernetes 1.22 dose not work with pouch

### ISSUE THREAD

**Issue by devopstales** [alibaba/pouch#3032]
### Ⅰ. Issue Description

Kubelet cannot start containers.

```
Aug 12 17:26:37 alma8 kubelet[9233]: E0812 17:26:37.202196    9233 pod_workers.go:747] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\" with CreateContainerError: \"failed to apply container security context for container \\\"kube-controller-manager\\\": failed to generate seccomp security options: undefault profile \\\"runtime/default\\\" should prefix with \\\"localhost/\\\"\"" pod="kube-system/kube-controller-manager-alma8" podUID=520e787941d90fc4adceac0d0d920cf1
```

### Ⅲ. Describe what you expected to happen
Kubernets woking with pouch.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

I installed my invironment based your documentation:
https://github.com/alibaba/pouch/blob/master/docs/kubernetes/pouch_with_kubernetes_deploying.md

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release): alamlinux 8
- Kernel (e.g. `uname -a`): Linux alma8 4.18.0-305.el8.x86_64 #1 SMP Wed May 19 18:55:28 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm 1.22.0

**Comment by devopstales** [comment]
@Novicei When it will be released? The last release was in 2019. Is this project still alive?

**Comment by simake2017** [comment]
i thins it is dead
