### ISSUE TITLE
[feature] Add a "pouch run" command for cli

### ISSUE THREAD

**Issue by skoo87** [alibaba/pouch#351]
**Issue Description**
run command be used to replace "create" and "start" commands.

**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Could you help to add a `pouch run` command to combine create and start API? @HusterWan 🧀 🦁

**Comment by HusterWan** [comment]
of course, my pleasure! @allencloud
