### ISSUE TITLE
CI is failed in ubuntu14.04.

### ISSUE THREAD

**Issue by sunyuan3** [alibaba/pouch#372]
**Issue Description**
CI is failed in ubuntu14.04.

**Describe what happened**:
root@p1:~/pouch/test# go test
# _/root/pouch/test
./pouch_cli_create_test.go:25:47: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to command.PouchRun("pull", busyboxImage).Assert
./pouch_cli_create_test.go:38:12: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to res.Assert
./pouch_cli_create_test.go:49:12: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to res.Assert
./pouch_cli_create_test.go:64:12: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to res.Assert
./pouch_cli_create_test.go:72:12: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to res.Assert
./pouch_cli_create_test.go:80:12: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to res.Assert
./pouch_cli_images_test.go:26:47: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to command.PouchRun("pull", busyboxImage).Assert
./pouch_cli_images_test.go:36:43: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to command.PouchRun("images").Assert
./pouch_cli_images_test.go:44:50: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to command.PouchRun("images", "-q").Assert
./pouch_cli_images_test.go:45:59: cannot use "github.com/gotestyourself/gotestyourself/icmd".Success (type "github.com/gotestyourself/gotestyourself/icmd".Expected) as type "github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd".Expected in argument to command.PouchRun("images", "--quiet").Assert
./pouch_cli_images_test.go:45:59: too many errors
FAIL	_/root/pouch/test [build failed]

**Describe what you expected to happen**:
No error

**How to reproduce it (as minimally and precisely as possible)**:
1.git clone https://github.com/alibaba/pouch.git
2.cd pouch/test
3.go test

**Anything else we need to know?**:
0x04C2

**Environment**:
- pouch version (use `pouch version`):
APIVersion:      1.24
Arch:            amd64
BuildTime:       2017-12-21T12:04:25.700250747+08:00
GitCommit:
GoVersion:       go1.9.1
KernelVersion:
Os:              linux
Version:         0.1.0-dev

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

- Kernel (e.g. `uname -a`):
Linux p1 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
root@p1:~/pouch# go version
go version go1.9.1 linux/amd64

- Others:

**Comment by sunyuan3** [comment]
ping @0x04C2

**Comment by 0x04C2** [comment]
CheckIng

**Comment by 0x04C2** [comment]
@sunyuan3 ， would you provide the `go env` information? It seems the `gopath` and the vendor is not correct.

**Comment by sunyuan3** [comment]
My gopath environment is not right. I have corrected this issue. Thank you, @0x04C2 .
