### ISSUE TITLE
[feature required] pouch  create should support create container using Image ID

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#374]
**Issue Description**

**Describe what happened**:
Create container using image id failed. And the error message should also be changed
```
#pouch images
IMAGE ID       IMAGE NAME                                       SIZE
68effe31a4ae   reg.docker.alibaba-inc.com/base/busybox:latest   686.62 KB

#pouch create 68effe31a4ae top
Error: failed to create container: {"message":"image: 68effe31a4ae:latest: not found"}
```
**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I set this as a P2 priority. We will make it in the future. And we welcome other contributors to try this. 🌹 🌞

**Comment by 0x04C2** [comment]
good catch!

**Comment by allencloud** [comment]
> Now the daemon side is supported to create container with image's id. I think we don't need to support it in the "cli". from @skoo87  in #402 

/cc @Letty5411

**Comment by Letty5411** [comment]
Close it as it has been fixed:
```
#pouch images
IMAGE ID       IMAGE NAME                                       SIZE
58af67620523   registry.hub.docker.com/library/busybox:latest   710.83 KB

#pouch run 58af67620523 echo xxx
xxx
```
