### ISSUE TITLE
[bug] pouch exec stuck

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#377]
**Issue Description**
i create a container and start it. but when i execute `pouch exec -i test`, the command stuck, and can not do nothing
```
[root@docker-registry github.com]# pouch start test
[root@docker-registry github.com]# pouch ps
Name   ID       Status    Image                                            Runtime   Created
test   12da7a   running   registry.hub.docker.com/library/busybox:latest   runc      about 17521 days ago
[root@docker-registry github.com]# pouch exec -i test sh
```

but i can do `pouch start -i test`
```
[root@docker-registry github.com]# pouch stop test
[root@docker-registry github.com]# pouch start -i test
/ #
```

another problem: maybe we should not stop container, when execute `exit` in container
```
[root@docker-registry github.com]# pouch start -i test
/ # exit
[root@docker-registry github.com]# pouch ps
Name   ID       Status    Image                                            Runtime   Created
test   12da7a   stopped   registry.hub.docker.com/library/busybox:latest   runc      about 17521 days ago
```

**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by 0x04C2** [comment]
Hi @HusterWan , I think `-i` is only used keep stdin open, but there is no stdout to show the content. The docker has the same problem but we can type something which docker can echo. 

pouch need to improve this. On more thing, it still need signal receive. :)

**Comment by skoo87** [comment]
./pouch exec -i a70c6e sh
OCI runtime exec failed: exec failed: container_linux.go:295: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown   

Now，there is a error message  @HusterWan

**Comment by allencloud** [comment]
>  On more thing, it still need signal receive.

Yes, we miss this. @0x04C2

**Comment by HusterWan** [comment]
Hi @skoo87 , it seems to still has this problem, when i execute exec command by using a not exists command 
```
[root@docker-registry github.com]# pouch exec -it 2c96d0 bash
Killed
[root@docker-registry github.com]# pouch ps
Name     ID       Status    Image                                            Runtime   Created
2c96d0   2c96d0   running   registry.hub.docker.com/library/busybox:latest   runc      1 minute ago
d5c803   d5c803   created   registry.hub.docker.com/library/busybox:latest   runc      4 minutes ago
[root@docker-registry github.com]# pouch exec -it 2c96d0 sh
/ #
```

**Comment by allencloud** [comment]
Reopen this as it seems no fixed.
