### ISSUE TITLE
[question] should we update requirement for developer guide?

### ISSUE THREAD

**Issue by fuweid** [alibaba/pouch#389]
**Issue Description**

As the issue #205 and https://github.com/containerd/containerd/issues/1883 mentioned, I think the kernel version should be 4.x. Lower version maybe cause unexpected issue.

ref: https://github.com/containerd/containerd#runtime-requirements

**Describe what happened**:

For #205, if the kernel is lower than 3.18, the kernel doesn't have the overlayfs. 
The `pouch create` command will fail.

**Describe what you expected to happen**:

Should no error for normal usage.

**How to reproduce it (as minimally and precisely as possible)**:

I use vagrant ubuntu/trusty64 whose kernel is 3.14 and reproduce #205 issue.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Yes, I think we need to update this. User always comes first, you know.
