### ISSUE TITLE
[enhancement request] CRI manager to integrate pouch with kubernetes

### ISSUE THREAD

**Issue by YaoZengzeng** [alibaba/pouch#420]
## What is the scope of CRI manager
* GRPC server : connect to kubelet and receive CRI requests

* API transform : use pouch's container & image manager to handle all kinds of CRI requests

* Pod support : pod's lifecycle and metadata store

* CNI integration: the network of containers which belong to kubernetes should be managed by CNI other than the pouch's network manager

## What is not in the scope of CRI manager
* CRI manager should never interact directly with containerd. It is the job of pouch's container & image manager to implement all the details of containers & images processing

* All metadata, except for the sandbox should not be managed by CRI manager

The above is the coarse-grained division of CRI manager's scope, we may have to refine it in the future. And the next part of this issue is used to track the progress of CRI manager.

### Basic framework
- [x] [P0]Skeleton of CRI manager #426 

### Lifecycle
- [x] Sandbox Management
   - [x] [P0]RunPodSandbox #455 
   - [x] [P0]StopPodSandbox #561 
   - [x] [P0]RemovePodSandbox #561 
   - [x] [P0] ListPodSandbox #551 
   - [x] [P0] PodSandboxStatus #573 

- [x] Container Management
   - [x] [P0] CreateContainer #487 
   - [x] [P0] StartContainer #487 
   - [x] [P0] StopContainer #527 
   - [x] [P0] RemoveContainer #527 
   - [x] [P0] ListContainers #527 
   - [x] [P0] ContainerStatus #573 

- [x] Image Management
   - [x] [P0] ListImages #477 
   - [x] [P0] PullImages #477 
   - [x] [P0] RemoveImages #496 
   - [x] [P0] ImageStatus #496 
   - [x] [P2] ImageFsInfo

### Others
- [x] Network
   - [x] [P1] Integrate CNI plugin #580 

- [x] Streaming
   - [x] [P0] ExecSync #629 
   - [x] [P2] Exec #797 
   - [x] [P2] Attach #797 
   - [x] [P2] PortForward #816

- [x] [P2] Logging #928 

cc @skoo87 @allencloud

**Comment by WIZARD-CXY** [comment]
Let me take a closer look at it

**Comment by WIZARD-CXY** [comment]
lgtm

**Comment by allencloud** [comment]
Hi, @xiang90 ,
Could you help to review this for us as an expert on Kubernetes? More details about architecture, maybe you can refer to https://github.com/alibaba/pouch/blob/master/docs/architecture.md#component-architecture.
And Please feel free to share with us if you find any thoughtlessness we brought. Thanks a lot. 🍻

**Comment by allencloud** [comment]
Have we finished the final one `ImageFsInfo` ? @YaoZengzeng @Starnop 
Just keep track of this.

**Comment by YaoZengzeng** [comment]
All tasks have been finished, close now.
