### ISSUE TITLE
[feature request] support container options, such as isolation and configurations

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#463]
**Issue Description**

Currently we have implemented container technology in pouch, while I think the specific functionality is not so sufficient, such as container isolation and container configuration support are still none. 

In our v0.1 milestone, some main container config options need implemented:

### ContainerConfig

@skoo87 will handle ContainerConfig.

- [x] Cmd
- [x] Entrypoint
- [x] Env
- [x] Hostname
- [x] Image
- [x] Labels
- [x] User
- [x] Volumes
- [x] WorkingDir

### HostConfig
- [x] AutoRemove
- [x] Binds
- [x] CpuShares      
- [x] CpusetCpus    
- [x] Device : https://github.com/alibaba/pouch/pull/514 by @HusterWan 
  - [x] CgroupPermissions
  - [x] PathInContainer
  - [x] PathOnHost
- [ ] LogConfig
  - [ ] Config
  - [ ] Type
- [x] Memory                        
- [x] MemorySwap                
- [x] MemorySwappiness    
- [x] NetworkMode @rudyfly 
- [x] RestartPolicy    @skoo 
- [x] Runtime
- [ ] VolumesFrom  @rudyfly 
- [x] OomScoreAdj https://github.com/alibaba/pouch/pull/934

**Describe what happened**:
Pouch does not support sufficient container configs.

**Describe what you expected to happen**:
Pouch supports essential container configs.

**Anything else we need to know?**:
NONE

**Environment**:
- pouch version (use `pouch version`): 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by WIZARD-CXY** [comment]
we also need device configuration because some containers will use fpga, gpu devices.

**Comment by allencloud** [comment]
I have updated the issue description. And it is already in HostConfig. @WIZARD-CXY

**Comment by HusterWan** [comment]
maybe we also need block io configuration like device_read_bps, device_write_bps, device_read_iops, device_write_iops. @allencloud

**Comment by allencloud** [comment]
Yes, We will add that. In the original plan, it is in the scope of 0.2 milestone. While if we have enough time, we can add them totally. @HusterWan

**Comment by allencloud** [comment]
@HusterWan 
Could you help to implement the following options in HostConfig: 
- [ ] Device
  - [ ] CgroupPermissions
  - [ ] PathInContainer
  - [ ] PathOnHost
And feel free to share with us if you met any issues.

**Comment by HusterWan** [comment]
OK，i will do it @allencloud

**Comment by 0x04C2** [comment]
@allencloud , I will take the following options in HostConfig:

- [ ] Memory
- [ ] MemorySwap
- [ ] MemorySwappiness

**Comment by HusterWan** [comment]
@allencloud @skoo87 i have no permission to edit this page
