### ISSUE TITLE
[bug report]make test command must run as root 

### ISSUE THREAD

**Issue by purplegrape** [alibaba/pouch#466]
**Issue Description**
pouch can build by normal user but “make test” command must run as root 

**Describe what happened**:

+ make test
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.login as normal user
2.run make
3. run make test

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
@Letty5411 @sunyuan3 Please take a look at this. Thanks.

**Comment by 0x04C2** [comment]
@purplegrape ,  `make build` is running on `go` command. Therefore, the user, who has `go` in PATH, can run `make build` command without root.

But for your report, the `make test` command needs to build env for test by docker cmd. It seems that the user aren't in `docker` group in your system. Ref is [here](https://docs.docker.com/engine/installation/linux/linux-postinstall/). Hope it can help.

After that, `make test` will run `pouchd` in background for integration-test. I think there is some safety reason that `pouchd` need to run by root user. So, I guess that `make test` requires `root`. Maybe we can add the comment on the target to clarify the case. For example, the check doesn't require the root mode but the `integration-test` does.

cc @allencloud, @Letty5411 and @sunyuan3

**Comment by sunyuan3** [comment]
Nice catch. I will create a patch.

**Comment by sunyuan3** [comment]
"make test" means that "env PATH=$(PATH) hack/make.sh check build integration-test" is executed. Check and build don't need root privilege.  In integration test, pouchd and $DIR/test/integration-test binary need root privilege.

In travis config, sudo is already added to make test.
https://github.com/alibaba/pouch/blob/master/.travis.yml

0x04C2 and I have answered the question. I would close this issue. If you still have question, you can reopen it.
