### ISSUE TITLE
[feature request] how to provide a grpc API test framework

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#474]
**Issue Description**

We have started the CRI implementation plan in Pouch. And in the previous PRs https://github.com/alibaba/pouch/pull/426 and https://github.com/alibaba/pouch/pull/455 we have initially make pod sandbox creation work.

As the developing work goes on, we still need to finish the CRI test work. Currently we need to add two parts of CRI test type:

* unit test in added CRI related codes;
* integration test for CRI API which is based on grpc.

In the future, after release of pouch's 1.0 version, we need to add performance test and stablility test and other aspects of testing.

So, right now, we should improve the priority of API integration test  for CRI grpc server. Since when we start a pouch daemon, it also listens to a port which is reserved for grpc, we can add grpc integration test cases directly in /test.

Here we need to add a grpc test framework for grpc and add test cases for API. I think we had better make test case addition easily like HTTP API test case's we have done right now.

/cc @Letty5411 @YaoZengzeng 

**Describe what happened**:
No CRI grpc test added.

**Describe what you expected to happen**:
Finish unit test in CRI related code and provide a grpc test framework to add API integration test.

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
We will consider use https://github.com/kubernetes-incubator/cri-tools as integration test tools. But here I have concern if it is suitable for an initial project like pouch which just finishes a little part of CRI implementation.  @Letty5411 @YaoZengzeng @skoo87

**Comment by YaoZengzeng** [comment]
@allencloud Maybe we can use option "--focus" to limit the scope of test.

https://github.com/kubernetes-incubator/cri-tools/blob/master/docs/validation.md
