### ISSUE TITLE
[Proposal] runv support user defined kernel version 

### ISSUE THREAD

**Issue by Ace-Tang** [alibaba/pouch#475]
pouch now support hyper runv,  beside this, we can privide a general solution which can support user to use their own kernel verson.

we offer some scripts and prepared image file for qemu, user may provide a kernel code as input, a kernel and a img will as output which can apply to runv.

**Comment by allencloud** [comment]
I think this has been done by @Ace-Tang and Haoyu. However, it is not so easy to open source this part. And this part is included in pr https://github.com/alibaba/pouch/pull/1442.

**Comment by Ace-Tang** [comment]
Close this, since we update to use kata, we will do new work on kata.
