### ISSUE TITLE
[enhancement required] cli/network needs to handle CMD flags

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#478]
**Issue Description**
**Describe what happened**:
Now CMD `pouch network create` supports several flags, but only `name` and `driver` are handled.
cli/network.go needs to handle this.

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rudyfly** [comment]
I have completed these jobs.
