### ISSUE TITLE
[bug] API interface /networks delete doesn't exist in apis/swagger.yml 

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#479]
**Issue Description**
**Describe what happened**:
From the apis/server/router.go, delete network API has been implemented, but no entry is found in swagger.yml. Need to add it.
```
r.Path("/networks/{id:.*}").Methods(http.MethodDelete).Handler(s.filter(s.deleteNetwork))
```
**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Yes, and actually daemon side has not implemented this API, see : 
```
func (s *Server) deleteNetwork(ctx context.Context, resp http.ResponseWriter, req *http.Request) error {
	return nil
}
```

And I will add this API in swagger.yml ASAP today.

**Comment by allencloud** [comment]
Oh, no. I will add  `GET /networks/{id}` first.
