### ISSUE TITLE
[feature request] pouch run in terminal default connects to container's stdout

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#491]
**Issue Description**

I tries the command: 

```
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch run -e aaaa=bbbb registry.hub.docker.com/library/busybox:latest env
babd75467bec7a8764e7931f08165cad2fab42ef6b0820a20ff15d22e4c745d4
root@ubuntu:~/go/src/github.com/alibaba/pouch#
```

I found that the terminal shows the created container and stops flush. Actually, I wish the terminal in which command `pouch run` runs could connects to the running container's stdout and stderr(at least stdout).  @HusterWan 

**Describe what happened**:
```
root@ubuntu:~/go/src/github.com/alibaba/pouch# pouch run -e aaaa=bbbb registry.hub.docker.com/library/busybox:latest env
96648a963a7fdb068ae1b5365c266fa4879581012eaa5fa6e4aed5281774ed1f
root@ubuntu:~/go/src/github.com/alibaba/pouch#
```

**Describe what you expected to happen**:
pouch run in terminal default connects to container's stdout

**How to reproduce it (as minimally and precisely as possible)**:
1. execute `pouch run -e aaaa=bbbb registry.hub.docker.com/library/busybox:latest env`
2. see output
3.

**Anything else we need to know?**:
none

**Environment**:
- pouch version (use `pouch version`): 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HusterWan** [comment]
Yes, the run command default not connect to container's stdout, i will support it soon. @allencloud
