### ISSUE TITLE
[suggestion] change default containerd socket path as official do

### ISSUE THREAD

**Issue by purplegrape** [alibaba/pouch#518]
**Issue Description**
pouch's default containerd socket path is /var/run/containerd.sock
containerd official default socket path is /run/containerd/containerd.sock

**Describe what happened**:
# pouchd --help |grep "/var/run/containerd.sock"
  -c, --containerd string          Specify listening address of containerd (default "/var/run/containerd.sock")
# containerd config default
root = "/var/lib/containerd"
state = "/run/containerd"
no_subreaper = false
oom_score = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0

[debug]
  address = "/run/containerd/debug.sock"
  uid = 0
  gid = 0
  level = "info"

[metrics]
  address = ""

[cgroup]
  path = ""

**Describe what you expected to happen**:
change default containerd socket path as official do

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by skoo87** [comment]
What is the reason for using the containerd's officail socket path ????

**Comment by purplegrape** [comment]
why not

**Comment by allencloud** [comment]
I do not think we have enough reason to make a change. Closing this now and feel free to reopen this if we think there are more things needed discussed. Thanks a lot for you suggestion. @purplegrape
