### ISSUE TITLE
[feature request] pouch need a config file

### ISSUE THREAD

**Issue by Ace-Tang** [alibaba/pouch#526]
**Issue Description**

how about make pouchd  to read parameters from a config file,  then pouchd can simply start by just like
```
pouch --config=/etc/pouch/pouch.json
```
and it will be better to remove `--containerd-config` in pouchd, it will be in next step.

if we do this, I want know:
- which type of config is better, json or toml

**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Actually I think I prefer json file. @Ace-Tang

**Comment by Ace-Tang** [comment]
#576 fix this.
