### ISSUE TITLE
https://github.com/alibaba/pouch/blob/master/cli/pull.go#L38  should be: "Args: cobra.ExactArgs (1),"

### ISSUE THREAD

**Issue by DarkForcesX** [alibaba/pouch#554]
**Issue Description**
https://github.com/alibaba/pouch/blob/master/cli/pull.go#L38
This line of code has a bug and should be: "Args: cobra.ExactArgs (1),"

**Describe what happened**:
“Args:  cobra.MinimumNArgs(1),”

**Describe what you expected to happen**:
“Args:  cobra.ExactArgs(1),”

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Yes, I agree with you, it is a bug in Pouch.
