### ISSUE TITLE
[ question ]why fork a containerd subprocess by pouchd

### ISSUE THREAD

**Issue by purplegrape** [alibaba/pouch#556]
**Issue Description**

in my opinion，containerd and pouchd are diffenrent software，both are not any part of  the other。

obviously，containerd is an upstream project 

pouchd now seems running as a monitor of containerd

why not make an error instead when containerd‘s socket is not avaliable ？

**Comment by allencloud** [comment]
Thanks for your feedback. @purplegrape 
Container is a daemon process which is focused on underlying containers. While pouchd is a container engine which is much more friendly to users. Pouchd provides best practice on containers to users and CRI implementation for Kubernetes eco-system.

Maybe pouchd did some monitoring thing for container, indeed. While I do not think that is all of pouchd for a perspective from users.

> why not make an error instead when containerd‘s socket is not avaliable 

Actually I cannot quite follow you with more context. Could you share a little bit more on the context? Thanks a lot.

**Comment by purplegrape** [comment]
thank @allencloud .

in fact,i'm trying to package both containerd and pouchd, and have wroten seperate systemd startup script. you know,this may have trouble, 

so i think pouchd should run after containerd as it' dependence in the local linux box.

**Comment by allencloud** [comment]
I think both are OK. For pouch, we wish to provide an out-of-box solution for users, so we try to make pouchd to start containerd there. If we do this, users could feel no existence of containerd, but pouchd takes over everything. 

And I try to find how docker does, and I found that it seems that docker does the same way. In addition, although pouch is another container engine yet, we pay more attention to keeping consistent with moby. @purplegrape

**Comment by purplegrape** [comment]
thanks . I think this question can be closed now.
