### ISSUE TITLE
[bug] test CI should clean docker when finished

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#566]
**Issue Description**
Now pouch CI using Dockerfile to unify test environment and check/build/unit-test are running in docker. There are legacy docker when test finished.
Code is in :  hack/make.sh
```
function target()
{
        case $1 in
        check)
                docker run -ti -v $(pwd):$SOURCEDIR $IMAGE bash -c "make check"
                ;;
        build)
                docker run -ti -v $(pwd):$SOURCEDIR $IMAGE bash -c "make build"
                install_pouch
                ;;
        unit-test)
                docker run -ti -v $(pwd):$SOURCEDIR $IMAGE bash -c "make unit-test"
                ;;
        integration-test)
                docker run -ti -v $(pwd):$SOURCEDIR $IMAGE bash -c "cd test && go test -c -o integration-test"
```

Should user `docker run --rm`  to remove docker container.
**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sunyuan3** [comment]
Nice catch.
