### ISSUE TITLE
[feature required] investigate whether to include lxcfs in pouch RPM

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#574]
**Issue Description**
In CentOS, you need to install lxcfs from source code.
Could we put lxcfs in pouch RPM? We need to investigate it.

Here are steps about how to install lxcfs on CentOS: https://github.com/Letty5411/letty-work/blob/master/pouch/Install_lxcfs.md
**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
cc @CodeJuan PTAL to provide more details which may be helpful.

**Comment by allencloud** [comment]
I think this has been done by @zzchun . Right? If not, please let me know.
I am closing this.
