### ISSUE TITLE
[bug] TestImageCreateWithoutTag random failed on CentOS

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#583]
**Issue Description**
This test failed randomly on CentOS.
It may be caused by the `pouch pull` returns while the image has not been downloaded.
Need to find whether it is a bug of the test or product.

**Describe what happened**:
```
START: api_image_create_test.go:56: APIImageCreateSuite.TestImageCreateWithoutTag
START: api_image_create_test.go:21: APIImageCreateSuite.SetUpTest
PASS: api_image_create_test.go:21: APIImageCreateSuite.SetUpTest	0.000s

api_image_create_test.go:66:
    CheckRespStatus(c, resp, 204)
utils.go:134:
    c.Assert(resp.StatusCode, check.Equals, status, check.Commentf("Error:%s", got.Message))
... obtained int = 404
... expected int = 204
... Error:image: registry.hub.docker.com/library/hello-world:latest: not found

FAIL: api_image_create_test.go:56: APIImageCreateSuite.TestImageCreateWithoutTag
```
**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Is dockerhub unstable? So that this API returns 404. Could you test another image on DockerHub, or another image on another image registry? @Letty5411
