### ISSUE TITLE
[question]How does Pouch's rich container works?

### ISSUE THREAD

**Issue by zhaonanyu** [alibaba/pouch#584]
**Issue Description**
I'm pretty interested in Pouch's rich container, but I can't find any detailed instruction about it either in this repo's doc nor on the internet, so my questions are:
1. The implementation of the Pouch Rich Container
2. Scenarios that Pouch's rich container fit in
3. Limitation of Pouch's rich container while using it

**Comment by purplegrape** [comment]
rich container means system container, while docker is application container .

system container can be considered as  non-classic VM, which replaced hardware emulation by new  technology (  cgroup, namespace  and uid/gid mappig  )

pouch is a golang version of enhanced LXC via more features .

**Comment by yyb196** [comment]
rich container is about starting a supervisor process in container automatically and then start user defined entrypoint+cmd via this supervisor process. inside container supervisor process will also start other predefined service which can be customized in base image.

we usually start a systemd in container as supervisor, which will start sshd and crond and then start entrypoint+cmd that specified in image or by user, and when user ssh to a running contianer, he can use systemctl status crond just as in a vm.

starting a systemd in container requires some modification in runc and requires kernel feature cgroupnamespace which introduce in 4.9. to top it of we should ensure that /sys/fs/cgroup/systemd is mounted rw in container, which makes systemd in container start normally, but that may incurs some security problems, so rich container is suggested only used in none multi-tenant environment.

**Comment by allencloud** [comment]
@zhaonanyu 
Does what @yyb196 said satisfy you?

And maybe we need to add a documentation in this repo. Since lots of people may have confusion on this. @yyb196

**Comment by zhaonanyu** [comment]
@allencloud I've no more questions at the moment, thx a lot folks.
