### ISSUE TITLE
[feature request] support context in client package between client and daemon side

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#62]
**Issue Description**

Currently, I found that in package client there is no context guaranteed. So if some special config in client side cannot be transferred to daemon side beyond RESTful APIs. In addition, context binding can make daemon side know the interrupt of client side. For example, within a time-costing request from client to daemon, if user interrupt this request in client side, the better way to act to this in daemon side is getting aware of this action and stopped the following work. And this will avoid some unnecessary cost in daemon side and be consistent with the client side. 

This can be done within built-in package `context` in golang runtime.

Since you did a lot of work in client package, would you help to solve this?
While I would set this as a mid-term target with priority/p2.

**Comment by MikeLing** [comment]
Hi, I'm new to pouch but I really want to take this issue and work on it. Could you assign this issue to me, please? Thanks a lot! :)

**Comment by MikeLing** [comment]
#dibs

**Comment by allencloud** [comment]
Any update on this? @MikeLing

**Comment by allencloud** [comment]
I think client side has implemented context in https://github.com/alibaba/pouch/pull/738.

**Comment by Ace-Tang** [comment]
can we close this

**Comment by allencloud** [comment]
I think we can close this.
