### ISSUE TITLE
[doc] typo in architecture.md

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#621]
**Issue Description**
The following line last word, should be `containerd`?
`ctrd is containerd client in Pouchd. When managers need to communicate with container`
**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Letty5411** [comment]
@allencloud

**Comment by allencloud** [comment]
yes, what you mentioned is totally right. I will fix this. @Letty5411
