### ISSUE TITLE
[feature request] add UPDATE command for container

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#631]
**Issue Description**

Pouch has not implemented `pouch update container_name`, while this command is very useful to modify the config of the container.

In this place we wish to support the following update configurations:

``` go
// UpdateConfig holds the mutable attributes of a Container.
// Those attributes can be updated at runtime.
type UpdateConfig struct {
	// Contains container's resources (cgroups, ulimits)
	Resources
	RestartPolicy RestartPolicy
	ImageID       string
	Env           []string
	Label         []string
	DiskQuota     string
}
```

**Describe what happened**:
no update command in pouch's master.

**Describe what you expected to happen**:
implement pouch update command.

**How to reproduce it (as minimally and precisely as possible)**:
none

**Anything else we need to know?**:
none

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I think this is very important. Do you have any thoughts on this? @HusterWan

**Comment by HusterWan** [comment]
Yes, update a container's cpu and memory on runtime is a very useful function in production environment, i will do it. @allencloud

**Comment by allencloud** [comment]
Do you need any help on this functionality implementation?  @HusterWan 😃 🍺

**Comment by HusterWan** [comment]
Last week, i was busy doing other works.
I will finish this feature this week @allencloud

**Comment by allencloud** [comment]
Any Update on this ? 😸 🦁  @HusterWan
