### ISSUE TITLE
[bug]TestRunEnableLxcfs test failed

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#669]
**Issue Description**
Test failed on AliOS4.9: 
commit: 25c95076fab3080a13f0295d043319b253342a9c

```
12:48:10 ----------------------------------------------------------------------
12:48:10 FAIL: /go/src/github.com/alibaba/pouch/test/cli_run_test.go:162: PouchRunSuite.TestRunEnableLxcfs
12:48:10 
12:48:10 /go/src/github.com/alibaba/pouch/test/cli_run_test.go:166:
12:48:10     res.Assert(c, icmd.Success)
12:48:10 /go/src/github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd/command.go:61:
12:48:10     t.Fatalf("at %s:%d - %s\n", filepath.Base(file), line, err.Error())
12:48:10 ... Error: at cli_run_test.go:166 - 
12:48:10 Command:  /usr/local/bin/pouch run --name test-run-lxcfs -m 512M --enableLxcfs=true registry.hub.docker.com/library/busybox:latest head -n 1 /proc/meminfo
12:48:10 ExitCode: 1
12:48:10 Error:    exit status 1
12:48:10 Stdout:   
12:48:10 Stderr:   Error: failed to run container test-run-lxcfs: {"message":"failed to create task, container id: 8c5b808ebcfb82d29fc6b6751e659f2d7a5c1de3e7a324828f2c8a71b73b6cfc: OCI runtime create failed: container_linux.go:265: starting container process caused \"process_linux.go:348: container init caused \\\"rootfs_linux.go:57: mounting \\\\\\\"/var/lib/lxc/lxcfs/proc/uptime\\\\\\\" to rootfs \\\\\\\"/var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/8c5b808ebcfb82d29fc6b6751e659f2d7a5c1de3e7a324828f2c8a71b73b6cfc/rootfs\\\\\\\" at \\\\\\\"/proc/uptime\\\\\\\" caused \\\\\\\"stat /var/lib/lxc/lxcfs/proc/uptime: transport endpoint is not connected\\\\\\\"\\\"\": unknown"}
12:48:10 
12:48:10 
12:48:10 
12:48:10 Failures:
12:48:10 ExitCode was 1 expected 0
12:48:10 Expected no error
```
**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
`Error: failed to run container test-run-lxcfs: {"message":"failed to create task, container id: 8c5b808ebcfb82d29fc6b6751e659f2d7a5c1de3e7a324828f2c8a71b73b6cfc: OCI runtime create failed: container_linux.go:265: starting container process caused \"process_linux.go:348: container init caused \\\"rootfs_linux.go:57: mounting \\\\\\\"/var/lib/lxc/lxcfs/proc/uptime\\\\\\\" to rootfs \\\\\\\"/var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/8c5b808ebcfb82d29fc6b6751e659f2d7a5c1de3e7a324828f2c8a71b73b6cfc/rootfs\\\\\\\" at \\\\\\\"/proc/uptime\\\\\\\" caused \\\\\\\"stat /var/lib/lxc/lxcfs/proc/uptime: transport endpoint is not connected\\\\\\\"\\\"\": unknown"}`

The real error is ` transport endpoint is not connected`.

And I think link https://stackoverflow.com/questions/24966676/transport-endpoint-is-not-connected can give us some guide.

**Comment by allencloud** [comment]
This issue is similar to https://github.com/alibaba/pouch/issues/788. Closing this one.
