### ISSUE TITLE
[bug] hack/make.sh judge pouchd started not accurate

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#670]
**Issue Description**
In hack/make.sh, it uses the existence of `/var/run/pouchd.sock` to check if the 
pouch daemon started successfully, this does not always work.
We could use `pouch version` instead.
**Describe what happened**:

```
		do
			if [[ -S /var/run/pouchd.sock ]];then
				echo "Succeed to start pouch daemon"
				break
			elif (( $((daemon_timeout_time--)) == 0 ));then
				echo "Failed to start pouch daemon"
				echo "pouch daemon log:"
				cat $TMP/log 
				return 1
			else
				sleep 1
			fi
		done
```
**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sunyuan3** [comment]
Which OS doesn't "/var/run/pouchd.sock" work well? Ubuntu or Centos?

**Comment by Letty5411** [comment]
fixed
