### ISSUE TITLE
[feature request] compatible network create operation 

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#679]
**Issue Description**

Currently we implemented container network functionality, but here when we need to create a container with network mode `bridge`, user has to execute command like `pouch run --net bridge:172.17.0.10 image_name`. If user does not specify `--net bridge:172.17.0.10`, he creates a container without network at all. I do not think this is user-friendly.

Maybe we should consider that by default pouch creates a container with bridge network mode. In another word, `pouch run image_name` would create a container with bridge network.

To be more detailed, we can implement this in the daemon side, if the container creation options have empty value in request body, we could set this as bridge. So this is daemon side bridge by default. Although we can set this in CLI side, but some user may still use pure HTTP request to do this, if we only do this in CLI side, daemon side will not do the bridge thing if user requests container creation with empty network mode.

WDYT? @rudyfly 

**Describe what happened**:

user has to execute command like `pouch run --net bridge:172.17.0.10 image_name` to create container with bridge network mode.

**Describe what you expected to happen**:

Maybe we should consider that by default pouch creates a container with bridge network mode

**How to reproduce it (as minimally and precisely as possible)**:
NONE

**Anything else we need to know?**:
NONE

**Environment**:
- pouch version (use `pouch version`): dev-master
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Could you give some details about how is it going with this issue?
If this has been fixed, please feel free to close this. Thanks a lot. @rudyfly

**Comment by rudyfly** [comment]
Have fixed, so close it.
