### ISSUE TITLE
[feature request] need repoTags and repoDigests fields in ImageInfo.

### ISSUE THREAD

**Issue by zeppp** [alibaba/pouch#696]
### Ⅰ. Issue Description
To keep consistency with Moby and implement cri methods, we need add `repoTags` and `repoDigests` fields to `ImageInfo` and remove the `name` field in `ImageInfo` correspondingly.

**Comment by allencloud** [comment]
I think this has been fixed in https://github.com/alibaba/pouch/pull/721. Closing this.
