### ISSUE TITLE
[enhance] the output of pouch volume create could be enhanced

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#702]
### Ⅰ. Issue Description
When using `pouch volume create` with `mount` option, the output of create is not readable.

### Ⅱ. Describe what happened

```
#pouch volume create -d local  -o mount=/tmp -n test
CreatedAt:
Driver:       local
Mountpoint:
Name:         test
Scope:

#pouch volume list
Name:
b2f197657d8fb9e03b4db314654449fee45328992e179cff2b94bfdd6e8b67d4
cb4b391c5d1b560c1d613658c53d16d60fdfd74c1ec198d43612ec9ee16e61a5
pouch-volume
test

[root@10.218.145.76 /home/sit/letty/src/github.com/alibaba/pouch]
#pouch volume inspect test
CreatedAt:    2018-2-6 11:08:50
Driver:       local
Mountpoint:   /tmp/test
Name:         test
Scope:
```
### Ⅲ. Describe what you expected to happen

Should also print the right mountpoint info.
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rudyfly** [comment]
Completed.
