### ISSUE TITLE
[bug] pouch volume create failed, but metadata is stored

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#703]
### Ⅰ. Issue Description
Create a volume failed, but `pouch volume list` could get the volume name.

### Ⅱ. Describe what happened

```
#touch /tmp/test6

#pouch volume create -d local  -o mount=/tmp -n test6
Error: {"message":"mount path is not a dir /tmp/test6"}


#echo $?
1

#pouch volume list
Name:
b2f197657d8fb9e03b4db314654449fee45328992e179cff2b94bfdd6e8b67d4
cb4b391c5d1b560c1d613658c53d16d60fdfd74c1ec198d43612ec9ee16e61a5
pouch-volume
test
test2
test3
test4
test5
test6

```
### Ⅲ. Describe what you expected to happen
`pouch list` should not contains `test6`

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Is this fixed in master? @rudyfly 
If the answer is yes, please close this one. Thanks a lot.
