### ISSUE TITLE
make extra/libnetwork submodule as vendor dependency

### ISSUE THREAD

**Issue by zhouhaibing089** [alibaba/pouch#750]
It is not clear on why `extra/libnetwork` has to be a submodule instead of sitting in `vendor/github.com/docker/libnetwork/`?

The situation now is, the navigation sometimes breaks as the editor can not find the 
 import `github.com/docker/libnetwork`(which is bad when browsing the codebase).

Hopefully there should be an easy to fix unless it is a real **have to**.

**Comment by allencloud** [comment]
We had a reason. @zhouhaibing089 
/cc @rudyfly Could you explain this for this.

**Comment by rudyfly** [comment]
@zhouhaibing089 we use libnetwork's version is 1.12.6, that libnetwork's version have depended some old base packages, such as: github.com/Sirupsen/logrus, but in pouchd, other package depend more newer packages, it conflicts when building. so we let the libnetwork into the independent GOPATH environment. Can you give me more suitable method?

**Comment by zhouhaibing089** [comment]
@rudyfly: I see, such conflicts will happen when `a` depends on `b:v1` and `c` depends on `b:v2`.

I have no better idea, and that is not my pain point anyway, so how about one of this:

*   Submodule to `vendor/github.com/libnetwork` rather than `extra/libnetwork`.
*   Fix the conflicts by choosing a compatible version of `b` for both `a` and `c` (long term but would be hard work).
