### ISSUE TITLE
[bug] the image size seems like not correct.

### ISSUE THREAD

**Issue by zeppp** [alibaba/pouch#752]
### Ⅰ. Issue Description
I found it is not normal that when I use pouch to pull image busybox:1 and busybox:1-uclibc. The size are different but it is the same and  bigger in docker . 
```
-># pouch images
IMAGE ID       IMAGE NAME                           SIZE
599d1d10a1d4   docker.io/library/busybox:1          710.74 KB
e8d07e9fab00   docker.io/library/busybox:1-uclibc   709.80 KB
```
```
-># docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
docker.io/busybox              1                   5b0d59026729        4 weeks ago         1.146 MB
docker.io/busybox              1-uclibc            5b0d59026729        4 weeks ago         1.146 MB
```

### Ⅲ. Describe what you expected to happen
The size of busybox:1 and busybox:1-uclibc should be same in pouch. And the size of image should be same within docker and pouch?

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:
pouch：
- pouch version (use `pouch version`):
GitCommit:       
GoVersion:       go1.9.1
KernelVersion:   
Os:              linux
Version:         0.1.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-02-23T22:38:20.046203766-08:00

- Kernel (e.g. `uname -a`):
Linux ubuntu 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

docker:
- docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64
Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Oct 24 15:40:21 2017
 OS/Arch:         linux/amd64

- Kernel (e.g. `uname -a`):
Linux izwz91u31rjw4d8ckl1zo6z 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zeppp** [comment]
In fact , it affects a little but still has a problem that these two images should share one storage location because they are same without tags. If their sizes are different , they will have different ID in pouch which we don't want to happen.
I have no idea about that, so I make this issue to look for help.  @allencloud

**Comment by allencloud** [comment]
I am wondering if pouchd still has this issue. I have no sense that we have already fixed. Could you help to confirm this? @fuweid

**Comment by fuweid** [comment]
@allencloud roger that

**Comment by allencloud** [comment]
Any update on this? @fuweid
