### ISSUE TITLE
[bug] install pouchd with the newest code failed

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#763]
### Ⅰ. Issue Description

```
wanziren@wanzirens-MacBook-Pro:~/Workspaces/go_workspace/src/github.com/alibaba/pouch|wanziren/add-update-command
⇒  make install
GOOS=linux go build -o pouchd
daemon/mgr/network.go:17:2: case-insensitive import collision: "github.com/alibaba/pouch/vendor/github.com/Sirupsen/logrus" and "github.com/alibaba/pouch/vendor/github.com/sirupsen/logrus"
make: *** [server] Error 1
```
### Ⅱ. Describe what happened
make install failed

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
```
⇒  uname -a
Darwin wanzirens-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```
- Install tools:
- Others:

**Comment by allencloud** [comment]
I think this issue is similar to https://github.com/alibaba/pouch/issues/750

**Comment by rudyfly** [comment]
mac system can not build pouch, you should use linux to build.

**Comment by HusterWan** [comment]
@rudyfly Thanks, i have figured it out, i will close this issure.
