### ISSUE TITLE
[bug] rich container can't run initscript

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#783]
### Ⅰ. Issue Description
When specify a shell script as initscript in rich container dumb-init mode, it returns error:
```
#pouch run -v /tmp/:/tmp/ --rich  --rich-mode dumb-init --initscript /tmp/1.sh registry.hub.docker.com/library/busybox:latest top
Error: failed to run container b22eef: {"message":"failed to create task, container id: b22eef942648e08d92523794de4ecee1527078ad557284a517b4cc6aee7a9292: OCI runtime create failed: container_linux.go:265: starting container process caused \"process_linux.go:348: container init caused \\\"process_linux.go:331: running prestart hook 1 caused \\\\\\\"fork/exec /tmp/1.sh: exec format error\\\\\\\"\\\"\": unknown"}


#cat /tmp/1.sh
ls /tmp/test
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yyb196** [comment]
the message "exec format error" indicates absent of shebang in init script file.

after add shebang in the init script, the error is that the init script actually executes on the host isn't in the container. 
eg:
```
#pouch run -v /tmp/:/tmp/ --rich  --rich-mode dumb-init --initscript /tmp/2.sh -d registry.hub.docker.com/library/busybox:latest top
bfa54bfd1d5686c2ee6ff14472693a98631d3b6a96d5769a103442256b33c2f1

[root@host /root]
#pouch exec -it bfa5 sh
/ # cat /tmp/2.sh
#! /bin/sh

touch /sl_test
/ # ls -l /sl_test
ls: /sl_test: No such file or directory
/ #
[root@host /root]
#ls -l /sl_test
-rw-r--r-- 1 root root 0 Feb 28 17:55 /sl_test
```

**Comment by Letty5411** [comment]
Please refer: https://github.com/wangforthinker/runcHook for the usage of intiscript

**Comment by wangforthinker** [comment]
Runc will send data of hookstate to stdin, so the initscript shoud process data from stdin.

**Comment by yyb196** [comment]
@wangforthinker if initscript is run on host machine by design, you should change the message in command help
```
--initscript string            Initial script executed in container
```
