### ISSUE TITLE
[bug] lxcfs test failed on centos7.2

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#788]
### Ⅰ. Issue Description
On pouch0.2.0, the following test failed:
```
----------------------------------------------------------------------
FAIL: cli_run_test.go:180: PouchRunSuite.TestRunEnableLxcfs

cli_run_test.go:184:
    res.Assert(c, icmd.Success)
/root/gocodes/src/github.com/alibaba/pouch/vendor/github.com/gotestyourself/gotestyourself/icmd/command.go:61:
    t.Fatalf("at %s:%d - %s\n", filepath.Base(file), line, err.Error())
... Error: at cli_run_test.go:184 -
Command:  /usr/local/bin/pouch run --name test-run-lxcfs -m 512M --enableLxcfs=true registry.hub.docker.com/library/busybox:latest head -n 1 /proc/meminfo
ExitCode: 1
Error:    exit status 1
Stdout:
Stderr:   Error: failed to run container test-run-lxcfs: {"message":"failed to create task, container id: 24341a8aa2863e10269a9ed759b5f51b36ffc81799ee7f30a3a403bd0217c731: OCI runtime create failed: container_linux.go:296: starting container process caused \"process_linux.go:398: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/lib/lxc/lxcfs/proc/uptime\\\\\\\" to rootfs \\\\\\\"/var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/24341a8aa2863e10269a9ed759b5f51b36ffc81799ee7f30a3a403bd0217c731/rootfs\\\\\\\" at \\\\\\\"/proc/uptime\\\\\\\" caused \\\\\\\"stat /var/lib/lxc/lxcfs/proc/uptime: transport endpoint is not connected\\\\\\\"\\\"\": unknown"}



Failures:
ExitCode was 1 expected 0
Expected no error
```
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
centOS
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux izj6c44nzox6sb97nzgmi0z 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by allencloud** [comment]
`Error: failed to run container test-run-lxcfs: {"message":"failed to create task, container id: 8c5b808ebcfb82d29fc6b6751e659f2d7a5c1de3e7a324828f2c8a71b73b6cfc: OCI runtime create failed: container_linux.go:265: starting container process caused \"process_linux.go:348: container init caused \\\"rootfs_linux.go:57: mounting \\\\\\\"/var/lib/lxc/lxcfs/proc/uptime\\\\\\\" to rootfs \\\\\\\"/var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/8c5b808ebcfb82d29fc6b6751e659f2d7a5c1de3e7a324828f2c8a71b73b6cfc/rootfs\\\\\\\" at \\\\\\\"/proc/uptime\\\\\\\" caused \\\\\\\"stat /var/lib/lxc/lxcfs/proc/uptime: transport endpoint is not connected\\\\\\\"\\\"\": unknown"}`

The real error is ` transport endpoint is not connected`.

And I think link https://stackoverflow.com/questions/24966676/transport-endpoint-is-not-connected can give us some guide.

**Comment by Letty5411** [comment]
Also exits on AliOS
