### ISSUE TITLE
[bug] version of pouch0.2.0 rpm is not right

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#789]
### Ⅰ. Issue Description
The version should be 0.2.0:
```
# pouch version
Arch:            amd64
BuildTime:       2018-02-28T16:12:09.190203683+08:00
GitCommit:
GoVersion:       go1.9.1
KernelVersion:
Os:              linux
Version:         0.1.0
APIVersion:      1.24
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
This has been fixed in #790 
Closing...
