### ISSUE TITLE
[question] Does pouch support multiple runtimes in one kubelet when it works with k8s?

### ISSUE THREAD

**Issue by gaocegege** [alibaba/pouch#800]
Hi, I am trying to integrate pouch with Kubernetes, and I know that pouch supports multiple runtimes, such as runc, runv, and runlxc. Then does pouch CRI support multiple runtimes in one kubelet? For example, we could run hypervisor-based containers and normal containers in one kubelet via pouch cri.

**Comment by allencloud** [comment]
Has kubernetes supported this API option `--runtime-type` in upstream? @YaoZengzeng 
Actually pouch has supported this, however I have no idea whether k8s supports this. @gaocegege

**Comment by YaoZengzeng** [comment]
@gaocegege We can't do it, only runc has been supported now.

And of course we would support multiple runtimes in the future like frakti: you could specify which runtime to run in the annotation of pod, and we'll make it right for you :)

**Comment by gaocegege** [comment]
Thanks for the reply @allencloud @YaoZengzeng and I noticed that frakti has a PR to support mix runtimes.

I am closing the issue, thanks again :)
