### ISSUE TITLE
[feature request] we need the ability to filter some attribute when using pouch inspect

### ISSUE THREAD

**Issue by yyb196** [alibaba/pouch#801]
### Ⅰ. Issue Description
using golang template expression to filter Id:
pouch inspect -f {{.Id}} $ct_name

### Ⅱ. Describe what happened
no support yet

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Thanks for your proposal. I think this is a practical feature. We will support this soon. @yyb196

**Comment by HusterWan** [comment]
@yyb196 @allencloud i will finish this feature soon.
