### ISSUE TITLE
[feature request] when using rich container mode we should persistent env to /etc/profile.d/pouchenv.sh

### ISSUE THREAD

**Issue by yyb196** [alibaba/pouch#810]
### Ⅰ. Issue Description
when using rich container mode, process 1 in container has the right env variables, but if entrypoint which user specified is start by a shell script, the entrypoint program cannot get the correct env variables passed in by Config or in Image.

writing env to /etc/profile.d/pouchenv.sh make every shell script has the correct env variable set, even shell started by sshd also have the same env variables.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I think this feature has been merged into https://github.com/alibaba/runc/pull/11, could we add a test case in pouch daemon side? @wangforthinker 

If we test this feature is already ready in pouch/master, we could close this issue. Thanks a lot.

**Comment by allencloud** [comment]
@wangforthinker 
Could you help to take a look at the status of this issue with the comment @yyb196 added? 

> in alibaba/runc#11 we should escapse some special characters like double quota", $ and back slash \

**Comment by allencloud** [comment]
This has been done. Close this.
