### ISSUE TITLE
[bug] make unit-test failed

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#831]
### Ⅰ. Issue Description
make unit-test has the following error:
```
make unit-test
unit-test
volume_build.go:8:8: cannot find package "github.com/alibaba/pouch/volume/store/boltdb" in any of:
	/tmp/pouchbuild/src/github.com/alibaba/pouch/vendor/github.com/alibaba/pouch/volume/store/boltdb (vendor tree)
	/usr/local/go/src/github.com/alibaba/pouch/volume/store/boltdb (from $GOROOT)
	/tmp/pouchbuild/src/github.com/alibaba/pouch/volume/store/boltdb (from $GOPATH)
	/tmp/pouchbuild/src/github.com/docker/libnetwork/Godeps/_workspace/src/github.com/alibaba/pouch/volume/store/boltdb
make: *** [unit-test] Error 1
```

This is because unit-test target should depend on modules.
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HusterWan** [comment]
No this problem is my dev env, can you check if it's your test env's problem? @Letty5411
