### ISSUE TITLE
[test request] add test for exposed port

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#842]
### Ⅰ. Issue Description
Need to add tests for exposing ports in container, CLI is like following:
pouch run --expose=8001-8002/tcp xxx

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fuweid** [comment]
added case for this.
