### ISSUE TITLE
[test request] tests for login/logout registry

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#843]
### Ⅰ. Issue Description
Need to add tests for login/logout CLI.
We may need to build a test registry in test code then use it to test.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Ace-Tang** [comment]
#908 fix this.
