### ISSUE TITLE
[feature request] Enhance format inspect print

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#857]
### Ⅰ. Issue Description
Now, we have finished format container inspect result, we also need support formatted like image, network, volume inspect result

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
ping @HusterWan 
What is going on on this issue?
