### ISSUE TITLE
[feature required] need network APIs

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#868]
### Ⅰ. Issue Description
The following network APIs are needed:

- [x] /networks/(id or name)/disconnect  https://github.com/alibaba/pouch/pull/1172

- [x] /networks/(id or name)/connect

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HusterWan** [comment]
i will finish the feature: 

> /networks/(id or name)/disconnect

**Comment by rudyfly** [comment]
fixes https://github.com/alibaba/pouch/pull/1187
