### ISSUE TITLE
[proposal]make default registry more standard

### ISSUE THREAD

**Issue by Ace-Tang** [alibaba/pouch#892]
### Ⅰ. Issue Description

```
flagSet.StringVar(&cfg.DefaultRegistry, "default-registry", "registry.hub.docker.com/library/", "Default Image Registry")
```

library determine which namespace you want to pull image in a defined registry, it should not  in `default-registry`.

What do you think.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Yes, I totally agree with you. @Ace-Tang

**Comment by Ace-Tang** [comment]
@allencloud , do you have plan to update this.
