### ISSUE TITLE
[feature required] pouch ps support no-trunc  flag

### ISSUE THREAD

**Issue by 112101160** [alibaba/pouch#903]
### Ⅰ.pouch ps command not support no-trunc flag
`pouch ps` command not support `no-trunc` flag, so i can't get the real imageId ,when i read container config from cgroup directory,  can't get a simple mapping

### Ⅱ. 
![image](https://user-images.githubusercontent.com/12136478/37463635-d6f94c86-2890-11e8-918d-5584a828c7f6.png)

### Ⅲ. 
Through `no-trunc` flag can get real imageId

**Comment by HusterWan** [comment]
@112101160  thanks a lot for your issue, we will support ASAP !

**Comment by HusterWan** [comment]
@ZouRui89 can you help to support this feature, thanks a lot, 😆
