### ISSUE TITLE
[feature required] pouch info  cmd return more result

### ISSUE THREAD

**Issue by 112101160** [alibaba/pouch#920]
### Ⅰ. pouch info  cmd return more result
`pouch info` cmd return more result ,such as daemon port ,listen address and so on

### Ⅱ.
![image](https://user-images.githubusercontent.com/12136478/37596249-847d910a-2bb6-11e8-9776-a2d309d54ffc.png)

**Comment by HusterWan** [comment]
@ZouRui89 Can you help to finish this feature,  thanks a lot.
