### ISSUE TITLE
[bug] when containerd-shim process been killed the related container is still up

### ISSUE THREAD

**Issue by yyb196** [alibaba/pouch#927]
### Ⅰ. Issue Description
when containerd-shim stopped container status should change to exit.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HusterWan** [comment]
Actually, we have a monitor to listen the container's status, if the container exited, will call a hook to change the pouch container' status to stopped, i check today, this function works fine.

@yyb196  can you replay this error again?

**Comment by HusterWan** [comment]
OK, i know the reason, if you first kill the pouchd process then kill then container, the monitor hook will no longer work,  so the container's status will not change.

we will fix this problem soon, thanks a lot @yyb196
