### ISSUE TITLE
[bug report] pouch pull failed

### ISSUE THREAD

**Issue by elianka** [alibaba/pouch#93]
**Issue Description**
is pouch pull function fully completed? and is there any doc about pouch usage?
i got failed when using pouch pull.

**Describe what happened**:
1. i just use pouch pull nginx, and return an error.
![image](https://user-images.githubusercontent.com/4158830/32761048-eba72f3e-c8b6-11e7-8ec8-58a957f6ee39.png)
2. i use the image from alibaba to do pouch pull, also got error.

> ./pouch pull reg.docker.alibaba-inc.com/busybox:latest

![image](https://user-images.githubusercontent.com/4158830/32761079-11c1d1b0-c8b7-11e7-931a-02825d9870f3.png)
![image](https://user-images.githubusercontent.com/4158830/32761114-2b80b440-c8b7-11e7-8348-fc459e4bc420.png)
3. i use pouch create to create a container from image. i found that there is no image in "pouch images".
![image](https://user-images.githubusercontent.com/4158830/32761146-58249a8e-c8b7-11e7-8072-412113753870.png)

**Describe what you expected to happen**:
1. i want to got docker images from all kinds of repository.
2. i think pouch should pull images automatically when i use "pouch create ..."
3. also, pouch pull should be worked.

**How to reproduce it (as minimally and precisely as possible)**:
1. ./pouch pull nginx
2. ./pouch pull reg.docker.alibaba-inc.com/busybox:latest
3.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/4158830/32761307-43934dd0-c8b8-11e7-9e22-80a0290c6652.png)

**Environment**:
- pouch version (use `pouch version`):

> GoVersion:       go1.8.3
KernelVersion:
Os:              linux
Version:         0.1.0-dev
APIVersion:      vx.y.z
Arch:            amd64
BuildTime:       2017-11-14T10:46:18.071044934+08:00
GitCommit:

- OS (e.g. from /etc/os-release):

> NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):

> Linux thinkcenter 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

> runc version 1.0.0-rc4+dev
commit: b2567b37d7b75eb4cf325b77297b140ea686ce8f
spec: 1.0.0

containerd github.com/containerd/containerd v1.0.0-beta.3-8-g732b156 732b1560b495fa0a98d986aa57b365b6111ddae0

**Comment by allencloud** [comment]
I think this has been fixed in https://github.com/alibaba/pouch/pull/266.
Closing this. Feel free to leave a comment if there is more details needed.
