### ISSUE TITLE
[proposal] move client package into vendor

### ISSUE THREAD

**Issue by Ace-Tang** [alibaba/pouch#933]
### Ⅰ. Issue Description
As title says, how about we move client package into vendor, and make it a independent 
project under alibaba. Others can communicate pouch daemon through API way.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I do not think we need to do this. I wondering if we could make package client independent enough, users can only import this package directly. 
https://github.com/alibaba/pouch/pull/962 this pr did this. And in the future, we will move alibaba/pouch/apis/types into this package as well. WDYT? @Ace-Tang

**Comment by allencloud** [comment]
I do not think we need to do this, an independent package is sufficient. Closing this.
And feel free to tell me if you have any further things. @Ace-Tang
