### ISSUE TITLE
[bug] failed to start container: failed to create endpoint

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#939]
### Ⅰ. Issue Description
* 1. firstly, i create a container
```
container-status-sync) -> pouch run -d -m 20m --name test2  registry.hub.docker.com/library/busybox:latest
ffc12aa41ad01907f1cfff80773e62a5345a43c00865088c3c22ed8256d6c047
```

* 2. secondly, i directly kill the container process
```
root@osboxes:wanziren -> ps aux | grep ffc12a
root     30008  0.0  0.1   8924  2948 pts/5    Sl   21:42   0:00 containerd-shim -namespace default -workdir /var/lib/pouch/containerd/root/io.containerd.runtime.v1.linux/default/ffc12aa41ad01907f1cfff80773e62a5345a43c00865088c3c22ed8256d6c047 -address /var/run/containerd.sock -containerd-binary /usr/local/bin/containerd -runtime-root /run
root     30397  0.0  0.0 112660   976 pts/0    R+   21:45   0:00 grep --color=auto ffc12a
root@osboxes:wanziren -> kill 30008
```
* 3. After the process of container exit, pouchd should be notified, and do clean work,  then when we start container again, it should normally be running. but it occured a error:
```
ERRO[2018-03-21 21:18:42.254819869] failed to create endpoint, err: service endpoint with name 9c1dc7bf already exists
ERRO[2018-03-21 21:18:42.254830542] failed to create endpoint: service endpoint with name 9c1dc7bf already exists
``` 

the reason why cannot start container, maybe because the network not be cleaned after the container exit.
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rudyfly** [comment]
already fixed

**Comment by allencloud** [comment]
Could you add a comment identifying which PR fixed this issue? 
If that we could make issue and pr more connective. @rudyfly Thanks a lot.

**Comment by rudyfly** [comment]
https://github.com/alibaba/pouch/pull/728
