### ISSUE TITLE
[bug] flags set in /etc/pouch/config.json cannot be recognized

### ISSUE THREAD

**Issue by yyb196** [alibaba/pouch#950]
### Ⅰ. Issue Description
run pouchd with config file present at default place /etc/pouch/config.json

```
{
  "debug": false,
  "listen":["tcp://0.0.0.0:4243", "unix:///var/run/pouchd.sock"],
  "home-dir": "/home/t4/pouch",
  "tlscacert": "/root/.pouchcert/ca.pem",
  "tlscert": "/root/.pouchcert/cert.pem",
  "tlskey": "/root/.pouchcert/key.pem",
  "tlsverify": true,
  "plugin":"/opt/ali-iaas/pouch/plugin/hook_plugin.so"
}
```

start pouchd error:

time="2018-03-23T11:24:08+08:00" level=error msg="failed to load daemon file: unknow flags: tlscacert, tlscert, tlskey, tlsverify, plugin, debug, listen, home-dir"
time="2018-03-23T11:24:08+08:00" level=error msg="failed to load daemon file: unknow flags: tlskey, tlsverify, plugin, debug, listen, home-dir, tlscacert, tlscert"
time="2018-03-23T11:24:09+08:00" level=error msg="failed to load daemon file: unknow flags: plugin, debug, listen, home-dir, tlscacert, tlscert, tlskey, tlsverify"

previous version (about 21 March) is ok

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yyb196** [comment]
@Ace-Tang @HusterWan PTAL

**Comment by HusterWan** [comment]
@yyb196 This is because of my PR: https://github.com/alibaba/pouch/pull/917
i will fix it soon!
