### ISSUE TITLE
[test]cli_rich_container_test.go:151 failes to validate stdout

### ISSUE THREAD

**Issue by faycheng** [alibaba/pouch#960]
### Ⅰ. Issue Description

sometimes cli_rich_container_test.go:151 fails to validate stdout, [here(tavis log)](https://travis-ci.org/alibaba/pouch/builds/357743327) can give us more details.

```
err=
Command:  /usr/local/bin/pouch exec TestRichContainerInitdWorks ps -ef | grep /sbin/init | awk '{print $1}'
ExitCode: 0
Error:    <nil>
Stdout:   
Stderr:   
Failures:
Expected stdout to contain "1"
----------------------------------------------------------------------
FAIL: /go/src/github.com/alibaba/pouch/test/cli_rich_container_test.go:151: PouchRichContainerSuite.TestRichContainerInitdWorks
/go/src/github.com/alibaba/pouch/test/cli_rich_container_test.go:182:
    c.Assert(checkPidofProcessIsOne(funcname, "/sbin/init"), check.Equals, true)
... obtained bool = false
... expected bool = true

```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Ace-Tang** [comment]
```
Command:  /usr/local/bin/pouch exec TestRichContainerInitdWorks ps -ef | grep /sbin/init | awk '{print $1}'
ExitCode: 1
Error:    exit status 1
Stdout:   error: garbage option
Usage:
 ps [options]
 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.
For more details see ps(1).
Stderr:   
Failures:
ExitCode was 1 expected 0
Expected no error
```
it seems like a ps command error, I have no idea whether it has related with my modification, #1128

**Comment by allencloud** [comment]
Could you take a look on this, whether this is still an issue for PouchContainer? @Letty5411 @Ace-Tang 
If not flaky any more, I think we can close this.
