### ISSUE TITLE
[doc required] need a document to explain upgrade function

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#968]
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I think we already have a Chinese version of this. And then a demand of English version is needed as well. @HusterWan I think we need to keep going.
